import type { DocPageDef } from '../../types';

// Ported from v02.1 Student Handbook (Screen source of truth; print theme
// via --hb-* vars, see handbook-theme.scss). EN+RO colocated.
export const PAGE_06: DocPageDef = {
  id: 'p6',
  label: 'Envelopes',
  en: `<section class="page" id="p6" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 04 · ENVELOPES</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">06</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">ENVELOPES</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Controlling your sound over time. An oscillator through a filter is still a beep: it starts when you press and stops when you let go, and nothing happens in between. Real instruments have a shape — an organ starts and stops instantly, a plucked string starts loud and fades, a bowed note swells. The envelope is that shape, drawn with four knobs and replayed every time you press a key.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 520" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;"><g><path d="M120 430H900" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M120 430V80" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M120 430L300 110L420 250L640 250L780 430" stroke="#FF8A48" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="210" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="28" fill="#FF8A48">A</text><text x="360" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="28" fill="#FF8A48">D</text><text x="530" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="28" fill="#FF8A48">S</text><text x="710" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="28" fill="#FF8A48">R</text><path d="M1000 430H1400" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M1000 430V80" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M1000 430L1008 110L1110 330L1290 336L1350 430" stroke="#FF8A48" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1200" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="26" letter-spacing="2" fill="#DBDBDB">BASS</text><path d="M1460 430H1840" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M1460 430V80" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M1460 430L1620 110L1720 110L1830 430" stroke="#FF8A48" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1650" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="26" letter-spacing="2" fill="#DBDBDB">PAD</text></g></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 4 · THE ADSR ENVELOPE, AND TWO SHAPES: BASS AND PAD.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ADSR</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Attack is the time to rise from silence to the peak. Decay is the time to fall from the peak to the sustain level. Sustain is a level, not a time: where the sound sits for as long as the key is held. Release is the time to fade to silence after the key is let go. Your brain identifies an instrument in its first milliseconds — attack matters most.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TWO ENVELOPES ON FOURM</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">The AMP ENVELOPE drives the amplifier: the loudness contour of a note. The FILTER ENVELOPE drives the cutoff, scaled by ENV AMT in the filter section: the brightness contour. Same shape, two jobs. ENV AMT is bipolar — zero at 12 o&#x27;clock, positive clockwise, inverted counter-clockwise; an amount left at 12 o&#x27;clock is the classic “why is nothing happening”.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">THE COOKBOOK</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Sustain at maximum: the decay has nowhere to fall and does nothing. Sustain at zero: the note dies while you hold it — a pluck. Attack and sustain at zero: percussion. Filter envelope slower than amp envelope: a pad that opens up; the other way round you hear nothing of it, because the amp closes first. Filter decay is the pluck knob: shorten it and the sound bites.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">VELOCITY</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Each envelope has a VELOCITY button: how hard you strike scales that envelope&#x27;s amount (hold it and turn SELECT for the depth; default 127). Velocity to the filter envelope is why soft playing stays dark and hard playing bites — module 07.</p></div></div>
  <p style="margin:16px 0 6px; font-stretch:92%; font-size:12.5px; line-height:1.5;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRY IT</span></p>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:30px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">RECIPE 1 · BASS</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Start from the module-02 sound (A saw + pulse, B triangle an octave down). Amp envelope: ATTACK 0, DECAY 10 o&#x27;clock, SUSTAIN 8 o&#x27;clock, RELEASE 8 o&#x27;clock. Filter envelope: ATTACK 0, DECAY 10 o&#x27;clock, SUSTAIN minimum, RELEASE 8 o&#x27;clock; in the filter, ENV AMT to 3 o&#x27;clock and CUTOFF to 9 o&#x27;clock. Play short, low notes. Now shorten the filter DECAY: more pluck.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">RECIPE 2 · PAD</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Amp envelope: ATTACK 12 o&#x27;clock, DECAY 0, SUSTAIN maximum, RELEASE 2 o&#x27;clock. CUTOFF to 12 o&#x27;clock, ENV AMT to 10 o&#x27;clock; Osc B to saw at octave 0, FREQUENCY nudged slightly for detune. Hold a chord and let it bloom. (Knob positions are starting points, not rules — trust your ears.)</p></div></div>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p6" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 04 · ENVELOPES</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">06</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">ENVELOPES</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Controlezi sunetul în timp. Un oscilator printr-un filtru e încă un bip: pornește când apeși, se oprește când dai drumul, iar între ele nu se întâmplă nimic. Instrumentele adevărate au o formă — orga pornește și se oprește instant, o coardă ciupită pornește tare și se stinge, o notă cu arcușul se umflă. Anvelopa e forma aceea, desenată din patru knob-uri și recântată la fiecare clapă apăsată.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 520" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;"><g><path d="M120 430H900" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M120 430V80" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M120 430L300 110L420 250L640 250L780 430" stroke="#FF8A48" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="210" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="28" fill="#FF8A48">A</text><text x="360" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="28" fill="#FF8A48">D</text><text x="530" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="28" fill="#FF8A48">S</text><text x="710" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="28" fill="#FF8A48">R</text><path d="M1000 430H1400" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M1000 430V80" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M1000 430L1008 110L1110 330L1290 336L1350 430" stroke="#FF8A48" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1200" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="26" letter-spacing="2" fill="#DBDBDB">BASS</text><path d="M1460 430H1840" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M1460 430V80" stroke="#8F8F8F" stroke-width="3.5"></path><path d="M1460 430L1620 110L1720 110L1830 430" stroke="#FF8A48" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1650" y="474" text-anchor="middle" font-family="Lato, sans-serif" font-weight="700" font-size="26" letter-spacing="2" fill="#DBDBDB">PAD</text></g></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 4 · ANVELOPA ADSR ȘI DOUĂ FORME: BASS ȘI PAD.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ADSR</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Attack e timpul de urcare de la liniște la vârf. Decay e timpul de coborâre de la vârf la nivelul de sustain. Sustain e un nivel, nu un timp: acolo stă sunetul cât ții clapa apăsată. Release e timpul de stingere după ce iei degetul. Creierul recunoaște un instrument din primele milisecunde — attack-ul contează cel mai mult.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">CELE DOUĂ ANVELOPE DE PE FOURM</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">AMP ENVELOPE conduce amplificatorul: conturul de volum al notei. FILTER ENVELOPE conduce cutoff-ul, scalat de ENV AMT din secțiunea filtrului: conturul de strălucire. Aceeași formă, două slujbe. ENV AMT e bipolar — zero la ora douăsprezece, pozitiv spre dreapta, inversat spre stânga; un amount lăsat la ora douăsprezece e clasicul „de ce nu se întâmplă nimic".</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">CARTEA DE BUCATE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Sustain la maximum: decay-ul nu mai are unde să cadă și nu face nimic. Sustain la zero: nota moare cât o ții — un pluck. Attack și sustain la zero: percuție. Anvelopa de filtru mai lentă decât cea de amp: un pad care se deschide; invers nu auzi nimic din ea, fiindcă amplificatorul se închide primul. Decay-ul filtrului e knob-ul de pluck: îl scurtezi și sunetul mușcă.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">VELOCITY</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Fiecare anvelopă are un buton VELOCITY: cât de tare lovești scalează amount-ul acelei anvelope (ține-l apăsat și rotește SELECT pentru adâncime; implicit 127). Velocity pe anvelopa de filtru e motivul pentru care cântatul moale rămâne întunecat, iar cel dur mușcă — modulul 07.</p></div></div>
  <p style="margin:16px 0 6px; font-stretch:92%; font-size:12.5px; line-height:1.5;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ÎNCEARCĂ</span></p>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:30px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">REȚETA 1 · BASS</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Pornește de la sunetul din modulul 02 (A saw + pulse, B triangle cu o octavă mai jos). Amp envelope: ATTACK 0, DECAY ora zece, SUSTAIN ora opt, RELEASE ora opt. Filter envelope: ATTACK 0, DECAY ora zece, SUSTAIN minim, RELEASE ora opt; în filtru, ENV AMT la ora trei și CUTOFF la ora nouă. Cântă note scurte, joase. Acum scurtează DECAY-ul filtrului: mai mult pluck.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">REȚETA 2 · PAD</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Amp envelope: ATTACK ora douăsprezece, DECAY 0, SUSTAIN maxim, RELEASE ora două. CUTOFF la ora douăsprezece, ENV AMT la ora zece; Osc B pe saw la octava 0, FREQUENCY mișcat ușor pentru detune. Ține un acord și lasă-l să înflorească. (Pozițiile knob-urilor sunt puncte de plecare, nu reguli — ai încredere în urechi.)</p></div></div>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
