import type { DocPageDef } from '../../types';

// Split off page 04, which ran past the sheet and lost its footer.
export const PAGE_05: DocPageDef = {
  id: 'p5',
  label: 'Build It',
  en: `<section class="page" id="p5" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 02 · OSCILLATORS</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">05</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">BUILD IT</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <div style="margin-top:18px;">
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">PULSE WIDTH &amp; PWM</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Pulse width is the duty cycle of the pulse wave, from square to a thin sliver. Fourm has no dedicated knob: hold PULSE and turn SELECT. 0 is the square; turn either way and the pulse thins until it vanishes at the end of the range (the display counts to -63/+64; the negative side gives the same widths with the pulse flipped). Modulating the width with the LFO — pulse width modulation — keeps the tone in constant, chorus-like motion from a single oscillator. We do it in module 05.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">THE SUB TRICK, AND NOISE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Set Osc B to triangle, one octave below Osc A: the nearly pure wave slips under the main tone and adds weight without clutter. Noise is the only source with no pitch at all, white (full band), pink (warmer), violet (tilted to the highs). Press NOISE (it comes in at full level, 127) then hold it and turn SELECT down for the level. White is the default; pink and violet live in the PARAM menu: press PARAM, turn SELECT to 4: Noise Type, press SELECT, choose, then press PROGRAM to leave the menu. A trace sharpens attacks and adds breath; more of it becomes percussion.</p></div></div>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRY IT</span> &nbsp;From the Basic Program: on Oscillator A press PULSE so both saw and pulse are lit, then hold PULSE and turn SELECT toward the edge and back. On Oscillator B make sure SAW is lit, leave the octave at 0 and raise OSC B in the mixer; now nudge Osc B&#x27;s FREQUENCY slightly off centre and listen to the beating (too far and it splits into two notes) then bring it back to the click at 12 o&#x27;clock. Press SAW to switch it off, press TRI and set Osc B&#x27;s octave to -1: add it, take it away, feel the weight go. Press NOISE (it comes in loud), hold it and turn SELECT down to about 30, just a breath of air. Leave it like this: it is the raw material for module 04.</p>
  </div>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p5" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 02 · OSCILLATORS</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">05</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">CONSTRUIEȘTE</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <div style="margin-top:18px;">
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">PULSE WIDTH &amp; PWM</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Pulse width e factorul de umplere (duty cycle) al undei pulse, de la square până la un fir subțire. Fourm nu are knob dedicat: ține PULSE și rotește SELECT. 0 e square-ul; rotește în oricare direcție și pulsul se subțiază până dispare la capătul cursei (afișajul numără până la -63/+64; partea negativă dă aceleași lățimi, cu pulsul inversat). Modularea lățimii cu LFO — pulse width modulation — ține tonul într-o mișcare continuă, ca de chorus, dintr-un singur oscilator. O facem în modulul 05.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRUCUL SUB, ȘI NOISE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Setează Osc B pe triangle, o octavă sub Osc A: unda aproape pură alunecă sub tonul principal și adaugă greutate fără aglomerație. Noise e singura sursă complet fără înălțime (pitch), white (bandă plină), pink (mai cald), violet (înclinat spre înalte). Apeși NOISE (intră la nivel maxim, 127) apoi îl ții apăsat și rotești SELECT în jos pentru nivel. White e implicit; pink și violet sunt în meniul PARAM: apasă PARAM, rotește SELECT la 4: Noise Type, apasă SELECT, alege, apoi apasă PROGRAM ca să ieși din meniu. O urmă ascute atacurile și adaugă respirație; mai mult devine percuție.</p></div></div>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ÎNCEARCĂ</span> &nbsp;Din Basic Program: pe Oscillator A apasă PULSE, ca să fie aprinse și saw, și pulse, apoi ține PULSE și rotește SELECT spre margine și înapoi. Pe Oscillator B asigură-te că SAW e aprins, lasă octava pe 0 și ridică OSC B din mixer; acum mișcă ușor FREQUENCY-ul lui Osc B de la centru și ascultă bătăile (prea mult și se desparte în două note) apoi adu-l înapoi la clicul de la ora douăsprezece. Apasă SAW ca să-l stingi, apasă TRI și pune octava lui Osc B pe -1: adaugă-l, scoate-l, simte cum pleacă greutatea. Apasă NOISE (intră tare), ține-l apăsat și rotește SELECT în jos până pe la 30, doar un pic de aer. Lasă-l așa: e materia primă pentru modulul 04.</p>
  </div>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
