import type { DocPageDef } from '../../types';

// Troubleshooting, the page for whoever takes the synth home and has nobody
// left to ask. Checklist B2: the eight silent-synth checks in signal order, the
// controls that look alive but are not, and Sequential's own repair order.
export const PAGE_20: DocPageDef = {
  id: 'p20',
  label: 'Troubleshooting',
  en: `<section class="page" id="p20" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">APPENDIX · TROUBLESHOOTING</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">20</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">TROUBLESHOOTING</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:16px 0 0; font-stretch:92%; font-size:14px; line-height:1.65; color:var(--hb-3, #C6C6C6);">This page is for home, when there is nobody beside you to ask. Almost everything that feels broken on an analog synth turns out to be one of the things below.</p>
  <div style="margin-top:22px; display:grid; grid-template-columns:1fr 1fr; column-gap:34px; align-items:start;">
    <div><h2 style="margin:0 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2px; color:var(--hb-5, #FF8A48);">IF YOU HEAR NOTHING</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:11.5px; line-height:1.5; color:var(--hb-2, #8F8F8F);">Take them in this order, it follows the signal through the synth.</p><ol style="margin:7px 0 0; padding-left:17px; font-stretch:92%; font-size:13px; line-height:1.55; color:var(--hb-3, #C6C6C6);"><li style="margin:0 0 9px;">Are the headphones pushed all the way into the splitter, and the splitter into the Fourm?</li><li style="margin:0 0 9px;">Is MAIN, the volume knob, turned up? At zero nothing comes out, however well the rest is set.</li><li style="margin:0 0 9px;">In the MIXER, is at least one source up? The four are OSC A, OSC B, NOISE and FEEDBACK. With all of them at zero the filter has nothing to filter.</li><li style="margin:0 0 9px;">Is CUTOFF closed all the way? Fully closed means the filter lets nothing through. Turn it to the right and listen.</li><li style="margin:0 0 9px;">Is HOLD still lit from the exercise before? Then the synth is holding the old notes and ignoring what you play now. Press it to switch it off.</li><li style="margin:0 0 9px;">Is the mod wheel down while the sound depends on it? A blue route in MODULATION listens to the wheel. Push the wheel up.</li><li style="margin:0 0 9px;">Still nothing? Go back to the starting sound: hold TRANSPOSE DOWN and press PROGRAM.</li><li style="margin:0 0 9px;">Still nothing after that? In the Global menu, 3, Local Control, set it to On. On Off the keyboard stops talking to the synth.</li></ol></div>
    <div><h2 style="margin:0 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2px; color:var(--hb-5, #FF8A48);">IF YOU HEAR SOUND BUT NOTHING CHANGES</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:11.5px; line-height:1.5; color:var(--hb-2, #8F8F8F);">These all look the same on the panel, and all of them make a sound feel stuck.</p><ul style="margin:7px 0 0; padding-left:17px; font-stretch:92%; font-size:13px; line-height:1.55; color:var(--hb-3, #C6C6C6);"><li style="margin:0 0 9px;">An amount knob left at 12 o'clock means zero, not half. It happens on ENV AMT, on the three MODULATION amounts and on the AFTERTOUCH amount. Turn from twelve toward the right.</li><li style="margin:0 0 9px;">A destination that is not lit receives nothing, however far you turn the amount.</li><li style="margin:0 0 9px;">KEY TRACK, VELOCITY and GLIDE have an on button as well as a value. With the LED dark the value does not matter.</li><li style="margin:0 0 9px;">The ATTACK knob does not change the note already sounding, only the next one. Press a fresh key to hear it.</li><li style="margin:0 0 9px;">A knob that feels completely dead: in the Global menu, 4, Pot Mode. If it is not on Jump, the knob does nothing until it reaches the stored value.</li></ul><h2 style="margin:26px 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2px; color:var(--hb-5, #FF8A48);">TO FIX A SOUND</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:11.5px; line-height:1.5; color:var(--hb-2, #8F8F8F);">Sequential's own order, from the source toward the output.</p><ol style="margin:7px 0 0; padding-left:17px; font-stretch:92%; font-size:13px; line-height:1.55; color:var(--hb-3, #C6C6C6);"><li style="margin:0 0 9px;">The oscillators. Right waveshape? Right octave? One or two of them?</li><li style="margin:0 0 9px;">The filter. Too harsh, bring CUTOFF down. Too dull, bring it up. Look at RESONANCE too.</li><li style="margin:0 0 9px;">The envelopes. Starts too abruptly, raise ATTACK. Falls too fast or too slowly, work on DECAY and SUSTAIN. Hangs on after you lift your hand, shorten RELEASE.</li><li style="margin:0 0 9px;">The LFO, last, for anything that should move on its own.</li></ol></div>
  </div>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p20" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">ANEXĂ · DEPANARE</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">20</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">DEPANARE</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:16px 0 0; font-stretch:92%; font-size:14px; line-height:1.65; color:var(--hb-3, #C6C6C6);">Pagina asta e pentru acasă, când nu mai e nimeni lângă tine să întrebi. Aproape tot ce pare stricat la un sintetizator analogic e, de fapt, unul dintre lucrurile de mai jos.</p>
  <div style="margin-top:22px; display:grid; grid-template-columns:1fr 1fr; column-gap:34px; align-items:start;">
    <div><h2 style="margin:0 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2px; color:var(--hb-5, #FF8A48);">DACĂ NU AUZI NIMIC</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:11.5px; line-height:1.5; color:var(--hb-2, #8F8F8F);">Ia-le în ordinea asta, e ordinea în care circulă semnalul prin synth.</p><ol style="margin:7px 0 0; padding-left:17px; font-stretch:92%; font-size:13px; line-height:1.55; color:var(--hb-3, #C6C6C6);"><li style="margin:0 0 9px;">Căștile sunt băgate până la capăt în splitter, iar splitterul în Fourm?</li><li style="margin:0 0 9px;">Knob-ul MAIN, cel de volum, e ridicat? Dacă e pe zero nu iese nimic, oricât de bine ar fi reglat restul.</li><li style="margin:0 0 9px;">În MIXER, e ridicată măcar una dintre surse? Cele patru sunt OSC A, OSC B, NOISE și FEEDBACK. Dacă toate sunt pe zero, filtrul nu are ce să filtreze.</li><li style="margin:0 0 9px;">CUTOFF e închis de tot? Închis complet înseamnă că filtrul nu lasă nimic să treacă. Rotește-l spre dreapta și ascultă.</li><li style="margin:0 0 9px;">HOLD a rămas aprins din exercițiul dinainte? Atunci synth-ul ține notele vechi și nu răspunde la ce cânți acum. Apasă-l ca să-l stingi.</li><li style="margin:0 0 9px;">Mod wheel-ul e jos, dar sunetul depinde de el? O rută albastră din MODULATION ascultă de roată. Împinge roata în sus.</li><li style="margin:0 0 9px;">Tot nimic? Întoarce-te la sunetul de start: ține TRANSPOSE DOWN și apasă PROGRAM.</li><li style="margin:0 0 9px;">Nici așa? În meniul Global, la 3, Local Control, pune-l pe On. Pe Off, claviatura nu mai vorbește cu synth-ul.</li></ol></div>
    <div><h2 style="margin:0 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2px; color:var(--hb-5, #FF8A48);">DACĂ AUZI SUNET, DAR NU SE SCHIMBĂ NIMIC</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:11.5px; line-height:1.5; color:var(--hb-2, #8F8F8F);">Toate arată la fel pe panou și toate fac sunetul să pară blocat.</p><ul style="margin:7px 0 0; padding-left:17px; font-stretch:92%; font-size:13px; line-height:1.55; color:var(--hb-3, #C6C6C6);"><li style="margin:0 0 9px;">Un knob de amount lăsat la ora douăsprezece înseamnă zero, nu jumătate. Se întâmplă la ENV AMT, la cele trei amount-uri din MODULATION și la amount-ul din AFTERTOUCH. Rotește de la douăsprezece spre dreapta.</li><li style="margin:0 0 9px;">O destinație care nu e aprinsă nu primește nimic, oricât ai roti amount-ul.</li><li style="margin:0 0 9px;">KEY TRACK, VELOCITY și GLIDE au și un buton de pornit, nu doar o valoare. Dacă LED-ul e stins, valoarea nu contează.</li><li style="margin:0 0 9px;">Knob-ul ATTACK nu schimbă nota care sună deja, ci pe următoarea. Apasă o clapă nouă ca să auzi diferența.</li><li style="margin:0 0 9px;">Un knob care pare mort de tot: în meniul Global, la 4, Pot Mode. Dacă nu e pe Jump, knob-ul nu face nimic până nu ajunge la valoarea salvată.</li></ul><h2 style="margin:26px 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2px; color:var(--hb-5, #FF8A48);">CA SĂ REPARI UN SUNET</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:11.5px; line-height:1.5; color:var(--hb-2, #8F8F8F);">Ordinea recomandată chiar de Sequential, de la sursă spre ieșire.</p><ol style="margin:7px 0 0; padding-left:17px; font-stretch:92%; font-size:13px; line-height:1.55; color:var(--hb-3, #C6C6C6);"><li style="margin:0 0 9px;">Oscilatoarele. E forma de undă potrivită? Octava potrivită? Cânți cu unul sau cu două?</li><li style="margin:0 0 9px;">Filtrul. Prea aspru, coboară CUTOFF. Prea mat, ridică-l. Uită-te și la RESONANCE.</li><li style="margin:0 0 9px;">Anvelopele. Pornește prea brusc, mărește ATTACK. Cade prea repede sau prea încet, umblă la DECAY și SUSTAIN. Rămâne în aer după ce ridici mâna, scurtează RELEASE.</li><li style="margin:0 0 9px;">LFO-ul, la final, pentru tot ce vrei să se miște singur.</li></ol></div>
  </div>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
