import type { DocPageDef } from '../../types';

// Ported from v02.1 Student Handbook (Screen source of truth; print theme
// via --hb-* vars, see handbook-theme.scss). EN+RO colocated.
export const PAGE_04: DocPageDef = {
  id: 'p4',
  en: `<section class="page" id="p4" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 02 · OSCILLATORS</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">04</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">OSCILLATORS</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Where every sound is born. Each of Fourm&#x27;s two oscillators offers a set of waveshapes, selected with dedicated buttons and freely combined: Oscillator A has sawtooth and pulse, Oscillator B adds a triangle. The shape you choose decides the harmonic material everything downstream will carve into — and two humble additions, a sub layer and a pinch of noise, separate thin patches from full ones.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 558" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;">
<defs><linearGradient id="gg0_m02en" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0"></stop><stop offset="0.25" stop-color="#EDEDED" stop-opacity="0.5"></stop><stop offset="0.62" stop-color="#FF8A48" stop-opacity="0.8"></stop><stop offset="1" stop-color="#FF8A48" stop-opacity="0"></stop></linearGradient></defs>
<rect x="4" y="4" width="1858" height="550" rx="30" fill="rgba(255,255,255,0.02)" stroke="#454545" stroke-width="2.5"></rect>
<rect x="120" y="150" width="760" height="330" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="500" y="198" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">OSC A</text><path d="M200 325L260 215L260 325L380 215L380 325L440 215" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="320" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">SAW</text><path d="M560 325L560 215L620 215L620 325L680 325L680 215L740 215L740 325L800 325" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="680" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">PULSE</text><text x="500" y="432" text-anchor="middle" font-family="Lato, sans-serif" font-size="25" letter-spacing="2" fill="#C6C6C6">EVEN + ODD HARMONICS · BRIGHT &amp; BUZZY</text><rect x="986" y="150" width="760" height="330" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="1366" y="198" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">OSC B</text><path d="M1046 325L1091 215L1136 325L1181 215L1226 325" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1136" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">TRI</text><path d="M1286 325L1331 215L1331 325L1421 215L1421 325L1466 215" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1376" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">SAW</text><path d="M1526 325L1526 215L1571 215L1571 325L1616 325L1616 215L1661 215L1661 325L1706 325" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1616" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">PULSE</text><text x="1366" y="432" text-anchor="middle" font-family="Lato, sans-serif" font-size="25" letter-spacing="2" fill="#C6C6C6">ADDS WEIGHT, DETUNE, LO MODES</text><text x="933" y="522" text-anchor="middle" font-family="Lato, sans-serif" font-size="27" font-weight="700" letter-spacing="1" fill="#FF8A48">PRESS SEVERAL SHAPE BUTTONS AT ONCE: THE WAVES COMBINE</text></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 2 · THE WAVESHAPES: SAWTOOTH, TRIANGLE, PULSE — AND THE SUB TRICK: OSC B, TRIANGLE, ONE OCTAVE DOWN.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SAW · TRI · PULSE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Sawtooth carries every harmonic: bright and full, the classic synth backbone, the sound of brass and strings. Triangle is soft and nearly pure, the natural sub layer. Pulse sits in between — hollow like a clarinet at square, thin and reedy as it narrows — and its character depends on its width.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">OCTAVES &amp; TUNING</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Each oscillator has five octave positions, from -2 to +2. Setting A and B an octave apart is the fastest way to a bigger sound. FREQUENCY fine-tunes by up to seven semitones either way; a few cents of detune between A and B makes the two waves beat against each other, and the tone starts to breathe. Push it too far and you hear two notes — bring it back until it just shimmers.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">PULSE WIDTH &amp; PWM</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Pulse width is the duty cycle of the pulse wave, from square to a thin sliver. Fourm has no dedicated knob: hold PULSE and turn SELECT (0 is square; toward ±100 the pulse thins until it disappears). Modulating the width with the LFO — pulse width modulation — keeps the tone in constant, chorus-like motion from a single oscillator. We do it in module 05.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">THE SUB TRICK, AND NOISE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Set Osc B to triangle, one octave below Osc A: the nearly pure wave slips under the main tone and adds weight without clutter. Noise is the only source with no pitch at all — white (full band), pink (warmer), violet (tilted to the highs); press NOISE, then hold it and turn SELECT for level. A trace sharpens attacks and adds breath; more of it becomes percussion.</p></div></div>
  <div style="margin-top:14px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Below the octaves, Osc B has two low modes: LO1 still follows the keyboard, LO2 free-runs. Down there it stops being a voice and becomes a modulation source, like an extra, polyphonic LFO. Sync locks Oscillator A&#x27;s cycle to Oscillator B for aggressive, tearing timbres.</p></div>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRY IT</span> &nbsp;From the Basic Program: on Oscillator A press PULSE so both saw and pulse are lit, then hold PULSE and turn SELECT toward the edge and back. On Oscillator B press TRI, set the octave to -1 and raise OSC B in the mixer: add it, take it away, feel the weight go. Nudge Osc B&#x27;s FREQUENCY slightly off centre and listen to the beating; too far and it splits into two notes. Press NOISE, hold it and turn SELECT down to about 30 — just a breath of air.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p4" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 02 · OSCILLATORS</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">04</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">OSCILLATORS</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Aici se naște orice sunet. Fiecare dintre cele două oscilatoare ale lui Fourm oferă un set de forme de undă, alese din butoane dedicate și combinabile liber: Oscillator A are sawtooth și pulse, Oscillator B adaugă un triangle. Forma pe care o alegi decide materialul armonic în care va sculpta tot ce urmează — iar două adăugiri modeste, un strat de sub și un vârf de noise, despart patch-urile subțiri de cele pline.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 558" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;">
<defs><linearGradient id="gg1_m02ro" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0"></stop><stop offset="0.25" stop-color="#EDEDED" stop-opacity="0.5"></stop><stop offset="0.62" stop-color="#FF8A48" stop-opacity="0.8"></stop><stop offset="1" stop-color="#FF8A48" stop-opacity="0"></stop></linearGradient></defs>
<rect x="4" y="4" width="1858" height="550" rx="30" fill="rgba(255,255,255,0.02)" stroke="#454545" stroke-width="2.5"></rect>
<rect x="120" y="150" width="760" height="330" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="500" y="198" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">OSC A</text><path d="M200 325L260 215L260 325L380 215L380 325L440 215" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="320" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">SAW</text><path d="M560 325L560 215L620 215L620 325L680 325L680 215L740 215L740 325L800 325" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="680" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">PULSE</text><text x="500" y="432" text-anchor="middle" font-family="Lato, sans-serif" font-size="25" letter-spacing="2" fill="#C6C6C6">ARMONICE PARE + IMPARE · STRĂLUCITOR</text><rect x="986" y="150" width="760" height="330" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="1366" y="198" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">OSC B</text><path d="M1046 325L1091 215L1136 325L1181 215L1226 325" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1136" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">TRI</text><path d="M1286 325L1331 215L1331 325L1421 215L1421 325L1466 215" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1376" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">SAW</text><path d="M1526 325L1526 215L1571 215L1571 325L1616 325L1616 215L1661 215L1661 325L1706 325" stroke="#FF8A48" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"></path><text x="1616" y="350" text-anchor="middle" font-family="Lato, sans-serif" font-size="26" letter-spacing="2" fill="#C6C6C6">PULSE</text><text x="1366" y="432" text-anchor="middle" font-family="Lato, sans-serif" font-size="25" letter-spacing="2" fill="#C6C6C6">ADAUGĂ GREUTATE, DETUNE, LO1/LO2</text><text x="933" y="522" text-anchor="middle" font-family="Lato, sans-serif" font-size="27" font-weight="700" letter-spacing="1" fill="#FF8A48">APASĂ MAI MULTE BUTOANE DE SHAPE SIMULTAN: UNDELE SE COMBINĂ</text></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 2 · FORMELE DE UNDĂ: SAWTOOTH, TRIANGLE, PULSE — ȘI TRUCUL SUB: OSC B, TRIANGLE, O OCTAVĂ MAI JOS.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SAW · TRI · PULSE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Sawtooth conține toate armonicele: strălucitor și plin, coloana vertebrală a synth-ului, sunetul de alămuri și coarde. Triangle e moale și aproape pur, stratul natural de sub. Pulse stă între ele — gol ca un clarinet când e pătrat, subțire și nazal pe măsură ce se îngustează — iar caracterul lui depinde de lățime.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">OCTAVES &amp; TUNING</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Fiecare oscilator are cinci poziții de octavă, de la -2 la +2. A și B la o octavă distanță e cel mai rapid drum spre un sunet mai mare. FREQUENCY face acordajul fin, până la șapte semitonuri în fiecare direcție; câțiva cenți de detune între A și B fac cele două unde să bată una în alta, iar tonul începe să respire. Împinge prea departe și auzi două note — adu-l înapoi până când doar sclipește.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">PULSE WIDTH &amp; PWM</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Pulse width e ciclul de umplere al undei pulse, de la pătrat până la un fir subțire. Fourm nu are knob dedicat: ține PULSE și rotește SELECT (0 e pătratul; spre ±100 pulsul se subțiază până dispare). Modularea lățimii cu LFO — pulse width modulation — ține tonul într-o mișcare continuă, ca de chorus, dintr-un singur oscilator. O facem în modulul 05.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRUCUL SUB, ȘI NOISE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Setează Osc B pe triangle, o octavă sub Osc A: unda aproape pură alunecă sub tonul principal și adaugă greutate fără aglomerație. Noise e singura sursă complet fără înălțime — white (bandă plină), pink (mai cald), violet (înclinat spre înalte); apeși NOISE, apoi îl ții apăsat și rotești SELECT pentru nivel. O urmă ascute atacurile și adaugă respirație; mai mult devine percuție.</p></div></div>
  <div style="margin-top:14px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Sub octave, Osc B are două moduri joase: LO1 urmează în continuare claviatura, LO2 merge liber. Acolo jos nu mai e o voce, devine sursă de modulație, ca un LFO în plus, polifonic. Sync leagă ciclul lui Oscillator A de Oscillator B, pentru timbre agresive, sfâșiate.</p></div>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ÎNCEARCĂ</span> &nbsp;Din Basic Program: pe Oscillator A apasă PULSE, ca să fie aprinse și saw, și pulse, apoi ține PULSE și rotește SELECT spre margine și înapoi. Pe Oscillator B apasă TRI, pune octava pe -1 și ridică OSC B din mixer: adaugă-l, scoate-l, simte cum pleacă greutatea. Mișcă ușor FREQUENCY-ul lui Osc B de la centru și ascultă bătăile; prea mult și se desparte în două note. Apasă NOISE, ține-l apăsat și rotește SELECT până pe la 30 — doar un pic de aer.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
