import type { DocPageDef } from '../../types';

// Page 9 carried more than an A4 shows: the exercise and the page footer ran
// off the bottom and were clipped. Its LEVEL 2 box and its exercise live here
// instead, and the glide modes get one line each again.
export const PAGE_10: DocPageDef = {
  id: 'p10',
  label: 'Expression · hands on',
  en: `<section class="page" id="p10" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 07 · EXPRESSION</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">10</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">HANDS ON</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:16px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">The settings behind what you just played, and then the exercise. Take the exercise slowly: every step is one hand on one control, and the point is to hear the change, not to get through the list.</p>
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Four glide modes, from GLIDE + SELECT or from Param 17. The A stands for Auto: the glide happens by itself, only when two notes overlap — that is, only when you hold one note until you press the next.</p><p style="margin:3px 0 0 13px; text-indent:-13px; font-stretch:92%; font-size:12px; line-height:1.45; color:var(--hb-9, #9A9A9A);">·&nbsp;<b style="color:var(--hb-3, #C6C6C6);">Fixed Rate</b> — the default. The rate is fixed, so a bigger jump takes longer.</p><p style="margin:3px 0 0 13px; text-indent:-13px; font-stretch:92%; font-size:12px; line-height:1.45; color:var(--hb-9, #9A9A9A);">·&nbsp;<b style="color:var(--hb-3, #C6C6C6);">Fixed Rate A</b> — the same, but it glides only when you play legato.</p><p style="margin:3px 0 0 13px; text-indent:-13px; font-stretch:92%; font-size:12px; line-height:1.45; color:var(--hb-9, #9A9A9A);">·&nbsp;<b style="color:var(--hb-3, #C6C6C6);">Fixed Time</b> — every jump takes the same time, however big it is.</p><p style="margin:3px 0 0 13px; text-indent:-13px; font-stretch:92%; font-size:12px; line-height:1.45; color:var(--hb-9, #9A9A9A);">·&nbsp;<b style="color:var(--hb-3, #C6C6C6);">Fixed Time A</b> — the same, legato only.</p></div>
  <p style="margin:12px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRY IT</span> &nbsp;If HOLD is still lit from the last exercise, press it to let the notes go, and set the filter&#x27;s ENV AMT to about 2 o&#x27;clock. In the FILTER ENVELOPE press VELOCITY so it lights; play soft, then hard. In AFTERTOUCH press the DEST button under FILT / AMP until only FILT is lit and turn AMOUNT from 12 o&#x27;clock to 2 o&#x27;clock; hold a three-note chord and press into just the top note. Now turn AMOUNT to 10 o&#x27;clock: pressure closes the filter instead. Hold UNISON and turn SELECT to 1 voice, press GLIDE, set RATE to 10 o&#x27;clock and play a bass line one note at a time: the notes slide into each other. Then press the FILT / AMP button until it goes dark, press the FREQ A / FREQ B button until both are lit, and bring AMOUNT back to just right of 12 o&#x27;clock. Now pressing harder bends the pitch upward. The keyboard senses each key on its own, so only the note you lean on bends; the others stay where they are.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p10" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 07 · EXPRESSION</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">10</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">PUNE MÂNA</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:16px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Setările din spatele a ceea ce tocmai ai cântat, și apoi exercițiul. Ia exercițiul încet: fiecare pas e o mână pe un singur buton, iar scopul e să auzi schimbarea, nu să termini lista.</p>
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Patru moduri de glide, din GLIDE + SELECT sau din Param 17. „A” vine de la Auto: alunecarea se face de la sine, doar când două note se suprapun — adică doar dacă ții o notă apăsată până o apeși pe următoarea.</p><p style="margin:3px 0 0 13px; text-indent:-13px; font-stretch:92%; font-size:12px; line-height:1.45; color:var(--hb-9, #9A9A9A);">·&nbsp;<b style="color:var(--hb-3, #C6C6C6);">Fixed Rate</b> — cel implicit. Viteza e fixă, deci un salt mai mare durează mai mult.</p><p style="margin:3px 0 0 13px; text-indent:-13px; font-stretch:92%; font-size:12px; line-height:1.45; color:var(--hb-9, #9A9A9A);">·&nbsp;<b style="color:var(--hb-3, #C6C6C6);">Fixed Rate A</b> — la fel, dar alunecă doar dacă joci legato.</p><p style="margin:3px 0 0 13px; text-indent:-13px; font-stretch:92%; font-size:12px; line-height:1.45; color:var(--hb-9, #9A9A9A);">·&nbsp;<b style="color:var(--hb-3, #C6C6C6);">Fixed Time</b> — orice salt durează la fel, oricât de mare ar fi.</p><p style="margin:3px 0 0 13px; text-indent:-13px; font-stretch:92%; font-size:12px; line-height:1.45; color:var(--hb-9, #9A9A9A);">·&nbsp;<b style="color:var(--hb-3, #C6C6C6);">Fixed Time A</b> — la fel, tot doar legato.</p></div>
  <p style="margin:12px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ÎNCEARCĂ</span> &nbsp;Dacă HOLD e încă aprins din exercițiul dinainte, apasă-l ca să lași notele să se stingă, și pune ENV AMT din filtru pe la ora două. În FILTER ENVELOPE apasă VELOCITY ca să se aprindă; cântă moale, apoi tare. În AFTERTOUCH apasă butonul DEST de sub FILT / AMP până rămâne aprins doar FILT și rotește AMOUNT de la ora douăsprezece la ora două; ține un acord de trei note și apasă doar în nota de sus. Acum rotește AMOUNT la ora zece: presiunea închide filtrul. Ține UNISON și rotește SELECT la 1 voce, apasă GLIDE, pune RATE la ora zece și cântă o linie de bass, notă cu notă: notele alunecă una în alta. Apoi apasă butonul FILT / AMP până se stinge, apasă butonul FREQ A / FREQ B până sunt aprinse amândouă și adu AMOUNT înapoi puțin la dreapta de ora douăsprezece. Acum, dacă apeși mai tare, nota se îndoaie în sus. Claviatura simte fiecare clapă separat, deci se îndoaie doar nota pe care apeși, celelalte rămân pe loc.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
