import type { DocPageDef } from '../../types';

// Split off page 07, which ran past the sheet and lost its footer.
export const PAGE_11: DocPageDef = {
  id: 'p11',
  label: 'Wire It Up',
  en: `<section class="page" id="p11" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 05 · LFO &amp; MODULATION</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">11</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">WIRE IT UP</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <div style="margin-top:18px;">
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Taken below the octaves, in LO1 or LO2, Osc B stops being a voice and becomes a second LFO, one for each note you hold. In LO1 it follows the keyboard, so high notes wobble faster than low ones. In LO2 it free-runs, at the same speed for every note. Osc B keeps modulating with its mixer level at zero: the mixer sets how loud Osc B is as a sound, while the modulation is taken separately, through the OSC B route. Down at lo1 and lo2 you want it at zero anyway, because as audio it is only a faint clicking. The filter envelope is a modulation source too: FILT ENV → FREQ A gives the “pitch blip” of synth brass; → PW A, a pulse that narrows over the note.</p></div>
  <p style="margin:12px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRY IT</span> &nbsp;On the pad from module 04: in the LFO section make sure TRI is the only lit shape and set FREQUENCY to about 10 o&#x27;clock. In the modulation section look at the LEDs: from the Basic Program, ROUTE under LFO, FREQ A and FREQ B are already blue, the mod-wheel bus. If one of them is dark or red, press it until it turns blue. Push the mod wheel all the way up, hold a chord and turn the LFO AMOUNT from 12 o&#x27;clock clockwise until you hear the vibrato; bring the wheel down and up again: vibrato that you control. Keep the wheel up. Now press FREQ A and FREQ B until they go dark, press PW A until it is blue: the pulse breathes; then CUTOFF until it is blue: wah. Faster FREQUENCY, more AMOUNT: go too far, then bring it back.</p>
  </div>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p11" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 05 · LFO &amp; MODULATION</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">11</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">FĂ LEGĂTURA</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <div style="margin-top:18px;">
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Coborât sub octave, în LO1 sau LO2, Osc B nu mai e o voce, ci un al doilea LFO, câte unul pentru fiecare notă apăsată. În LO1 urmează claviatura, deci notele înalte tremură mai repede decât cele joase. În LO2 merge liber, cu aceeași viteză pentru toate. Osc B modulează și cu nivelul lui din mixer la zero: mixerul stabilește cât de tare se aude Osc B ca sunet, iar modulația e luată separat, prin ruta OSC B din MODULATION. La lo1 și lo2 chiar vrei să fie pe zero, fiindcă drept sunet nu se aude decât ca un ticăit slab. Anvelopa de filtru e și ea sursă de modulație: FILT ENV → FREQ A dă „pitch blip"-ul alămurilor de synth; → PW A, un puls care se îngustează pe durata notei.</p></div>
  <p style="margin:12px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ÎNCEARCĂ</span> &nbsp;Pe pad-ul din modulul 04: în secțiunea LFO asigură-te că TRI e singura formă aprinsă și pune FREQUENCY pe la ora zece. În secțiunea Modulation uită-te la LED-uri: din Basic Program, ROUTE de sub LFO, FREQ A și FREQ B sunt deja albastre, bus-ul mod wheel. Dacă vreunul e stins sau roșu, apasă-l până devine albastru. Împinge mod wheel-ul până sus, ține un acord și rotește AMOUNT-ul LFO-ului de la ora douăsprezece spre dreapta până auzi vibrato-ul; coboară roata și ridic-o din nou: vibrato pe care îl controlezi tu. Ține roata sus. Acum apasă FREQ A și FREQ B până se sting, apasă PW A până e albastru: pulsul respiră; apoi CUTOFF până e albastru: wah. FREQUENCY mai rapid, AMOUNT mai mult: mergi prea departe, apoi adu înapoi.</p>
  </div>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
