import type { DocPageDef } from '../../types';

// Ported from v02.1 Student Handbook (Screen source of truth; print theme
// via --hb-* vars, see handbook-theme.scss). EN+RO colocated.
export const PAGE_09: DocPageDef = {
  id: 'p9',
  label: 'Expression',
  en: `<section class="page" id="p9" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 07 · EXPRESSION</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">09</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">EXPRESSION</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Play it, don&#x27;t just press it. Envelopes and LFOs make every note the same; what makes it music is what your hands add. Velocity reads how fast you strike, aftertouch reads how hard you keep pressing, glide lets one note slide into the next. Fourm&#x27;s Tactive keybed senses pressure under every single key — polyphonic aftertouch — so each finger shapes its own note.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 558" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;">
<defs><linearGradient id="gg28_m05en" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0"></stop><stop offset="0.25" stop-color="#EDEDED" stop-opacity="0.5"></stop><stop offset="0.62" stop-color="#FF8A48" stop-opacity="0.8"></stop><stop offset="1" stop-color="#FF8A48" stop-opacity="0"></stop></linearGradient></defs>
<rect x="4" y="4" width="1858" height="550" rx="30" fill="rgba(255,255,255,0.02)" stroke="#454545" stroke-width="2.5"></rect>
<rect x="263" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="363" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">FREQ A</text><rect x="493" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="593" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">FREQ B</text><rect x="723" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="823" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">FILT</text><rect x="953" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="1053" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">AMP</text><rect x="1183" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="1283" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">LFO FREQ</text><rect x="1413" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="1513" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">LFO AMT</text><text x="933" y="340" text-anchor="middle" font-family="Lato, sans-serif" font-size="25" letter-spacing="2" fill="#C6C6C6">PICK DESTINATIONS WITH THE DEST BUTTONS: TWO PER BUS</text><text x="933" y="430" text-anchor="middle" font-family="Lato, sans-serif" font-size="27" font-weight="700" letter-spacing="1" fill="#FF8A48">ONE AMOUNT KNOB, POSITIVE OR NEGATIVE</text><text x="933" y="490" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#C6C6C6">PRESS HARDER WITH +FILT: THE SOUND OPENS · WITH −FILT: IT CLOSES</text></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 7 · PRESSURE ROUTING: ONE AMOUNT, SIX DESTINATIONS.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">VELOCITY</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Louder notes on real instruments also have more harmonics, which is why velocity belongs on the filter, not just the volume. Each envelope has a VELOCITY button: press it, and how hard you play scales that envelope&#x27;s depth (hold it and turn SELECT for the amount). Velocity to the filter envelope: soft playing stays dark, hard playing bites. Five response curves in Global — Soft+, Soft, Medium, Hard, Hard+ — match the keybed to your touch.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">POLY AFTERTOUCH</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">After the key is down, extra pressure becomes a continuous modulator, per key. Lean into one note of a held chord and only that note blooms — like blowing harder into a flute: press harder, brighter. Mono aftertouch, on most keyboards, moves every voice at once; per-note aftertouch used to be a rarity — the CS-80, the Prophet T8 — and Fourm has it natively.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">PRESSURE ROUTING</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Six destinations — FREQ A, FREQ B, FILT, AMP, LFO FREQ, LFO AMT — chosen with the three DEST buttons, two per bus, and one AMOUNT knob, positive or negative. Cutoff is the classic: press for brightness, release to relax; a negative amount closes the filter instead. Pitch is for the brave.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">GLIDE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Also called portamento: the pitch slides from the previous note to the next instead of jumping. Press GLIDE and set RATE — glide on with rate at zero does nothing. Subtle settings, barely a slur, sound the most musical: it is the difference between a keyboard melody and a phrase that sounds like a voice.</p></div></div>
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Four glide modes (hold GLIDE and turn SELECT): Fixed Rate (default; larger intervals take longer), Fixed Time (any interval takes the same time), and their legato variants (glide only when notes overlap). The legato and fixed-time modes appear when Unison is on. Aftertouch curves live in Global too.</p></div>
  <p style="margin:12px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRY IT</span> &nbsp;In the FILTER ENVELOPE press VELOCITY; play soft, then hard. In AFTERTOUCH press the DEST button under FILT / AMP until only FILT is lit, turn AMOUNT to 2 o&#x27;clock; hold a three-note chord and press into just the top note. Now turn AMOUNT to 10 o&#x27;clock: pressure closes the filter instead. Press GLIDE, set RATE to 10 o&#x27;clock and play a bass line: the notes slide. Then move the pressure to FREQ A and FREQ B with a small amount — a bend, per finger.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p9" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 07 · EXPRESSION</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">09</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">EXPRESSION</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Cântă, nu doar apăsa. Anvelopele și LFO-urile fac fiecare notă la fel; ce transformă asta în muzică e ce adaugă mâinile tale. Velocity citește cât de repede lovești, aftertouch citește cât de tare continui să apeși, glide leagă o notă de următoarea. Claviatura Tactive a lui Fourm simte presiunea sub fiecare clapă în parte — polyphonic aftertouch — deci fiecare deget își modelează propria notă.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 558" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;">
<defs><linearGradient id="gg29_m05ro" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0"></stop><stop offset="0.25" stop-color="#EDEDED" stop-opacity="0.5"></stop><stop offset="0.62" stop-color="#FF8A48" stop-opacity="0.8"></stop><stop offset="1" stop-color="#FF8A48" stop-opacity="0"></stop></linearGradient></defs>
<rect x="4" y="4" width="1858" height="550" rx="30" fill="rgba(255,255,255,0.02)" stroke="#454545" stroke-width="2.5"></rect>
<rect x="263" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="363" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">FREQ A</text><rect x="493" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="593" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">FREQ B</text><rect x="723" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="823" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">FILT</text><rect x="953" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="1053" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">AMP</text><rect x="1183" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="1283" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">LFO FREQ</text><rect x="1413" y="220" width="200" height="52" rx="10" fill="none" stroke="#8F8F8F" stroke-width="2"></rect><text x="1513" y="254" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#DBDBDB">LFO AMT</text><text x="933" y="340" text-anchor="middle" font-family="Lato, sans-serif" font-size="25" letter-spacing="2" fill="#C6C6C6">ALEGE DESTINAȚIILE CU BUTOANELE DEST: CÂTE DOUĂ PE BUS</text><text x="933" y="430" text-anchor="middle" font-family="Lato, sans-serif" font-size="27" font-weight="700" letter-spacing="1" fill="#FF8A48">UN SINGUR KNOB DE AMOUNT, POZITIV SAU NEGATIV</text><text x="933" y="490" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#C6C6C6">APASĂ MAI TARE CU +FILT: SUNETUL SE DESCHIDE · CU −FILT: SE ÎNCHIDE</text></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 7 · RUTAREA PRESIUNII: O SINGURĂ CANTITATE, ȘASE DESTINAȚII.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">VELOCITY</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">La instrumentele reale, notele mai tari au și mai multe armonice — de aceea velocity merge pe filtru, nu doar pe volum. Fiecare anvelopă are un buton VELOCITY: îl apeși și cât de tare cânți scalează adâncimea acelei anvelope (ține-l apăsat și rotește SELECT pentru cantitate). Velocity pe anvelopa de filtru: cântatul moale rămâne întunecat, cel dur mușcă. Cinci curbe de răspuns în Global — Soft+, Soft, Medium, Hard, Hard+ — potrivesc claviatura cu tușeul tău.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">POLY AFTERTOUCH</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">După ce clapa e jos, presiunea în plus devine un modulator continuu, pe fiecare clapă. Apeși mai tare într-o notă dintr-un acord ținut și doar ea înflorește — ca și cum ai sufla mai tare într-un flaut: apeși mai tare, sună mai luminos. Aftertouch-ul mono, de pe majoritatea claviaturilor, mișcă toate vocile deodată; cel per notă era o raritate — CS-80, Prophet T8 — iar Fourm îl are nativ.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">RUTAREA PRESIUNII</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Șase destinații — FREQ A, FREQ B, FILT, AMP, LFO FREQ, LFO AMT — alese cu cele trei butoane DEST, câte două pe bus, și un singur knob AMOUNT, pozitiv sau negativ. Cutoff e clasicul: apeși pentru strălucire, eliberezi ca să se relaxeze; cu un amount negativ, presiunea închide filtrul. Pitch e pentru curajoși.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">GLIDE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Numit și portamento: înălțimea alunecă de la nota anterioară la următoarea, în loc să sară. Apeși GLIDE și setezi RATE — glide pornit cu rate pe zero nu face nimic. Setările subtile, abia un legato, sună cel mai muzical: e diferența dintre o melodie de claviatură și o frază care sună a voce.</p></div></div>
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Patru moduri de glide (ține GLIDE și rotește SELECT): Fixed Rate (implicit; intervalele mari durează mai mult), Fixed Time (orice interval durează la fel) și variantele lor legato (alunecă doar când notele se suprapun). Modurile legato și fixed-time apar când Unison e pornit. Curbele de aftertouch sunt tot în Global.</p></div>
  <p style="margin:12px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ÎNCEARCĂ</span> &nbsp;În FILTER ENVELOPE apasă VELOCITY; cântă moale, apoi tare. În AFTERTOUCH apasă butonul DEST de sub FILT / AMP până rămâne aprins doar FILT, rotește AMOUNT la ora două; ține un acord de trei note și apasă doar în nota de sus. Acum rotește AMOUNT la ora zece: presiunea închide filtrul. Apasă GLIDE, pune RATE la ora zece și cântă o linie de bass: notele alunecă. Apoi mută presiunea pe FREQ A și FREQ B, cu un amount mic — un bend, pe deget.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
