import type { DocPageDef } from '../../types';

// Ported from v02.1 Student Handbook (Screen source of truth; print theme
// via --hb-* vars, see handbook-theme.scss). EN+RO colocated.
export const PAGE_02: DocPageDef = {
  id: 'p2',
  label: 'Before we start',
  en: `<section class="page" id="p2" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 00 · WELCOME &amp; SETUP</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">02</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">BEFORE WE START</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <div style="margin-top:26px;">
  <p style="margin:0 0 0; font-stretch:92%; font-size:15px; line-height:1.7; color:var(--hb-3, #C6C6C6);">Set MAIN, the volume knob, to about 12 o&#x27;clock and leave it there: from here on the sound changes with the other knobs, not with the volume.</p>
  <p style="margin:18px 0 0; font-stretch:92%; font-size:15px; line-height:1.7; color:var(--hb-3, #C6C6C6);">Home base is the Basic Program: a plain sawtooth with the filter open and a vibrato already wired to the mod wheel (we use it in module 05). It doesn&#x27;t matter if your sound doesn&#x27;t come out identical to the recipe, that is the good part of exploring. If you get lost, come back to the Basic Program: hold TRANSPOSE DOWN and press PROGRAM. One thing to avoid: when the display shows a program name, turning SELECT loads another program and the sound you built is gone. Turn it only when a step asks you to, and when the display shows a parameter instead of a program name.</p>
  <p style="margin:18px 0 0; font-stretch:92%; font-size:15px; line-height:1.7; color:var(--hb-3, #C6C6C6);">This handbook follows the workshop stop by stop. Each module has one page: the idea in a few lines, the diagram from the screen, and a TRY IT you can do at the synth. The words we use are collected in the glossary at the back. Read one module, turn one knob, listen.</p>
  </div>
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">WHAT THE BASIC PROGRAM IS</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Osc A on sawtooth, full up in the mixer; on Osc B the sawtooth is lit too, but its mixer level sits at zero, so you hear nothing from it until you raise it. Filter open, no resonance, KEY TRACK off; both envelopes plain, VELOCITY off; feedback and noise off; in MODULATION the LFO is already routed to FREQ A and FREQ B on the mod-wheel bus, so raise the wheel and you have vibrato; the arpeggiator off. The same program fills the whole of User bank 2, and it is what TRANSPOSE DOWN + PROGRAM brings back.</p></div><div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SIX PAIRS OF WORDS</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">When you describe a sound, reach for these before anything else: bright / dark (how much high end) · thin / fat (how much body) · hollow / full (square-like or saw-like) · soft / hard (how it starts) · pluck / pad (does it die or does it stay) · static / moving (does anything change while it sounds).</p><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Say which one you hear, then look for the knob that moves it: brightness lives at CUTOFF, body at the sub and the detune, hollowness at the waveshape, the start at ATTACK, the pluck at DECAY and SUSTAIN, the movement at the LFO.</p></div>
  <p style="margin:8px 0 0; font-style:italic; font-stretch:92%; font-size:11.5px; line-height:1.4; color:var(--hb-9, #9A9A9A);">Sequential&#x27;s Prophet-5, in 1978, was the first fully programmable polysynth: before it a patch lived on a sheet of paper, rebuilt knob by knob.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p2" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 00 · WELCOME &amp; SETUP</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">02</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">ÎNAINTE SĂ ÎNCEPEM</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <div style="margin-top:26px;">
  <p style="margin:0 0 0; font-stretch:92%; font-size:15px; line-height:1.7; color:var(--hb-3, #C6C6C6);">Pune MAIN, knob-ul de volum, cam la ora douăsprezece și lasă-l acolo: de aici încolo sunetul se schimbă din celelalte knob-uri, nu din volum.</p>
  <p style="margin:18px 0 0; font-stretch:92%; font-size:15px; line-height:1.7; color:var(--hb-3, #C6C6C6);">Punctul de plecare e Basic Program: un sawtooth simplu cu filtrul deschis și un vibrato deja pregătit pe mod wheel (îl folosim în modulul 05). Nu contează dacă sunetul tău nu iese identic cu rețeta, asta e partea bună a explorării. Dacă te pierzi, întoarce-te la Basic Program: ține apăsat TRANSPOSE DOWN și apasă PROGRAM. Un singur lucru de evitat: când pe ecran e numele unui program, rotirea lui SELECT încarcă alt program, iar sunetul construit de tine dispare. Rotește-l doar când ți-o cere un pas din exercițiu și când pe ecran apare un parametru, nu numele unui program.</p>
  <p style="margin:18px 0 0; font-stretch:92%; font-size:15px; line-height:1.7; color:var(--hb-3, #C6C6C6);">Manualul urmează workshopul oprire cu oprire. Fiecare modul are o pagină: ideea în câteva rânduri, diagrama de pe ecran și un ÎNCEARCĂ pe care îl poți face la synth. Cuvintele pe care le folosim sunt adunate în glosarul de la final. Citește un modul, învârte un buton, ascultă.</p>
  </div>
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">CE E ÎN BASIC PROGRAM</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Osc A pe sawtooth, ridicat la maximum în mixer; pe Osc B forma sawtooth e aprinsă și ea, dar nivelul lui din mixer stă pe zero, deci nu se aude nimic de la el până nu îl ridici. Filtrul deschis, fără rezonanță, KEY TRACK oprit; ambele anvelope simple, VELOCITY oprit; feedback și noise oprite; în MODULATION, LFO-ul e deja rutat la FREQ A și FREQ B pe bus-ul roții, deci ridici mod wheel-ul și ai vibrato; arpeggiatorul oprit. Același program umple toată banca User 2 și tot el revine cu TRANSPOSE DOWN + PROGRAM.</p></div><div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ȘASE PERECHI DE CUVINTE</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Când descrii un sunet, folosește-le pe astea înaintea oricărora: strălucitor / întunecat (cât înalt are) · subțire / gros (cât corp are) · gol / plin (a square sau a saw) · moale / dur (cum pornește) · pluck / pad (moare sau rămâne) · static / în mișcare (se schimbă ceva cât sună).</p><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Spune ce auzi, apoi caută knob-ul care îl mișcă: strălucirea stă la CUTOFF, corpul la sub și la detune, golul la forma de undă, pornirea la ATTACK, pluck-ul la DECAY și SUSTAIN, mișcarea la LFO.</p></div>
  <p style="margin:8px 0 0; font-style:italic; font-stretch:92%; font-size:11.5px; line-height:1.4; color:var(--hb-9, #9A9A9A);">Prophet-5 de la Sequential, în 1978, a fost primul sintetizator polifonic complet programabil: înainte de el, un patch trăia pe o foaie de hârtie și îl reconstruiai knob cu knob.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
