import type { DocPageDef } from '../../types';

// Ported from v02.1 Student Handbook (Screen source of truth; print theme
// via --hb-* vars, see handbook-theme.scss). EN+RO colocated.
export const PAGE_08: DocPageDef = {
  id: 'p8',
  label: 'Voices & unison',
  en: `<section class="page" id="p8" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 06 · VOICES &amp; UNISON</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">08</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">VOICES &amp; UNISON</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Four voices, one note, and the loop that thickens everything. Fourm is polyphonic: it holds four complete voices — each with its own oscillators, filter and envelopes — so four notes can sound at once. This module is about how those voices are spent: spread across a chord, stacked on one massive note, or replayed as a stored chord from a single key. And it adds mass from a different place: the feedback loop.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 558" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;">
<defs><linearGradient id="gg10_m04en" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0"></stop><stop offset="0.25" stop-color="#EDEDED" stop-opacity="0.5"></stop><stop offset="0.62" stop-color="#FF8A48" stop-opacity="0.8"></stop><stop offset="1" stop-color="#FF8A48" stop-opacity="0"></stop></linearGradient></defs>
<rect x="4" y="4" width="1858" height="550" rx="30" fill="rgba(255,255,255,0.02)" stroke="#454545" stroke-width="2.5"></rect>
<rect x="300" y="190" width="340" height="180" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="470" y="238" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">MIXER</text><path d="M652 280H710" stroke="#FF8A48" stroke-width="6" stroke-linecap="round"></path><path d="M734 280L706 266L706 294Z" fill="#FF8A48"></path><rect x="746" y="190" width="340" height="180" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="916" y="238" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">FILTER</text><path d="M1098 280H1156" stroke="#FF8A48" stroke-width="6" stroke-linecap="round"></path><path d="M1180 280L1152 266L1152 294Z" fill="#FF8A48"></path><rect x="1192" y="190" width="340" height="180" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="1362" y="238" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">OUT</text><path d="M1139 380V452H470V380" stroke="#FF8A48" stroke-width="4" stroke-dasharray="14 10" fill="none"></path><path d="M470 366L459 388L481 388Z" fill="#FF8A48"></path><text x="933" y="432" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#C6C6C6">SOFT-CLIPPING DIODES SATURATE THE LOOP</text><text x="933" y="514" text-anchor="middle" font-family="Lato, sans-serif" font-size="27" font-weight="700" letter-spacing="1" fill="#FF8A48">DEFAULT LEVEL 100 · HOLD FEEDBACK + TURN SELECT · THICKEN, DRIVE, CHAOS</text></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 6 · FEEDBACK: THE OUTPUT RETURNED INTO THE MIXER THROUGH SOFT CLIPPING.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">POLYPHONY</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Mono synths play one note at a time. Fourm plays four; press a fifth and the oldest note is stolen — faster than you expect once unison is on. HOLD sustains up to four held notes after your hands leave the keys.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">UNISON</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Unison stacks the voices you choose — one to four (hold UNISON and turn SELECT) — on a single note. Fourm becomes monophonic and, with all four, enormous. On its own that is just louder; the magic is detune (Param 10, Unison Detune, 0–127), which spreads the voices a few cents apart into one wide, beating tone. Small reads as analog richness, large as an obvious chorus. When it sounds huge, back it off ten percent: that is usually the keeper.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">CHORD MEMORY</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Hold a chord and store it; from then on any single key replays the whole voicing, transposed as you move — one finger, full harmony, great for chord stabs. It is saved with the program.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">FEEDBACK</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">A dedicated mixer channel returns Fourm&#x27;s output into the mix, with soft-clipping diodes in the loop. Press FEEDBACK (it comes in at level 100), hold it and turn SELECT to set the amount. Low amounts warm and thicken; high amounts growl and overdrive, all inside the voice. Unison plus feedback is Fourm&#x27;s biggest bass.</p></div></div>
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Chord memory, step by step: press UNISON; push SELECT to move to the middle row and scroll to Chord; press UNISON to move to the top row; play and hold a chord of two to four notes; press UNISON again — Chord Mode is on. To clear it: hold UNISON, set the voice count with SELECT, press UNISON off, save. Vintage (Param 11) adds voice-to-voice drift without unison, like an old synth on a warm night.</p></div>
  <p style="margin:12px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRY IT</span> &nbsp;Play five notes at once and count what you hear. Hold UNISON, turn SELECT to 4 voices and play a line: one huge note. Press PARAM, scroll to 10 Unison Detune, press SELECT and turn it to about 40, press PROGRAM to exit — the tone widens. Press FEEDBACK, hold it and turn SELECT down to about 60: growl without chaos. Turn unison off, play a chord, press HOLD and lift your hands.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p8" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 06 · VOICES &amp; UNISON</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">08</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">VOICES &amp; UNISON</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Patru voci, o notă și bucla care îngroașă tot. Fourm e polifonic: ține patru voci complete — fiecare cu oscilatoarele, filtrul și anvelopele ei — deci pot suna patru note deodată. Modulul ăsta e despre cum se cheltuiesc vocile: întinse pe un acord, stivuite pe o singură notă uriașă sau recântate ca un acord memorat, dintr-o singură clapă. Și adaugă masă dintr-un alt loc: bucla de feedback.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 558" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;">
<defs><linearGradient id="gg11_m04ro" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0"></stop><stop offset="0.25" stop-color="#EDEDED" stop-opacity="0.5"></stop><stop offset="0.62" stop-color="#FF8A48" stop-opacity="0.8"></stop><stop offset="1" stop-color="#FF8A48" stop-opacity="0"></stop></linearGradient></defs>
<rect x="4" y="4" width="1858" height="550" rx="30" fill="rgba(255,255,255,0.02)" stroke="#454545" stroke-width="2.5"></rect>
<rect x="300" y="190" width="340" height="180" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="470" y="238" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">MIXER</text><path d="M652 280H710" stroke="#FF8A48" stroke-width="6" stroke-linecap="round"></path><path d="M734 280L706 266L706 294Z" fill="#FF8A48"></path><rect x="746" y="190" width="340" height="180" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="916" y="238" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">FILTER</text><path d="M1098 280H1156" stroke="#FF8A48" stroke-width="6" stroke-linecap="round"></path><path d="M1180 280L1152 266L1152 294Z" fill="#FF8A48"></path><rect x="1192" y="190" width="340" height="180" rx="14" fill="none" stroke="#C9C9C9" stroke-width="2.5"></rect><text x="1362" y="238" text-anchor="middle" font-family="Lato, sans-serif" font-size="33" letter-spacing="3" fill="#DBDBDB">OUT</text><path d="M1139 380V452H470V380" stroke="#FF8A48" stroke-width="4" stroke-dasharray="14 10" fill="none"></path><path d="M470 366L459 388L481 388Z" fill="#FF8A48"></path><text x="933" y="432" text-anchor="middle" font-family="Lato, sans-serif" font-size="24" letter-spacing="2" fill="#C6C6C6">DIODELE SOFT-CLIPPING SATUREAZĂ BUCLA</text><text x="933" y="514" text-anchor="middle" font-family="Lato, sans-serif" font-size="27" font-weight="700" letter-spacing="1" fill="#FF8A48">NIVEL IMPLICIT 100 · ȚINE FEEDBACK + ROTEȘTE SELECT · ÎNGROAȘĂ, SATUREAZĂ, HAOS</text></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 6 · FEEDBACK: IEȘIREA, ÎNTOARSĂ ÎN MIXER PRIN SOFT CLIPPING.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">POLIFONIE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Synth-urile mono cântă o notă odată. Fourm cântă patru; apeși a cincea și cea mai veche notă e furată — mai repede decât te aștepți, odată ce unison-ul e pornit. HOLD susține până la patru note ținute, după ce mâinile pleacă de pe clape.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">UNISON</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Unison stivuiește vocile alese — de la una la patru (ține UNISON și rotește SELECT) — pe o singură notă. Fourm devine monofonic și, cu toate patru, enorm. Singur, e doar mai tare; magia e detune (Param 10, Unison Detune, 0–127), care împrăștie vocile la câțiva cenți distanță într-un ton lat, care pulsează. Puțin se citește ca bogăție analogică, mult ca un chorus evident. Când sună uriaș, dă-l înapoi cu zece la sută: de obicei aia e varianta bună.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">CHORD MEMORY</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Ține un acord și memorează-l; de atunci, orice clapă redă întregul voicing, transpus pe măsură ce te muți — un deget, armonie completă, excelent pentru chord stabs. Se salvează cu programul.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">FEEDBACK</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Un canal dedicat din mixer întoarce ieșirea lui Fourm în mix, cu diode de soft-clipping în buclă. Apeși FEEDBACK (intră la nivelul 100), îl ții apăsat și rotești SELECT pentru cantitate. Puțin încălzește și îngroașă; mult mârâie și distorsionează, totul în interiorul vocii. Unison plus feedback e cel mai mare bass pe care îl scoate Fourm.</p></div></div>
  <div style="margin-top:12px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Chord memory, pas cu pas: apasă UNISON; apasă SELECT ca să treci pe rândul din mijloc și derulează la Chord; apasă UNISON ca să ajungi pe rândul de sus; cântă și ține un acord de două-patru note; apasă UNISON din nou — Chord Mode e pornit. Ca să-l ștergi: ține UNISON, setează numărul de voci cu SELECT, apasă UNISON off, salvează. Vintage (Param 11) adaugă drift între voci fără unison, ca un synth vechi într-o seară caldă.</p></div>
  <p style="margin:12px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ÎNCEARCĂ</span> &nbsp;Cântă cinci note deodată și numără ce auzi. Ține UNISON, rotește SELECT la 4 voci și cântă o linie: o singură notă uriașă. Apasă PARAM, derulează la 10 Unison Detune, apasă SELECT și rotește pe la 40, apasă PROGRAM ca să ieși — tonul se lățește. Apasă FEEDBACK, ține-l apăsat și rotește SELECT în jos până pe la 60: mârâit fără haos. Scoate unison-ul, cântă un acord, apasă HOLD și ridică mâinile.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
