import type { DocPageDef } from '../../types';

// Ported from v02.1 Student Handbook (Screen source of truth; print theme
// via --hb-* vars, see handbook-theme.scss). EN+RO colocated.
export const PAGE_20: DocPageDef = {
  id: 'p20',
  label: 'Take it home',
  en: `<section class="page" id="p20" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 09 · WRAP-UP</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">20</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">TAKE IT HOME</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:16px 0 0; font-stretch:92%; font-size:14px; line-height:1.65; color:var(--hb-3, #C6C6C6);">That is the whole course. Keep this handbook next to the synth: read one module, turn one knob, listen. The order on the panel is the order in your head now — and every synthesizer you meet from here on is the same road with different clothes.</p><p style="margin:14px 0 0; font-stretch:92%; font-size:14px; line-height:1.65; color:var(--hb-3, #C6C6C6);">When you build a sound you like, write it down: the waveshapes, the octaves, the filter, the four knobs of each envelope, what the LFO moves. A patch on paper survives; a patch in memory rarely does.</p>
  <div style="margin-top:14px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">A PUZZLE</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">“My bass sound is too buzzy, and it fades in slowly. What should I do?” Work it out before you read on: the buzz is harmonics, so that is the filter (module 03); the slow fade-in is time, so that is an envelope (module 04).</p><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-2, #8F8F8F);">Answer: amp ATTACK to zero, then CUTOFF down until the buzz is gone.</p></div>
  <div style="margin-top:18px;"><div style="display:flex; align-items:center; gap:16px; margin-top:12px;"><img src="/course/qr-telegram.svg" alt="QR code for the Sintezaur Telegram group" style="flex:none; width:88px; height:88px; display:block; background:#FFFFFF; border-radius:8px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SINTEZAUR · TELEGRAM</p><p style="margin:3px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);">the community, the gear talk, and where to say hello</p></div></div><div style="display:flex; align-items:center; gap:16px; margin-top:12px;"><img src="/course/qr-instagram.svg" alt="QR code for the Sintezaur Instagram page" style="flex:none; width:88px; height:88px; display:block; background:#FFFFFF; border-radius:8px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SINTEZAUR · INSTAGRAM</p><p style="margin:3px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);">what we are building next, in pictures</p></div></div><div style="display:flex; align-items:center; gap:16px; margin-top:12px;"><img src="/course/qr-fourm.svg" alt="QR code for the Sequential Fourm page" style="flex:none; width:88px; height:88px; display:block; background:#FFFFFF; border-radius:8px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SEQUENTIAL · FOURM</p><p style="margin:3px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);">the user guide, the preset list and the full specs</p></div></div><div style="margin-top:16px; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px;"><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ZEEDO</span>&nbsp;&nbsp;where to try and buy the Fourm: <span style="color:var(--hb-4, #E8E8E8);">zeedoshop.ro</span></p><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SEQUENTIAL</span>&nbsp;&nbsp;the instruments that made tonight possible: <span style="color:var(--hb-4, #E8E8E8);">sequential.com</span></p></div></div>
  <p style="margin:18px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-size:26px; color:var(--hb-4, #E8E8E8);">Thank you for playing.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p20" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 09 · WRAP-UP</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">20</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">IA-L ACASĂ</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:16px 0 0; font-stretch:92%; font-size:14px; line-height:1.65; color:var(--hb-3, #C6C6C6);">Ăsta e tot cursul. Ține manualul lângă synth: citește un modul, învârte un buton, ascultă. Ordinea de pe panou e acum ordinea din capul tău — iar orice sintetizator pe care îl întâlnești de aici încolo e același traseu, cu alte haine.</p><p style="margin:14px 0 0; font-stretch:92%; font-size:14px; line-height:1.65; color:var(--hb-3, #C6C6C6);">Când construiești un sunet care îți place, notează-l: formele de undă, octavele, filtrul, cele patru knob-uri ale fiecărei anvelope, ce mișcă LFO-ul. Un patch pe hârtie supraviețuiește; unul în memorie, rar.</p>
  <div style="margin-top:14px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">O GHICITOARE</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">„Bass-ul meu e prea bâzâitor și intră încet. Ce fac?" Gândește-te înainte să citești mai departe: bâzâitul înseamnă armonice, deci e filtrul (modulul 03); intrarea lentă înseamnă timp, deci e o anvelopă (modulul 04).</p><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-2, #8F8F8F);">Răspuns: ATTACK-ul de amp la zero, apoi CUTOFF în jos până dispare bâzâitul.</p></div>
  <div style="margin-top:18px;"><div style="display:flex; align-items:center; gap:16px; margin-top:12px;"><img src="/course/qr-telegram.svg" alt="Cod QR pentru grupul de Telegram Sintezaur" style="flex:none; width:88px; height:88px; display:block; background:#FFFFFF; border-radius:8px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SINTEZAUR · TELEGRAM</p><p style="margin:3px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);">comunitatea, vorba despre aparate și unde ne dai un semn</p></div></div><div style="display:flex; align-items:center; gap:16px; margin-top:12px;"><img src="/course/qr-instagram.svg" alt="Cod QR pentru pagina de Instagram Sintezaur" style="flex:none; width:88px; height:88px; display:block; background:#FFFFFF; border-radius:8px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SINTEZAUR · INSTAGRAM</p><p style="margin:3px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);">ce construim mai departe, în imagini</p></div></div><div style="display:flex; align-items:center; gap:16px; margin-top:12px;"><img src="/course/qr-fourm.svg" alt="Cod QR pentru pagina Fourm de la Sequential" style="flex:none; width:88px; height:88px; display:block; background:#FFFFFF; border-radius:8px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SEQUENTIAL · FOURM</p><p style="margin:3px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);">manualul, lista de presete și specificațiile complete</p></div></div><div style="margin-top:16px; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px;"><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ZEEDO</span>&nbsp;&nbsp;unde încerci și cumperi Fourm: <span style="color:var(--hb-4, #E8E8E8);">zeedoshop.ro</span></p><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.45; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SEQUENTIAL</span>&nbsp;&nbsp;instrumentele care au făcut seara asta posibilă: <span style="color:var(--hb-4, #E8E8E8);">sequential.com</span></p></div></div>
  <p style="margin:18px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-size:26px; color:var(--hb-4, #E8E8E8);">Mulțumim că ai cântat.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
