import type { DocPageDef } from '../../types';

// Ported from v02.1 Student Handbook (Screen source of truth; print theme
// via --hb-* vars, see handbook-theme.scss). EN+RO colocated.
export const PAGE_05: DocPageDef = {
  id: 'p5',
  en: `<section class="page" id="p5" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULE 03 · FILTER</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">05</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">FILTER</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Shaping your tone. The oscillators give you a block of harmonics; the filter is the chisel. Fourm&#x27;s low-pass filter lets everything below a chosen frequency through and fades everything above it — close it and the sound darkens, open it and it brightens. It is the most important knob on any synthesizer, and the one you will touch most tonight.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 600" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;"><g><path d="M140 520H1780" stroke="#8F8F8F" stroke-width="4"></path><path d="M140 520V60" stroke="#8F8F8F" stroke-width="4"></path><path d="M1000 90V520" stroke="#FF8A48" stroke-width="5" stroke-dasharray="16 12"></path><path d="M140 300L820 300C900 300.5 950 312 1000 372C1060 448 1160 500 1300 516" stroke="#FF8A48" stroke-width="7" fill="none" stroke-linecap="round" opacity="0.5" stroke-dasharray="20 14"></path><path d="M140 300L800 300C880 299 930 274 970 200C985 172 995 146 1000 132L1004 148C1012 196 1022 260 1044 320C1090 440 1210 492 1360 512" stroke="#FF8A48" stroke-width="9" fill="none" stroke-linecap="round"></path><text x="978" y="496" text-anchor="end" font-family="Lato, sans-serif" font-weight="700" font-size="36" fill="#FF8A48">CUTOFF</text><text x="1044" y="150" font-family="Lato, sans-serif" font-weight="700" font-size="36" fill="#FF8A48">RESONANCE (Q)</text><text x="144" y="574" font-family="Lato, sans-serif" font-size="28" letter-spacing="4" fill="#A7A7A7">LOW</text><text x="1780" y="574" text-anchor="end" font-family="Lato, sans-serif" font-size="28" letter-spacing="4" fill="#A7A7A7">HIGH</text><text transform="rotate(-90 84 290)" x="84" y="290" text-anchor="middle" font-family="Lato, sans-serif" font-size="28" letter-spacing="5" fill="#A7A7A7">GAIN</text></g></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 3 · A LOW-PASS FILTER WITHOUT AND WITH RESONANCE: THE CUTOFF, AND THE PEAK THAT SINGS.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">CUTOFF</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">The hinge frequency. Below it the harmonics pass; above it they fall away, on Fourm with a steep four-pole slope. Fully open, you hear the raw wave; fully closed, you hear nothing at all — the first thing to check when a patch goes silent.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">RESONANCE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">A boost of the narrow band right at the cutoff. A little adds focus and vowel-like character to a sweep; a lot makes the filter whistle along with the note. Unlike many classic filters, Fourm keeps the low end full as resonance rises.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SELF-OSCILLATION</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">At maximum resonance the filter feeds on itself and produces a pure sine of its own, with no oscillator needed: a fifth sound source. Turn the volume down a touch before you go there — it arrives suddenly and loud.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">KEY TRACK &amp; ENV AMOUNT</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">KEY TRACK makes the cutoff follow the keyboard (quarter, half or full — hold the button and turn SELECT): higher notes get a brighter filter, as acoustic instruments do; with full tracking, a singing filter plays a scale in tune. ENV AMT sets how much the filter envelope moves the cutoff over the life of a note — positive or negative, with zero at 12 o&#x27;clock. That is the story of the next module.</p></div></div>
  <div style="margin-top:14px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Fourm&#x27;s filter is a four-pole resonant low-pass in the Prophet-5 lineage. Its bass compensation is always on, so resonance never thins the fundamental the way vintage ladder filters do.</p></div>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">TRY IT</span> &nbsp;Hold a chord. Turn CUTOFF slowly down until the sound is dark, then back up. Set RESONANCE to about 3 o&#x27;clock and sweep CUTOFF again: a whistle rides the sweep. Lower MAIN a touch, turn RESONANCE to maximum, close CUTOFF a little and play single notes: the filter sings on its own. Hold KEY TRACK, turn SELECT to Full, and hear the high notes brighten. Bring RESONANCE back to 9 o&#x27;clock and CUTOFF to 12 o&#x27;clock — we keep this for the next module.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · STUDENT HANDBOOK</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
  ro: `<section class="page" id="p5" style="background:var(--hb-6, #000000); box-sizing:border-box; padding:52px 64px 44px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; display:flex; flex-direction:column;">
  <div style="display:flex; justify-content:space-between; align-items:baseline;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:var(--hb-5, #FF8A48);">MODULUL 03 · FILTER</p>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:2px; color:var(--hb-2, #8F8F8F);">05</p>
  </div>
  <h1 style="margin:26px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:42px; line-height:1.05; color:var(--hb-4, #E8E8E8);">FILTER</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6; color:var(--hb-3, #C6C6C6);">Sculptezi timbrul. Oscilatoarele îți dau blocul de armonice; filtrul e dalta. Filtrul low-pass al lui Fourm lasă să treacă tot ce e sub o frecvență aleasă și stinge tot ce e deasupra — îl închizi și sunetul se întunecă, îl deschizi și se luminează. E cel mai important knob de pe orice sintetizator și cel pe care îl vei atinge cel mai des în seara asta.</p>
  <div style="margin-top:14px; background:var(--hb-1, #0A0A0A); border:1px solid #2A2A2A; border-radius:14px; padding:12px 16px;"><svg viewBox="0 0 1866 600" width="100%" preserveAspectRatio="xMidYMid meet" style="display:block;"><g><path d="M140 520H1780" stroke="#8F8F8F" stroke-width="4"></path><path d="M140 520V60" stroke="#8F8F8F" stroke-width="4"></path><path d="M1000 90V520" stroke="#FF8A48" stroke-width="5" stroke-dasharray="16 12"></path><path d="M140 300L820 300C900 300.5 950 312 1000 372C1060 448 1160 500 1300 516" stroke="#FF8A48" stroke-width="7" fill="none" stroke-linecap="round" opacity="0.5" stroke-dasharray="20 14"></path><path d="M140 300L800 300C880 299 930 274 970 200C985 172 995 146 1000 132L1004 148C1012 196 1022 260 1044 320C1090 440 1210 492 1360 512" stroke="#FF8A48" stroke-width="9" fill="none" stroke-linecap="round"></path><text x="978" y="496" text-anchor="end" font-family="Lato, sans-serif" font-weight="700" font-size="36" fill="#FF8A48">CUTOFF</text><text x="1044" y="150" font-family="Lato, sans-serif" font-weight="700" font-size="36" fill="#FF8A48">RESONANCE (Q)</text><text x="144" y="574" font-family="Lato, sans-serif" font-size="28" letter-spacing="4" fill="#A7A7A7">LOW</text><text x="1780" y="574" text-anchor="end" font-family="Lato, sans-serif" font-size="28" letter-spacing="4" fill="#A7A7A7">HIGH</text><text transform="rotate(-90 84 290)" x="84" y="290" text-anchor="middle" font-family="Lato, sans-serif" font-size="28" letter-spacing="5" fill="#A7A7A7">GAIN</text></g></svg></div>
  <p style="margin:7px 0 0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:1.5px; color:var(--hb-2, #8F8F8F);">FIG. 3 · UN FILTRU LOW-PASS FĂRĂ ȘI CU REZONANȚĂ: CUTOFF-UL ȘI VÂRFUL CARE CÂNTĂ.</p>
  <div style="margin-top:14px; display:grid; grid-template-columns:1fr 1fr; column-gap:30px; row-gap:14px;"><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">CUTOFF</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Frecvența-balama. Sub ea armonicele trec; deasupra se sting, pe Fourm cu o pantă abruptă, de patru poli. Complet deschis, auzi unda brută; complet închis, nu auzi nimic — primul lucru de verificat când un patch amuțește.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">RESONANCE</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">Un accent al benzii înguste chiar de la cutoff. Puțină adaugă focus și un caracter de vocală când miști cutoff-ul; multă face filtrul să fluiere pe lângă notă. Spre deosebire de multe filtre clasice, Fourm păstrează josul plin pe măsură ce rezonanța crește.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">SELF-OSCILLATION</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">La rezonanță maximă filtrul se hrănește din el însuși și produce un sinus pur, fără niciun oscilator: a cincea sursă de sunet. Coboară puțin volumul înainte să ajungi acolo — vine brusc și tare.</p></div><div><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:12.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">KEY TRACK &amp; ENV AMOUNT</h2><p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);">KEY TRACK face cutoff-ul să urmeze claviatura (quarter, half sau full — ține butonul apăsat și rotește SELECT): notele de sus primesc un filtru mai deschis, cum fac instrumentele acustice; cu tracking full, un filtru care cântă singur cântă o gamă acordată. ENV AMT stabilește cât de mult mișcă anvelopa de filtru cutoff-ul pe durata notei — pozitiv sau negativ, cu zero la ora douăsprezece. Asta e povestea modulului următor.</p></div></div>
  <div style="margin-top:14px; border-left:3px solid var(--hb-8, #2A2A2A); padding-left:14px;"><h2 style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-2, #8F8F8F);">LEVEL 2</h2><p style="margin:5px 0 0; font-stretch:92%; font-size:12px; line-height:1.5; color:var(--hb-9, #9A9A9A);">Filtrul lui Fourm e un low-pass rezonant de patru poli, din descendența Prophet-5. Bass compensation e mereu activă, deci rezonanța nu subțiază niciodată fundamentala așa cum o fac filtrele ladder vintage.</p></div>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.5; color:var(--hb-3, #C6C6C6);"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:11.5px; letter-spacing:2.5px; color:var(--hb-5, #FF8A48);">ÎNCEARCĂ</span> &nbsp;Ține un acord. Rotește CUTOFF încet în jos până când sunetul e întunecat, apoi înapoi în sus. Pune RESONANCE pe la ora trei și mai fă un sweep de CUTOFF: un fluierat călărește sweep-ul. Coboară puțin MAIN, dă RESONANCE la maximum, închide un pic CUTOFF și cântă note simple: filtrul cântă singur. Ține KEY TRACK, rotește SELECT la Full și ascultă cum se luminează notele de sus. Adu RESONANCE înapoi la ora nouă și CUTOFF la ora douăsprezece — păstrăm asta pentru modulul următor.</p>
  <div style="margin-top:auto; border-top:1px solid var(--hb-8, #2A2A2A); padding-top:10px; display:flex; justify-content:space-between; align-items:center;">
    <div style="display:flex; align-items:center; gap:10px;"><img class="hb-only-dark" src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="height:20px; width:auto;"><img class="hb-only-light" src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:20px; width:auto;"><p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:#8F8F8F;">SINTEZAUR · MANUALUL CURSANTULUI</p></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:10px; letter-spacing:2px; color:var(--hb-7, #8F8F8F);">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  </div>
</section>`,
};
