import type { SlideDef } from '../../types';

// Ported 1:1 from v02.1 "Full Course.dc.html" (00·02 EN Today / 00·02 RO Today).
// EN and RO layouts are colocated; deleting this page = delete this file +
// its line in index.ts.
export const SLIDE_S00_02_TODAY: SlideDef = {
  id: '00·02',
  module: '00',
  label: "Today",
  en: `<section data-label="00·02 EN Today" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">TODAY</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">Club Control, Bucharest</p>
  <div style="position:absolute; left:27px; top:428px; width:1866px; height:480px; box-sizing:border-box; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); display:grid; grid-template-columns:1fr 1fr 1fr; align-items:center; padding:0 40px;"><div style="text-align:center; padding:0 30px;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:40px; letter-spacing:3px; color:#FF8A48;">SINTEZAUR</p><p style="margin:22px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:32px; line-height:1.4; color:#E8E8E8;">Bucharest's community for people who love synthesis. Your guide today: Iulian.</p></div><div style="text-align:center; padding:0 30px;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:40px; letter-spacing:3px; color:#FF8A48;">ZEEDO</p><p style="margin:22px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:32px; line-height:1.4; color:#E8E8E8;">Our retail partner, and the reason there are a dozen synths in this room.</p></div><div style="text-align:center; padding:0 30px;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:40px; letter-spacing:3px; color:#FF8A48;">SEQUENTIAL FOURM</p><p style="margin:22px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:32px; line-height:1.4; color:#E8E8E8;">Today's instrument: a 4-voice analog synth that feels pressure in every key.</p></div></div>
  <p style="position:absolute; left:0; width:1920px; top:938px; margin:0; text-align:center; font-family:'Lato',sans-serif; font-size:24px; letter-spacing:5px; color:#A7A7A7;">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULE 00 · WELCOME &amp; SETUP</p>
</section>`,
  ro: `<section data-label="00·02 RO Today" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">TODAY</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">Club Control, București</p>
  <div style="position:absolute; left:27px; top:428px; width:1866px; height:480px; box-sizing:border-box; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); display:grid; grid-template-columns:1fr 1fr 1fr; align-items:center; padding:0 40px;"><div style="text-align:center; padding:0 30px;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:40px; letter-spacing:3px; color:#FF8A48;">SINTEZAUR</p><p style="margin:22px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:32px; line-height:1.4; color:#E8E8E8;">Comunitatea din București pentru oamenii care iubesc sinteza. Ghidul vostru azi: Iulian.</p></div><div style="text-align:center; padding:0 30px;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:40px; letter-spacing:3px; color:#FF8A48;">ZEEDO</p><p style="margin:22px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:32px; line-height:1.4; color:#E8E8E8;">Partenerul nostru de retail, și motivul pentru care sunt o duzină de synth-uri în sală.</p></div><div style="text-align:center; padding:0 30px;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:40px; letter-spacing:3px; color:#FF8A48;">SEQUENTIAL FOURM</p><p style="margin:22px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:32px; line-height:1.4; color:#E8E8E8;">Instrumentul de azi: un synth analogic cu 4 voci, care simte presiunea în fiecare clapă.</p></div></div>
  <p style="position:absolute; left:0; width:1920px; top:938px; margin:0; text-align:center; font-family:'Lato',sans-serif; font-size:24px; letter-spacing:5px; color:#A7A7A7;">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULUL 00 · WELCOME &amp; SETUP</p>
</section>`,
};
