import type { SlideDef } from '../../types';

// Ported 1:1 from v02.1 "Full Course.dc.html" (02·07 EN Terms / 02·07 RO Termeni).
// EN and RO layouts are colocated; deleting this page = delete this file +
// its line in index.ts.
export const SLIDE_S02_07_TERMS: SlideDef = {
  id: '02·07',
  module: '02',
  label: "Terms",
  en: `<section data-label="02·07 EN Terms" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <a data-go="hub" style="cursor:pointer; position:absolute; right:48px; top:1028px; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F; text-decoration:none;" class="ws-hover-accent">← COURSE MAP</a>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULE 02 · OSCILLATORS</p>
  <div style="position:absolute; left:27px; top:428px; width:1866px; height:558px; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); box-sizing:border-box; padding:58px 70px 0;">
    <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:70px; row-gap:22px; margin-top:10px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">WAVESHAPE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">The geometric shape of one cycle: it sets the raw timbre.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">PULSE WIDTH (PW)</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Duty cycle of the pulse wave, -100% to +100%. 0 = square.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">PWM</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Pulse width modulation: moving PW with the LFO or an envelope.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">SYNC</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Locks Oscillator A’s cycle to Oscillator B for aggressive timbres.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">LO1 / LO2</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Osc B’s low modes: LFO-range pitch, key-tracked (LO1) or free (LO2).</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">HARMONICS</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Saw has them all; square and triangle only the odd ones — the triangle&#x27;s fade much faster.</p></div></div>
  </div><h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">KEY TERMS</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">New words from this module</p>
</section>`,
  ro: `<section data-label="02·07 RO Termeni" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <a data-go="hub" style="cursor:pointer; position:absolute; right:48px; top:1028px; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F; text-decoration:none;" class="ws-hover-accent">← CUPRINS</a>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULUL 02 · OSCILLATORS</p>
  <div style="position:absolute; left:27px; top:428px; width:1866px; height:558px; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); box-sizing:border-box; padding:58px 70px 0;">
    <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:70px; row-gap:22px; margin-top:10px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">WAVESHAPE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Forma geometrică a unui ciclu: dă timbrul brut.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">PULSE WIDTH (PW)</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Duty cycle-ul undei pulse, de la -100% la +100%. 0 = square.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">PWM</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Pulse width modulation: mișcarea PW cu LFO sau cu o anvelopă.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">SYNC</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Blochează ciclul Oscilatorului A de Oscilatorul B, pentru timbruri agresive.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">LO1 / LO2</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Modurile joase ale lui Osc B: pitch în zona LFO, urmând claviatura (LO1) sau liber (LO2).</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">HARMONICS</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Saw le are pe toate; square și triangle doar pe cele impare — la triangle scad mult mai repede.</p></div></div>
  </div><h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">TERMENI-CHEIE</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">Cuvintele noi din acest modul</p>
</section>`,
};
