import type { SlideDef } from '../../types';

// Ported 1:1 from v02.1 "Full Course.dc.html" (06·06 EN Terms / 06·06 RO Termeni).
// EN and RO layouts are colocated; deleting this page = delete this file +
// its line in index.ts.
export const SLIDE_S06_06_TERMS: SlideDef = {
  id: '06·06',
  module: '06',
  label: "Terms",
  en: `<section data-label="06·06 EN Terms" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <a data-go="hub" style="cursor:pointer; position:absolute; right:48px; top:1028px; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F; text-decoration:none;" class="ws-hover-accent">← COURSE MAP</a>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULE 06 · VOICES &amp; UNISON</p>
  <div style="position:absolute; left:27px; top:428px; width:1866px; height:558px; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); box-sizing:border-box; padding:58px 70px 0;">
    <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:70px; row-gap:22px; margin-top:10px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">UNISON</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">All chosen voices play the same note. Monophonic, massive.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">UNISON DETUNE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">0–127 of drift between stacked voices: the chorused fat.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">CHORD MEMORY</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Unison stores a chord; single keys replay it transposed.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">HOLD</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Sustains up to four notes after your hands leave the keys; also latches the arpeggiator.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">FEEDBACK</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">The output fed back into the mixer, soft-clipped.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">SOFT-CLIPPING</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Gentle rounding of peaks: saturation instead of harsh distortion.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">POLYPHONY · VOICE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Four complete voices; the fifth note steals the oldest.</p></div></div>
  </div><h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">KEY TERMS</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">New words from this module</p>
</section>`,
  ro: `<section data-label="06·06 RO Termeni" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <a data-go="hub" style="cursor:pointer; position:absolute; right:48px; top:1028px; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F; text-decoration:none;" class="ws-hover-accent">← CUPRINS</a>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULUL 06 · VOICES &amp; UNISON</p>
  <div style="position:absolute; left:27px; top:428px; width:1866px; height:558px; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); box-sizing:border-box; padding:58px 70px 0;">
    <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:70px; row-gap:22px; margin-top:10px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">UNISON</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Toate vocile alese cântă aceeași notă. Monofonic, masiv.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">UNISON DETUNE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">0–127 de alunecare între vocile stivuite: grăsimea de chorus.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">CHORD MEMORY</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Unison memorează un acord; clapele simple îl recântă transpus.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">HOLD</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Ține până la patru note după ce ridici mâinile de pe clape; ține și arpeggiator-ul în mers.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">FEEDBACK</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Ieșirea, întoarsă în mixer, cu soft clipping.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">SOFT-CLIPPING</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Rotunjire blândă a vârfurilor: saturație în loc de distorsiune dură.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">POLYPHONY · VOICE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Patru voci complete; a cincea notă o fură pe cea mai veche.</p></div></div>
  </div><h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">TERMENI-CHEIE</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">Cuvintele noi din acest modul</p>
</section>`,
};
