import type { SlideDef } from '../../types';

// Ported 1:1 from v02.1 "Full Course.dc.html" (08·05 EN Terms / 08·05 RO Termeni).
// EN and RO layouts are colocated; deleting this page = delete this file +
// its line in index.ts.
export const SLIDE_S08_05_TERMS: SlideDef = {
  id: '08·05',
  module: '08',
  label: "Terms",
  en: `<section data-label="08·05 EN Terms" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <a data-go="hub" style="cursor:pointer; position:absolute; right:48px; top:1028px; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F; text-decoration:none;" class="ws-hover-accent">← COURSE MAP</a>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULE 08 · ARPEGGIATOR &amp; SEQUENCER</p>
  <div style="position:absolute; left:27px; top:428px; width:1866px; height:558px; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); box-sizing:border-box; padding:58px 70px 0;">
    <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:70px; row-gap:22px; margin-top:10px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">ARPEGGIATOR</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Plays a pattern from the notes of a held chord.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">HOLD / LATCH</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Keeps the arpeggio running after you release the keys.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">RELATCH</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Each new chord starts a fresh arpeggio instead of adding notes.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">BPM / TAP TEMPO</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">The clock speed: dialed in or tapped in.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">CLOCK DIVISION</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Note value per step: quarters, eighths, sixteenths…</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">REST · TIE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">A silent step · a step that extends the previous note.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">MOD SEQUENCE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Steps that move a parameter instead of playing notes.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">SEQ REVIEW</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Global setting for stepping through and editing a sequence.</p></div></div>
  </div><h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">KEY TERMS</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">New words from this module</p>
</section>`,
  ro: `<section data-label="08·05 RO Termeni" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <a data-go="hub" style="cursor:pointer; position:absolute; right:48px; top:1028px; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F; text-decoration:none;" class="ws-hover-accent">← CUPRINS</a>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULUL 08 · ARPEGGIATOR &amp; SEQUENCER</p>
  <div style="position:absolute; left:27px; top:428px; width:1866px; height:558px; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); box-sizing:border-box; padding:58px 70px 0;">
    <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:70px; row-gap:22px; margin-top:10px;"><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">ARPEGGIATOR</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Cântă un tipar din notele unui acord ținut.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">HOLD / LATCH</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Ține arpegiul în mers după ce ai eliberat clapele.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">RELATCH</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Fiecare acord nou pornește un arpegiu proaspăt, în loc să adauge note.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">BPM / TAP TEMPO</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Viteza clock-ului: setată din knob sau bătută din buton.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">CLOCK DIVISION</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Valoarea de notă per pas: pătrimi, optimi, șaisprezecimi…</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">REST · TIE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Un pas de tăcere · un pas care prelungește nota anterioară.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">MOD SEQUENCE</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Pași care mișcă un parametru în loc să cânte note.</p></div><div><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:30px; letter-spacing:2px; color:#FF8A48;">SEQ REVIEW</p><p style="margin:4px 0 0; font-family:'Lato',sans-serif; font-size:26px; line-height:1.3; color:#C6C6C6;">Setare globală pentru parcurgerea și editarea unei secvențe pas cu pas.</p></div></div>
  </div><h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">TERMENI-CHEIE</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">Cuvintele noi din acest modul</p>
</section>`,
};
