import type { SlideDef } from '../../types';

// Ported 1:1 from v02.1 "Full Course.dc.html" (09·02 EN Thank You / 09·02 RO Thank You).
// EN and RO layouts are colocated; deleting this page = delete this file +
// its line in index.ts.
export const SLIDE_S09_02_THANK_YOU: SlideDef = {
  id: '09·02',
  module: '09',
  label: "Thank You",
  en: `<section data-label="09·02 EN Thank You" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">THANK YOU</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">Take the handbook home — EN or RO</p>
  <div style="position:absolute; left:27px; top:400px; width:1866px; height:470px; box-sizing:border-box; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); display:grid; grid-template-columns:1fr 1fr 1fr; align-items:center; padding:0 60px;"><div style="text-align:center;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:38px; letter-spacing:3px; color:#FF8A48;">SINTEZAUR</p><p style="margin:14px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:30px; line-height:1.3; color:#E8E8E8;">community &amp; next workshop</p><div style="margin:20px auto 0; width:120px; height:120px; border:2.5px solid #454545; border-radius:14px; display:flex; align-items:center; justify-content:center;"><span style="font-family:'Lato',sans-serif; font-size:24px; letter-spacing:2px; color:#6E6E6E;">QR</span></div></div><div style="text-align:center;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:38px; letter-spacing:3px; color:#FF8A48;">ZEEDO</p><p style="margin:14px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:30px; line-height:1.3; color:#E8E8E8;">try and buy the Fourm</p><div style="margin:20px auto 0; width:120px; height:120px; border:2.5px solid #454545; border-radius:14px; display:flex; align-items:center; justify-content:center;"><span style="font-family:'Lato',sans-serif; font-size:24px; letter-spacing:2px; color:#6E6E6E;">QR</span></div></div><div style="text-align:center;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:38px; letter-spacing:3px; color:#FF8A48;">SEQUENTIAL</p><p style="margin:14px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:30px; line-height:1.3; color:#E8E8E8;">user guide &amp; presets</p><div style="margin:20px auto 0; width:120px; height:120px; border:2.5px solid #454545; border-radius:14px; display:flex; align-items:center; justify-content:center;"><span style="font-family:'Lato',sans-serif; font-size:24px; letter-spacing:2px; color:#6E6E6E;">QR</span></div></div></div>
  <p style="position:absolute; left:0; width:1920px; top:920px; margin:0; text-align:center; font-family:'Lato',sans-serif; font-size:26px; letter-spacing:5px; color:#A7A7A7;">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULE 09 · WRAP-UP</p>
  <a data-go="hub" style="cursor:pointer; position:absolute; right:48px; top:1028px; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">← COURSE MAP</a>
</section>`,
  ro: `<section data-label="09·02 RO Thank You" style="background:#000000; overflow:hidden;">
  <img src="/course/logo-sintezaur-white.png" alt="Sintezaur" style="position:absolute; left:48px; top:20px; height:84px; width:auto; opacity:0.85;">
  <div style="position:absolute; right:48px; top:48px; display:flex; align-items:center; gap:26px;"><img src="/course/logo-zeedo-white.svg" alt="Zeedo" style="height:26px; width:auto; opacity:0.6;"><img src="/course/logo-sequential.png" alt="Sequential" style="height:24px; width:auto; opacity:0.55;"></div>
  <h1 style="position:absolute; left:0; width:1920px; top:110px; margin:0; text-align:center; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:92px; line-height:1; color:#E8E8E8;">MULȚUMIM</h1>
  <svg style="position:absolute; left:650px; top:232px; width:620px; height:18px;" viewBox="0 0 860 24" fill="none"><path d="M6 12.5C120 10 260 14.5 400 12S640 10.5 740 13 830 11.5 854 12.3" stroke="#E97132" stroke-width="6.5" stroke-linecap="round"></path></svg>
  <p style="position:absolute; left:0; width:1920px; top:280px; margin:0; text-align:center; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-weight:400; font-size:36px; line-height:1.15; color:#B4B4B4;">Ia manualul acasă — EN sau RO</p>
  <div style="position:absolute; left:27px; top:400px; width:1866px; height:470px; box-sizing:border-box; border:2.5px solid #454545; border-radius:30px; background:rgba(255,255,255,0.02); display:grid; grid-template-columns:1fr 1fr 1fr; align-items:center; padding:0 60px;"><div style="text-align:center;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:38px; letter-spacing:3px; color:#FF8A48;">SINTEZAUR</p><p style="margin:14px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:30px; line-height:1.3; color:#E8E8E8;">comunitatea și workshopul următor</p><div style="margin:20px auto 0; width:120px; height:120px; border:2.5px solid #454545; border-radius:14px; display:flex; align-items:center; justify-content:center;"><span style="font-family:'Lato',sans-serif; font-size:24px; letter-spacing:2px; color:#6E6E6E;">QR</span></div></div><div style="text-align:center;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:38px; letter-spacing:3px; color:#FF8A48;">ZEEDO</p><p style="margin:14px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:30px; line-height:1.3; color:#E8E8E8;">unde încerci și cumperi Fourm</p><div style="margin:20px auto 0; width:120px; height:120px; border:2.5px solid #454545; border-radius:14px; display:flex; align-items:center; justify-content:center;"><span style="font-family:'Lato',sans-serif; font-size:24px; letter-spacing:2px; color:#6E6E6E;">QR</span></div></div><div style="text-align:center;"><p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:38px; letter-spacing:3px; color:#FF8A48;">SEQUENTIAL</p><p style="margin:14px 0 0; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:92%; font-size:30px; line-height:1.3; color:#E8E8E8;">manualul și presetele</p><div style="margin:20px auto 0; width:120px; height:120px; border:2.5px solid #454545; border-radius:14px; display:flex; align-items:center; justify-content:center;"><span style="font-family:'Lato',sans-serif; font-size:24px; letter-spacing:2px; color:#6E6E6E;">QR</span></div></div></div>
  <p style="position:absolute; left:0; width:1920px; top:920px; margin:0; text-align:center; font-family:'Lato',sans-serif; font-size:26px; letter-spacing:5px; color:#A7A7A7;">SINTEZAUR × ZEEDO · POWERED BY SEQUENTIAL</p>
  <p style="position:absolute; left:48px; top:1028px; margin:0; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">MODULUL 09 · WRAP-UP</p>
  <a data-go="hub" style="cursor:pointer; position:absolute; right:48px; top:1028px; font-family:'Lato',sans-serif; font-size:19px; letter-spacing:3px; color:#8F8F8F;">← CUPRINS</a>
</section>`,
};
