// Ported from v02.1 "Run of Show.dc.html" (flowing A4, light theme).
// RO is the original; EN is the 2026-08-26 translation (structure verified
// against RO: tables, rows, boxes, [fill-in] fields). PENDING Iulian's
// validation (workshops-spec.md §6).
export const RUN_OF_SHOW = {
  ro: `<div slot="footer" style="display:flex; justify-content:space-between; align-items:center; padding:6px 0; border-top:1px solid #E0E0E0; font-family:'Lato',sans-serif;">
  <div style="display:flex; align-items:center; gap:8px;"><img src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:16px; width:auto;"><span style="font-size:9px; letter-spacing:2px; color:#A0A0A0;">SINTEZAUR · DESFĂȘURĂTOR &amp; SETUP · v02.1</span></div>
  <span style="font-size:9px; letter-spacing:2px; color:#A0A0A0;">21 SEPTEMBRIE 2026 · CLUB CONTROL</span>
</div>
<div style="font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;">
  <div style="display:flex; justify-content:space-between; align-items:center;">
    <img src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:30px; width:auto;"><div style="display:flex; align-items:center; gap:14px; margin-left:auto; margin-right:14px;"><img src="/course/logo-zeedo-dark.svg" alt="Zeedo" style="height:14px; width:auto; opacity:0.75;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:3px; color:#8A8A8A;">SEQUENTIAL</span></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:3px; color:#8A8A8A;">DE IULIAN CAZAN</p>
  </div>
  <p style="margin:26px 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:#C25010;">DESFĂȘURĂTOR &amp; SETUP · 21 SEPTEMBRIE 2026, CLUB CONTROL</p>
  <h1 style="margin:8px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:40px; line-height:1.05; color:#111111;">INTRO TO SYNTHESIS</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6;">Foaia de zi a workshopului: setup-ul de la sosirea kitului până la deschiderea ușilor, desfășurătorul cu ora reală, planul B și strângerea. Se completează câmpurile <span style="color:#C25010;">[…]</span> înainte de ziua evenimentului. Sintezaur × Zeedo · powered by Sequential.</p>
  <div style="margin-top:26px;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#8A8A8A;">PARTEA 1</p>
    <h2 style="margin:4px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:26px; line-height:1.05; color:#111111;">SETUP · T−3h → T−0</h2>
  </div>
  <table style="margin-top:12px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;"><thead><tr><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CÂND</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CE</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">DETALII</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CINE</th></tr></thead><tbody>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−3:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Sosire kit + numărare</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Din kitul Sequential: <strong>11 Fourm</strong>, <strong>11 standuri X</strong>, <strong>20 căști ADAM H200</strong>, <strong>10 splittere</strong>, <strong>3 prize multiple</strong>, <strong>10 prelungitoare</strong> (8 ft / 15 ft). Plus <strong>synth-ul Zeedo</strong> și <strong>synth-ul lui Iulian</strong> = 13 Fourm-uri. Fiecare cutie se verifică la deschidere; ambalajul se păstrează intact pentru repack.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:45</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Layout</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;"><strong>12 stații</strong> (2 rânduri × 6 sau 3 × 4), toate cu vedere la ecran; <strong>stația prezentatorului</strong> în față, lateral, cu vedere la sală și la ecran; culoar de trecere printre mese (prezentatorul trece la fiecare exercițiu). Câte <strong>2 participanți</strong> la o stație.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Standuri + synth-uri</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Standul: pinul la a doua gaură, velcro în sus; synth-ul așezat pe velcro; alimentatorul legat de stand, cablul pe sub masă. Nimic nu atârnă la nivelul genunchilor.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Curent</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Prelungitoare 8 ft la mijloc / 15 ft la capete; <strong>o priză multiplă per rând</strong>, a doua înlănțuită în prima; <strong>toate synth-urile OFF</strong> înainte de a porni prizele, apoi <strong>ON, pe rând</strong>.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:45</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Căști</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Un splitter + 2 căști pe stație. Necesar: <strong>24 căști + 12 splittere</strong> → din kit 20 + 10 → <strong>+4 căști și +2 splittere de la Zeedo</strong>, marcate „de returnat la Zeedo”. Test: sunet în ambele căști ale fiecărei stații.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Audio + video</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Synth-ul prezentatorului (main out mono 1/4") → mixer PA + microfon, testat din fundul sălii; ecran 16:9 + laptop + HDMI + clicker; overhead camera cadrată pe panou (opțional). Prezentarea RO deschisă pe planșa de titlu.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Pe fiecare unitate</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;"><strong>main</strong> la 12 o&#x27;clock; Basic Program pe toate (hold <strong>transpose down</strong> + <strong>program</strong>) sau presetul ales; sunet în ambele căști. Vezi caseta „De verificat pe unități”.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−0:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Ultimele lucruri</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Manualele cursantului (EN + RO) la ieșire, nu pe mese; apă; foto/video la setup; scriptul prezentatorului + cheat sheet-ul la stația ta; presetele de DEMO verificate (F1 118 Bottle Service, F1 17 Glass Echo etc.).</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−0:15</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Ușile</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Participanții se așază câte doi la o stație; căștile rămân jos până la primul exercițiu.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
  </tbody></table>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:16px;">
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">NUMERE</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;24 de locuri · 12 stații (câte 2 la un synth) · 13 Fourm-uri (11 kit + 1 Zeedo + 1 Iulian).</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;90 de minute de curs (8 module + wrap-up), apoi free play. Q&amp;A 5 minute, inclus.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Necesar căști: 24 + 12 splittere. Din kit: 20 + 10. De la Zeedo: +4 căști, +2 splittere.</p>
  </div>
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">DE VERIFICAT PE UNITĂȚI</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Firmware-ul claviaturii: keymech OS ≥ 1.0.0.2 (versiunile vechi dau aftertouch maxim pe octava de jos).</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Global: Aftertouch = Poly · Clock Mode = Out sau Off (pe In arp-ul așteaptă clock extern) · Preset Mode = On · Velocity Curve = Medium.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;„Tune Voices” după 15 minute de încălzire; <strong>main</strong> la 12 o&#x27;clock; Basic Program pe toate.</p>
  </div>
  </div>
  <div style="break-before:page; page-break-before:always; margin-top:10px;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#8A8A8A;">PARTEA 2</p>
    <h2 style="margin:4px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:26px; line-height:1.05; color:#111111;">RUN OF SHOW · ora reală = <span style="color:#C25010;">[ORA START]</span> + offset</h2>
  </div>
  <table style="margin-top:12px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;"><thead><tr><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">ORA</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">MINUTAJ</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">SEGMENT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CONȚINUT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">RESPONSABIL</th></tr></thead><tbody>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:00–0:05</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>00 · WELCOME &amp; SETUP</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">00·01 Titlu · 00·02 Today · 00·03 Demo „distanța” · 00·04 Primul contact (Basic Program). Căștile jos.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:05</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:05–0:12</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>01 · SIGNAL FLOW</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Ce e într-un sunet · drumul vocii · unde pe Fourm · mixerul · exercițiu 0:10–0:12 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:12</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:12–0:23</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>02 · OSCILLATORS</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Formele de undă · octave &amp; acordaj · pulse width &amp; PWM · trucul de sub · noise · exercițiu 0:19–0:22 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:23</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:23–0:33</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>03 · FILTER</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Low-pass · resonance · key track &amp; env amount · exercițiu 0:29–0:32 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:33</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:33–0:44</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>04 · ENVELOPES</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">ADSR · două anvelope · bass vs pad · exercițiu 0:38–0:43 (bass + pad, în perechi) · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:44</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:44–0:53</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>05 · LFO &amp; MODULATION</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">LFO · secțiunea Modulation (route → destinație → amount, roșu/albastru) · exercițiu 0:49–0:52 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:53</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:53–1:02</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>06 · VOICES &amp; UNISON</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Polifonie · unison · chord memory (doar demo) · feedback · exercițiu 0:59–1:01 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:02</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:02–1:10</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>07 · EXPRESSION</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Velocity · poly aftertouch · rutarea presiunii · glide · exercițiu 1:07–1:09 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:10</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:10–1:17</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>08 · ARPEGGIATOR &amp; SEQUENCER</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Ține un acord · clock &amp; sync · note &amp; mod seq · exercițiu 1:14–1:16 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:17</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:17–1:26</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>09 · WRAP-UP</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Drumul, din nou · challenge (bass din Basic Program) · Q&amp;A (5 min) · mulțumiri (Zeedo, Sequential) + manualele la ieșire.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:26</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:26–1:30</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>FREE PLAY</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Synth-urile rămân ale participanților; propunerea „un sunet, șaizeci de secunde”; foto de grup.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:30–2:00</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>STRÂNGERE</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Repack (fiecare Fourm în cutia lui, alimentatorul lângă) · căștile și splitterele numărate (20 + 10 din kit; separat cele de la Zeedo) · standuri, prize, prelungitoare · checklist de retur semnat · 10 minute de notițe: ce a mers, ce a fost prea lung, ce întrebări au venit.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
  </tbody></table>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:16px;">
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">PLAN B</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Fără proiector:</strong> predai de la panou și din manualul cursantului; overhead camera pe un TV, dacă există.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Fără PA:</strong> căștile jos, tu cânți pe synth-ul tău printr-un amplificator sau o boxă locală; demo-urile se scurtează.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Un synth defect / blocat:</strong> Basic Program (hold <strong>transpose down</strong> + <strong>program</strong>); apoi <strong>main</strong>, mixer, <strong>cutoff</strong>, amount-urile la 12 o&#x27;clock, <strong>key track</strong>; ultima soluție: schimbi stația cu a ta.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Întârziere > 5 min:</strong> tai în ordinea 08·04 → demo lung 05 → 06·04 → demo 03·04 → demo 07·05 → exerciții la 90 s, fără swap.</p>
  </div>
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">CONTACTE</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Zeedo (retail / instrumente): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Club Control (sală, PA, ecran): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Sequential (Taiho): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Foto / video: <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Retur kit — cui, când, unde: <span style="color:#C25010;">[de completat]</span></p>
  </div>
  </div>

</div>`,
  en: `<div slot="footer" style="display:flex; justify-content:space-between; align-items:center; padding:6px 0; border-top:1px solid #E0E0E0; font-family:'Lato',sans-serif;">
  <div style="display:flex; align-items:center; gap:8px;"><img src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:16px; width:auto;"><span style="font-size:9px; letter-spacing:2px; color:#A0A0A0;">SINTEZAUR · RUN OF SHOW &amp; SETUP · v02.1</span></div>
  <span style="font-size:9px; letter-spacing:2px; color:#A0A0A0;">21 SEPTEMBER 2026 · CLUB CONTROL</span>
</div>
<div style="font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;">
  <div style="display:flex; justify-content:space-between; align-items:center;">
    <img src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:30px; width:auto;"><div style="display:flex; align-items:center; gap:14px; margin-left:auto; margin-right:14px;"><img src="/course/logo-zeedo-dark.svg" alt="Zeedo" style="height:14px; width:auto; opacity:0.75;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:3px; color:#8A8A8A;">SEQUENTIAL</span></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:3px; color:#8A8A8A;">BY IULIAN CAZAN</p>
  </div>
  <p style="margin:26px 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:#C25010;">RUN OF SHOW &amp; SETUP · 21 SEPTEMBER 2026, CLUB CONTROL</p>
  <h1 style="margin:8px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:40px; line-height:1.05; color:#111111;">INTRO TO SYNTHESIS</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6;">The workshop&#x27;s day sheet: setup from the kit&#x27;s arrival to doors, the run of show on real clock time, plan B and teardown. Fill in the <span style="color:#C25010;">[…]</span> fields before event day. Sintezaur × Zeedo · powered by Sequential.</p>
  <div style="margin-top:26px;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#8A8A8A;">PART 1</p>
    <h2 style="margin:4px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:26px; line-height:1.05; color:#111111;">SETUP · T−3h → T−0</h2>
  </div>
  <table style="margin-top:12px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;"><thead><tr><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">WHEN</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">WHAT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">DETAILS</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">WHO</th></tr></thead><tbody>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−3:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Kit arrival + count</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">From the Sequential kit: <strong>11 Fourms</strong>, <strong>11 X-stands</strong>, <strong>20 ADAM H200 headphones</strong>, <strong>10 splitters</strong>, <strong>3 power strips</strong>, <strong>10 extension cords</strong> (8 ft / 15 ft). Plus <strong>Zeedo&#x27;s synth</strong> and <strong>Iulian&#x27;s synth</strong> = 13 Fourms. Every box gets checked on opening; packaging stays intact for repack.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:45</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Layout</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;"><strong>12 stations</strong> (2 rows × 6 or 3 × 4), all with a clear view of the screen; the <strong>presenter&#x27;s station</strong> up front, off to the side, facing both the room and the screen; a walking aisle between the tables (the presenter passes through at every exercise). <strong>2 participants</strong> per station.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Stands + synths</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">The stand: pin in the second hole, velcro facing up; the synth seated on the velcro; power supply strapped to the stand, cable running under the table. Nothing dangles at knee height.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Power</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">8 ft extensions in the middle / 15 ft at the ends; <strong>one power strip per row</strong>, the second daisy-chained into the first; <strong>all synths OFF</strong> before the strips go live, then <strong>ON, one by one</strong>.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:45</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Headphones</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">One splitter + 2 headphones per station. Needed: <strong>24 headphones + 12 splitters</strong> → 20 + 10 from the kit → <strong>+4 headphones and +2 splitters from Zeedo</strong>, tagged &#x201C;return to Zeedo&#x201D;. Test: sound in both headphones at every station.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Audio + video</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Presenter&#x27;s synth (main out, mono 1/4&#x22;) → PA mixer + microphone, tested from the back of the room; 16:9 screen + laptop + HDMI + clicker; overhead camera framed on the panel (optional). The RO deck open on the title slide.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>On every unit</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;"><strong>main</strong> at 12 o&#x27;clock; Basic Program on all of them (hold <strong>transpose down</strong> + <strong>program</strong>) or the chosen preset; sound in both headphones. See the &#x201C;Per-unit checks&#x201D; box.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−0:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Last things</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Student handbooks (EN + RO) by the exit, not on the tables; water; photo/video of the setup; the presenter script + cheat sheet at your station; the DEMO presets checked (F1 118 Bottle Service, F1 17 Glass Echo etc.).</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−0:15</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Doors</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Participants sit two to a station; headphones stay down until the first exercise.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
  </tbody></table>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:16px;">
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">NUMBERS</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;24 seats · 12 stations (2 per synth) · 13 Fourms (11 kit + 1 Zeedo + 1 Iulian).</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;90 minutes of course (8 modules + wrap-up), then free play. Q&amp;A 5 minutes, included.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Headphones needed: 24 + 12 splitters. From the kit: 20 + 10. From Zeedo: +4 headphones, +2 splitters.</p>
  </div>
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">PER-UNIT CHECKS</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Keybed firmware: keymech OS ≥ 1.0.0.2 (older versions send maximum aftertouch on the bottom octave).</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Global: Aftertouch = Poly · Clock Mode = Out or Off (on In the arp waits for external clock) · Preset Mode = On · Velocity Curve = Medium.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;&#x201C;Tune Voices&#x201D; after 15 minutes of warm-up; <strong>main</strong> at 12 o&#x27;clock; Basic Program on all.</p>
  </div>
  </div>
  <div style="break-before:page; page-break-before:always; margin-top:10px;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#8A8A8A;">PART 2</p>
    <h2 style="margin:4px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:26px; line-height:1.05; color:#111111;">RUN OF SHOW · real time = <span style="color:#C25010;">[START TIME]</span> + offset</h2>
  </div>
  <table style="margin-top:12px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;"><thead><tr><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">TIME</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CLOCK</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">SEGMENT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CONTENT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">OWNER</th></tr></thead><tbody>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:00–0:05</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>00 · WELCOME &amp; SETUP</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">00·01 Title · 00·02 Today · 00·03 The &#x201C;distance&#x201D; demo · 00·04 First contact (Basic Program). Headphones down.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:05</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:05–0:12</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>01 · SIGNAL FLOW</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">What&#x27;s in a sound · the voice path · where on Fourm · the mixer · exercise 0:10–0:12 · terms.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:12</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:12–0:23</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>02 · OSCILLATORS</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">The waveshapes · octaves &amp; tuning · pulse width &amp; PWM · the sub trick · noise · exercise 0:19–0:22 · terms.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:23</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:23–0:33</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>03 · FILTER</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Low-pass · resonance · key track &amp; env amount · exercise 0:29–0:32 · terms.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:33</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:33–0:44</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>04 · ENVELOPES</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">ADSR · two envelopes · bass vs pad · exercise 0:38–0:43 (bass + pad, in pairs) · terms.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:44</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:44–0:53</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>05 · LFO &amp; MODULATION</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">The LFO · the Modulation section (route → destination → amount, red/blue) · exercise 0:49–0:52 · terms.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:53</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:53–1:02</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>06 · VOICES &amp; UNISON</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Polyphony · unison · chord memory (demo only) · feedback · exercise 0:59–1:01 · terms.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:02</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:02–1:10</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>07 · EXPRESSION</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Velocity · poly aftertouch · pressure routing · glide · exercise 1:07–1:09 · terms.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:10</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:10–1:17</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>08 · ARPEGGIATOR &amp; SEQUENCER</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Hold a chord · clock &amp; sync · note &amp; mod seq · exercise 1:14–1:16 · terms.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:17</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:17–1:26</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>09 · WRAP-UP</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">The road, again · challenge (bass from Basic Program) · Q&amp;A (5 min) · thanks (Zeedo, Sequential) + handbooks at the exit.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:26</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:26–1:30</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>FREE PLAY</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">The synths stay with the participants; the &#x201C;one sound, sixty seconds&#x201D; suggestion; group photo.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:30–2:00</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>TEARDOWN</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Repack (every Fourm in its own box, power supply alongside) · headphones and splitters counted (20 + 10 from the kit; Zeedo&#x27;s separately) · stands, strips, extensions · return checklist signed · 10 minutes of notes: what worked, what ran long, what questions came up.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[to fill in]</span></td></tr>
  </tbody></table>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:16px;">
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">PLAN B</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>No projector:</strong> teach from the panel and from the student handbook; overhead camera on a TV, if one exists.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>No PA:</strong> headphones down, you play your synth through an amp or a local speaker; demos get shortened.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>A faulty / frozen synth:</strong> Basic Program (hold <strong>transpose down</strong> + <strong>program</strong>); then <strong>main</strong>, mixer, <strong>cutoff</strong>, the amounts at 12 o&#x27;clock, <strong>key track</strong>; last resort: swap that station with yours.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>More than 5 min behind:</strong> cut in the order 08·04 → long demo in 05 → 06·04 → 03·04 demo → 07·05 demo → exercises at 90 s, no swap.</p>
  </div>
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">CONTACTS</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Zeedo (retail / instruments): <span style="color:#C25010;">[to fill in]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Club Control (room, PA, screen): <span style="color:#C25010;">[to fill in]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Sequential (Taiho): <span style="color:#C25010;">[to fill in]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Photo / video: <span style="color:#C25010;">[to fill in]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Kit return — to whom, when, where: <span style="color:#C25010;">[to fill in]</span></p>
  </div>
  </div>

</div>`,
};
