// Ported from v02.1 "Run of Show.dc.html" (flowing A4, light). RO is the
// original; EN starts as a copy and is replaced by the translation pass
// (workshops-spec.md §6 — everything bilingual).
export const RUN_OF_SHOW = {
  ro: `<div slot="footer" style="display:flex; justify-content:space-between; align-items:center; padding:6px 0; border-top:1px solid #E0E0E0; font-family:'Lato',sans-serif;">
  <div style="display:flex; align-items:center; gap:8px;"><img src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:16px; width:auto;"><span style="font-size:9px; letter-spacing:2px; color:#A0A0A0;">SINTEZAUR · DESFĂȘURĂTOR &amp; SETUP · v02.1</span></div>
  <span style="font-size:9px; letter-spacing:2px; color:#A0A0A0;">21 SEPTEMBRIE 2026 · CLUB CONTROL</span>
</div>
<div style="font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;">
  <div style="display:flex; justify-content:space-between; align-items:center;">
    <img src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:30px; width:auto;"><div style="display:flex; align-items:center; gap:14px; margin-left:auto; margin-right:14px;"><img src="/course/logo-zeedo-dark.svg" alt="Zeedo" style="height:14px; width:auto; opacity:0.75;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:3px; color:#8A8A8A;">SEQUENTIAL</span></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:3px; color:#8A8A8A;">DE IULIAN CAZAN</p>
  </div>
  <p style="margin:26px 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:#C25010;">DESFĂȘURĂTOR &amp; SETUP · 21 SEPTEMBRIE 2026, CLUB CONTROL</p>
  <h1 style="margin:8px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:40px; line-height:1.05; color:#111111;">INTRO TO SYNTHESIS</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6;">Foaia de zi a workshopului: setup-ul de la sosirea kitului până la deschiderea ușilor, desfășurătorul cu ora reală, planul B și strângerea. Se completează câmpurile <span style="color:#C25010;">[…]</span> înainte de ziua evenimentului. Sintezaur × Zeedo · powered by Sequential.</p>
  <div style="margin-top:26px;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#8A8A8A;">PARTEA 1</p>
    <h2 style="margin:4px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:26px; line-height:1.05; color:#111111;">SETUP · T−3h → T−0</h2>
  </div>
  <table style="margin-top:12px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;"><thead><tr><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CÂND</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CE</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">DETALII</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CINE</th></tr></thead><tbody>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−3:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Sosire kit + numărare</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Din kitul Sequential: <strong>11 Fourm</strong>, <strong>11 standuri X</strong>, <strong>20 căști ADAM H200</strong>, <strong>10 splittere</strong>, <strong>3 prize multiple</strong>, <strong>10 prelungitoare</strong> (8 ft / 15 ft). Plus <strong>synth-ul Zeedo</strong> și <strong>synth-ul lui Iulian</strong> = 13 Fourm-uri. Fiecare cutie se verifică la deschidere; ambalajul se păstrează intact pentru repack.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:45</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Layout</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;"><strong>12 stații</strong> (2 rânduri × 6 sau 3 × 4), toate cu vedere la ecran; <strong>stația prezentatorului</strong> în față, lateral, cu vedere la sală și la ecran; culoar de trecere printre mese (prezentatorul trece la fiecare exercițiu). Câte <strong>2 participanți</strong> la o stație.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Standuri + synth-uri</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Standul: pinul la a doua gaură, velcro în sus; synth-ul așezat pe velcro; alimentatorul legat de stand, cablul pe sub masă. Nimic nu atârnă la nivelul genunchilor.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Curent</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Prelungitoare 8 ft la mijloc / 15 ft la capete; <strong>o priză multiplă per rând</strong>, a doua înlănțuită în prima; <strong>toate synth-urile OFF</strong> înainte de a porni prizele, apoi <strong>ON, pe rând</strong>.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:45</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Căști</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Un splitter + 2 căști pe stație. Necesar: <strong>24 căști + 12 splittere</strong> → din kit 20 + 10 → <strong>+4 căști și +2 splittere de la Zeedo</strong>, marcate „de returnat la Zeedo”. Test: sunet în ambele căști ale fiecărei stații.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Audio + video</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Synth-ul prezentatorului (main out mono 1/4") → mixer PA + microfon, testat din fundul sălii; ecran 16:9 + laptop + HDMI + clicker; overhead camera cadrată pe panou (opțional). Prezentarea RO deschisă pe planșa de titlu.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Pe fiecare unitate</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;"><strong>main</strong> la 12 o&#x27;clock; Basic Program pe toate (hold <strong>transpose down</strong> + <strong>program</strong>) sau presetul ales; sunet în ambele căști. Vezi caseta „De verificat pe unități”.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−0:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Ultimele lucruri</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Manualele cursantului (EN + RO) la ieșire, nu pe mese; apă; foto/video la setup; scriptul prezentatorului + cheat sheet-ul la stația ta; presetele de DEMO verificate (F1 118 Bottle Service, F1 17 Glass Echo etc.).</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−0:15</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Ușile</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Participanții se așază câte doi la o stație; căștile rămân jos până la primul exercițiu.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
  </tbody></table>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:16px;">
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">NUMERE</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;24 de locuri · 12 stații (câte 2 la un synth) · 13 Fourm-uri (11 kit + 1 Zeedo + 1 Iulian).</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;90 de minute de curs (8 module + wrap-up), apoi free play. Q&amp;A 5 minute, inclus.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Necesar căști: 24 + 12 splittere. Din kit: 20 + 10. De la Zeedo: +4 căști, +2 splittere.</p>
  </div>
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">DE VERIFICAT PE UNITĂȚI</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Firmware-ul claviaturii: keymech OS ≥ 1.0.0.2 (versiunile vechi dau aftertouch maxim pe octava de jos).</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Global: Aftertouch = Poly · Clock Mode = Out sau Off (pe In arp-ul așteaptă clock extern) · Preset Mode = On · Velocity Curve = Medium.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;„Tune Voices” după 15 minute de încălzire; <strong>main</strong> la 12 o&#x27;clock; Basic Program pe toate.</p>
  </div>
  </div>
  <div style="break-before:page; page-break-before:always; margin-top:10px;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#8A8A8A;">PARTEA 2</p>
    <h2 style="margin:4px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:26px; line-height:1.05; color:#111111;">RUN OF SHOW · ora reală = <span style="color:#C25010;">[ORA START]</span> + offset</h2>
  </div>
  <table style="margin-top:12px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;"><thead><tr><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">ORA</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">MINUTAJ</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">SEGMENT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CONȚINUT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">RESPONSABIL</th></tr></thead><tbody>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:00–0:05</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>00 · WELCOME &amp; SETUP</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">00·01 Titlu · 00·02 Today · 00·03 Demo „distanța” · 00·04 Primul contact (Basic Program). Căștile jos.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:05</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:05–0:12</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>01 · SIGNAL FLOW</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Ce e într-un sunet · drumul vocii · unde pe Fourm · mixerul · exercițiu 0:10–0:12 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:12</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:12–0:23</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>02 · OSCILLATORS</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Formele de undă · octave &amp; acordaj · pulse width &amp; PWM · trucul de sub · noise · exercițiu 0:19–0:22 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:23</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:23–0:33</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>03 · FILTER</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Low-pass · resonance · key track &amp; env amount · exercițiu 0:29–0:32 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:33</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:33–0:44</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>04 · ENVELOPES</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">ADSR · două anvelope · bass vs pad · exercițiu 0:38–0:43 (bass + pad, în perechi) · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:44</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:44–0:53</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>05 · LFO &amp; MODULATION</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">LFO · secțiunea Modulation (route → destinație → amount, roșu/albastru) · exercițiu 0:49–0:52 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:53</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:53–1:02</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>06 · VOICES &amp; UNISON</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Polifonie · unison · chord memory (doar demo) · feedback · exercițiu 0:59–1:01 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:02</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:02–1:10</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>07 · EXPRESSION</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Velocity · poly aftertouch · rutarea presiunii · glide · exercițiu 1:07–1:09 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:10</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:10–1:17</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>08 · ARPEGGIATOR &amp; SEQUENCER</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Ține un acord · clock &amp; sync · note &amp; mod seq · exercițiu 1:14–1:16 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:17</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:17–1:26</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>09 · WRAP-UP</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Drumul, din nou · challenge (bass din Basic Program) · Q&amp;A (5 min) · mulțumiri (Zeedo, Sequential) + manualele la ieșire.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:26</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:26–1:30</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>FREE PLAY</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Synth-urile rămân ale participanților; propunerea „un sunet, șaizeci de secunde”; foto de grup.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:30–2:00</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>STRÂNGERE</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Repack (fiecare Fourm în cutia lui, alimentatorul lângă) · căștile și splitterele numărate (20 + 10 din kit; separat cele de la Zeedo) · standuri, prize, prelungitoare · checklist de retur semnat · 10 minute de notițe: ce a mers, ce a fost prea lung, ce întrebări au venit.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
  </tbody></table>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:16px;">
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">PLAN B</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Fără proiector:</strong> predai de la panou și din manualul cursantului; overhead camera pe un TV, dacă există.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Fără PA:</strong> căștile jos, tu cânți pe synth-ul tău printr-un amplificator sau o boxă locală; demo-urile se scurtează.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Un synth defect / blocat:</strong> Basic Program (hold <strong>transpose down</strong> + <strong>program</strong>); apoi <strong>main</strong>, mixer, <strong>cutoff</strong>, amount-urile la 12 o&#x27;clock, <strong>key track</strong>; ultima soluție: schimbi stația cu a ta.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Întârziere > 5 min:</strong> tai în ordinea 08·04 → demo lung 05 → 06·04 → demo 03·04 → demo 07·05 → exerciții la 90 s, fără swap.</p>
  </div>
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">CONTACTE</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Zeedo (retail / instrumente): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Club Control (sală, PA, ecran): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Sequential (Taiho): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Foto / video: <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Retur kit — cui, când, unde: <span style="color:#C25010;">[de completat]</span></p>
  </div>
  </div>

</div>`,
  // TODO(translation): EN version pending — currently the RO original.
  en: `<div slot="footer" style="display:flex; justify-content:space-between; align-items:center; padding:6px 0; border-top:1px solid #E0E0E0; font-family:'Lato',sans-serif;">
  <div style="display:flex; align-items:center; gap:8px;"><img src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:16px; width:auto;"><span style="font-size:9px; letter-spacing:2px; color:#A0A0A0;">SINTEZAUR · DESFĂȘURĂTOR &amp; SETUP · v02.1</span></div>
  <span style="font-size:9px; letter-spacing:2px; color:#A0A0A0;">21 SEPTEMBRIE 2026 · CLUB CONTROL</span>
</div>
<div style="font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;">
  <div style="display:flex; justify-content:space-between; align-items:center;">
    <img src="/course/logo-sintezaur-dark.png" alt="Sintezaur" style="height:30px; width:auto;"><div style="display:flex; align-items:center; gap:14px; margin-left:auto; margin-right:14px;"><img src="/course/logo-zeedo-dark.svg" alt="Zeedo" style="height:14px; width:auto; opacity:0.75;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:3px; color:#8A8A8A;">SEQUENTIAL</span></div>
    <p style="margin:0; font-family:'Lato',sans-serif; font-size:11px; letter-spacing:3px; color:#8A8A8A;">DE IULIAN CAZAN</p>
  </div>
  <p style="margin:26px 0 0; font-family:'Lato',sans-serif; font-weight:700; font-size:12px; letter-spacing:3px; color:#C25010;">DESFĂȘURĂTOR &amp; SETUP · 21 SEPTEMBRIE 2026, CLUB CONTROL</p>
  <h1 style="margin:8px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:40px; line-height:1.05; color:#111111;">INTRO TO SYNTHESIS</h1>
  <svg style="display:block; margin-top:10px; width:320px; height:12px;" viewBox="0 0 320 12" fill="none"><path d="M3 6.5C45 5 95 8 150 6S240 5 285 7 310 6 317 6.3" stroke="#E97132" stroke-width="3.5" stroke-linecap="round"></path></svg>
  <p style="margin:14px 0 0; font-stretch:92%; font-size:13.5px; line-height:1.6;">Foaia de zi a workshopului: setup-ul de la sosirea kitului până la deschiderea ușilor, desfășurătorul cu ora reală, planul B și strângerea. Se completează câmpurile <span style="color:#C25010;">[…]</span> înainte de ziua evenimentului. Sintezaur × Zeedo · powered by Sequential.</p>
  <div style="margin-top:26px;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#8A8A8A;">PARTEA 1</p>
    <h2 style="margin:4px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:26px; line-height:1.05; color:#111111;">SETUP · T−3h → T−0</h2>
  </div>
  <table style="margin-top:12px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;"><thead><tr><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CÂND</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CE</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">DETALII</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CINE</th></tr></thead><tbody>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−3:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Sosire kit + numărare</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Din kitul Sequential: <strong>11 Fourm</strong>, <strong>11 standuri X</strong>, <strong>20 căști ADAM H200</strong>, <strong>10 splittere</strong>, <strong>3 prize multiple</strong>, <strong>10 prelungitoare</strong> (8 ft / 15 ft). Plus <strong>synth-ul Zeedo</strong> și <strong>synth-ul lui Iulian</strong> = 13 Fourm-uri. Fiecare cutie se verifică la deschidere; ambalajul se păstrează intact pentru repack.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:45</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Layout</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;"><strong>12 stații</strong> (2 rânduri × 6 sau 3 × 4), toate cu vedere la ecran; <strong>stația prezentatorului</strong> în față, lateral, cu vedere la sală și la ecran; culoar de trecere printre mese (prezentatorul trece la fiecare exercițiu). Câte <strong>2 participanți</strong> la o stație.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Standuri + synth-uri</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Standul: pinul la a doua gaură, velcro în sus; synth-ul așezat pe velcro; alimentatorul legat de stand, cablul pe sub masă. Nimic nu atârnă la nivelul genunchilor.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−2:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Curent</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Prelungitoare 8 ft la mijloc / 15 ft la capete; <strong>o priză multiplă per rând</strong>, a doua înlănțuită în prima; <strong>toate synth-urile OFF</strong> înainte de a porni prizele, apoi <strong>ON, pe rând</strong>.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:45</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Căști</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Un splitter + 2 căști pe stație. Necesar: <strong>24 căști + 12 splittere</strong> → din kit 20 + 10 → <strong>+4 căști și +2 splittere de la Zeedo</strong>, marcate „de returnat la Zeedo”. Test: sunet în ambele căști ale fiecărei stații.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Audio + video</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Synth-ul prezentatorului (main out mono 1/4") → mixer PA + microfon, testat din fundul sălii; ecran 16:9 + laptop + HDMI + clicker; overhead camera cadrată pe panou (opțional). Prezentarea RO deschisă pe planșa de titlu.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−1:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Pe fiecare unitate</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;"><strong>main</strong> la 12 o&#x27;clock; Basic Program pe toate (hold <strong>transpose down</strong> + <strong>program</strong>) sau presetul ales; sunet în ambele căști. Vezi caseta „De verificat pe unități”.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−0:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Ultimele lucruri</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Manualele cursantului (EN + RO) la ieșire, nu pe mese; apă; foto/video la setup; scriptul prezentatorului + cheat sheet-ul la stația ta; presetele de DEMO verificate (F1 118 Bottle Service, F1 17 Glass Echo etc.).</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">T−0:15</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><strong>Ușile</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Participanții se așază câte doi la o stație; căștile rămân jos până la primul exercițiu.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
  </tbody></table>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:16px;">
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">NUMERE</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;24 de locuri · 12 stații (câte 2 la un synth) · 13 Fourm-uri (11 kit + 1 Zeedo + 1 Iulian).</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;90 de minute de curs (8 module + wrap-up), apoi free play. Q&amp;A 5 minute, inclus.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Necesar căști: 24 + 12 splittere. Din kit: 20 + 10. De la Zeedo: +4 căști, +2 splittere.</p>
  </div>
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">DE VERIFICAT PE UNITĂȚI</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Firmware-ul claviaturii: keymech OS ≥ 1.0.0.2 (versiunile vechi dau aftertouch maxim pe octava de jos).</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Global: Aftertouch = Poly · Clock Mode = Out sau Off (pe In arp-ul așteaptă clock extern) · Preset Mode = On · Velocity Curve = Medium.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;„Tune Voices” după 15 minute de încălzire; <strong>main</strong> la 12 o&#x27;clock; Basic Program pe toate.</p>
  </div>
  </div>
  <div style="break-before:page; page-break-before:always; margin-top:10px;">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#8A8A8A;">PARTEA 2</p>
    <h2 style="margin:4px 0 0; font-family:'Aptos Display','Aptos','Instrument Sans','Segoe UI',sans-serif; font-stretch:88%; font-weight:400; font-size:26px; line-height:1.05; color:#111111;">RUN OF SHOW · ora reală = <span style="color:#C25010;">[ORA START]</span> + offset</h2>
  </div>
  <table style="margin-top:12px; font-family:'Aptos','Instrument Sans','Segoe UI',sans-serif; color:#333333;"><thead><tr><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">ORA</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">MINUTAJ</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">SEGMENT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">CONȚINUT</th><th style="text-align:left; padding:6px 8px; border-bottom:2px solid #C25010; font-family:'Lato',sans-serif; font-size:9px; letter-spacing:2px; color:#8A8A8A;">RESPONSABIL</th></tr></thead><tbody>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:00</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:00–0:05</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>00 · WELCOME &amp; SETUP</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">00·01 Titlu · 00·02 Today · 00·03 Demo „distanța” · 00·04 Primul contact (Basic Program). Căștile jos.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:05</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:05–0:12</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>01 · SIGNAL FLOW</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Ce e într-un sunet · drumul vocii · unde pe Fourm · mixerul · exercițiu 0:10–0:12 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:12</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:12–0:23</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>02 · OSCILLATORS</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Formele de undă · octave &amp; acordaj · pulse width &amp; PWM · trucul de sub · noise · exercițiu 0:19–0:22 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:23</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:23–0:33</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>03 · FILTER</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Low-pass · resonance · key track &amp; env amount · exercițiu 0:29–0:32 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:33</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:33–0:44</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>04 · ENVELOPES</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">ADSR · două anvelope · bass vs pad · exercițiu 0:38–0:43 (bass + pad, în perechi) · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:44</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:44–0:53</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>05 · LFO &amp; MODULATION</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">LFO · secțiunea Modulation (route → destinație → amount, roșu/albastru) · exercițiu 0:49–0:52 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+0:53</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">0:53–1:02</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>06 · VOICES &amp; UNISON</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Polifonie · unison · chord memory (doar demo) · feedback · exercițiu 0:59–1:01 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:02</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:02–1:10</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>07 · EXPRESSION</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Velocity · poly aftertouch · rutarea presiunii · glide · exercițiu 1:07–1:09 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:10</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:10–1:17</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>08 · ARPEGGIATOR &amp; SEQUENCER</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Ține un acord · clock &amp; sync · note &amp; mod seq · exercițiu 1:14–1:16 · termeni.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:17</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:17–1:26</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>09 · WRAP-UP</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Drumul, din nou · challenge (bass din Basic Program) · Q&amp;A (5 min) · mulțumiri (Zeedo, Sequential) + manualele la ieșire.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:26</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:26–1:30</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>FREE PLAY</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Synth-urile rămân ale participanților; propunerea „un sunet, șaizeci de secunde”; foto de grup.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
    <tr class="row"><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap;"><span style="font-family:'Lato',sans-serif; font-weight:700; font-size:10px; letter-spacing:2px; color:#FFFFFF; background:#C25010; border-radius:999px; padding:2px 10px; white-space:nowrap;">+1:30</span></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;">1:30–2:00</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; font-family:'Lato',sans-serif; font-weight:700; font-size:9.5px; letter-spacing:1.5px; color:#C25010;"><strong>STRÂNGERE</strong></td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45;">Repack (fiecare Fourm în cutia lui, alimentatorul lângă) · căștile și splitterele numărate (20 + 10 din kit; separat cele de la Zeedo) · standuri, prize, prelungitoare · checklist de retur semnat · 10 minute de notițe: ce a mers, ce a fost prea lung, ce întrebări au venit.</td><td style="padding:7px 8px; border-bottom:1px solid #E6E6E6; vertical-align:top; font-stretch:92%; font-size:11.5px; line-height:1.45; white-space:nowrap; color:#6E6E6E;"><span style="color:#C25010;">[de completat]</span></td></tr>
  </tbody></table>
  <div style="display:grid; grid-template-columns:1fr 1fr; column-gap:16px;">
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">PLAN B</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Fără proiector:</strong> predai de la panou și din manualul cursantului; overhead camera pe un TV, dacă există.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Fără PA:</strong> căștile jos, tu cânți pe synth-ul tău printr-un amplificator sau o boxă locală; demo-urile se scurtează.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Un synth defect / blocat:</strong> Basic Program (hold <strong>transpose down</strong> + <strong>program</strong>); apoi <strong>main</strong>, mixer, <strong>cutoff</strong>, amount-urile la 12 o&#x27;clock, <strong>key track</strong>; ultima soluție: schimbi stația cu a ta.</p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;<strong>Întârziere > 5 min:</strong> tai în ordinea 08·04 → demo lung 05 → 06·04 → demo 03·04 → demo 07·05 → exerciții la 90 s, fără swap.</p>
  </div>
<div style="margin:18px 0 0; border:1px solid #E0E0E0; border-radius:10px; padding:14px 18px;" class="row">
    <p style="margin:0; font-family:'Lato',sans-serif; font-weight:700; font-size:11px; letter-spacing:2.5px; color:#C25010;">CONTACTE</p>
    <p style="margin:8px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Zeedo (retail / instrumente): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Club Control (sală, PA, ecran): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Sequential (Taiho): <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Foto / video: <span style="color:#C25010;">[de completat]</span></p>
    <p style="margin:7px 0 0; font-stretch:92%; font-size:12.5px; line-height:1.55;">· &nbsp;Retur kit — cui, când, unde: <span style="color:#C25010;">[de completat]</span></p>
  </div>
  </div>

</div>`,
};
