import type { BeatSlides, ScriptModule } from '../../script/types';

/**
 * The presenter script's beats — first ported out of the v02.1 hand-written
 * document by tools/scripts/port-script-beats.ts, then edited here. SAY /
 * DEMO / THEY DO are the original wording; the clock is not stored, the
 * renderer adds `minutes` up so a shorter cut retimes itself.
 *
 * This is the EXTENDED (90') cut; variants.ts says what the 60' one changes.
 */
export const SCRIPT_MODULES: ScriptModule[] = [
  {
    id: '00',
    title: { en: `MODULE 00 · WELCOME &amp; SETUP`, ro: `MODULUL 00 · WELCOME &amp; SETUP` },
    beats: [
    {
      id: '00·01',
      title: { en: `TITLE`, ro: `TITLE` },
      minutes: 1,
      say: { en: `&#x201C;Welcome. I&#x27;m Iulian, from Sintezaur. Over the next ninety minutes you&#x27;ll come to understand every stage a sound passes through inside a subtractive synthesizer — and you&#x27;ll hear it, not from me, but from under your own fingers, on the instrument in front of you: the Sequential Fourm. Thank you to Zeedo, who made this possible, and to Sequential, who lent us the instruments. The map behind me is the whole course: eight stops, in the order the signal travels.&#x201D;`, ro: `„Bine ați venit. Sunt Iulian, de la Sintezaur. În următoarele nouăzeci de minute o să înțelegeți fiecare etapă prin care trece un sunet într-un sintetizator subtractiv, și o să o auziți — nu de la mine, ci de sub degetele voastre, pe instrumentul din fața voastră: Sequential Fourm. Mulțumim celor de la Zeedo, prin care s-a putut întâmpla asta, și celor de la Sequential, care ne-au împrumutat instrumentele. Harta din spatele meu e tot cursul: opt opriri, în ordinea în care circulă semnalul."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '00·02',
      title: { en: `TODAY`, ro: `TODAY` },
      minutes: 2,
      say: { en: `&#x201C;Three things before we start. One: you&#x27;re two to a synth. Swap at the controls at every exercise, so the panel passes through both pairs of hands, and both of you watch me: nobody has to read anything. Two: headphones — on when you play, one ear free when I&#x27;m talking; MAIN volume at twelve o&#x27;clock, and we leave it there. Three: if you get lost, you have a home button: hold TRANSPOSE DOWN and press PROGRAM. That loads Basic Program — a plain saw with the filter open. That&#x27;s where we start from every time. Don&#x27;t press PROGRAM otherwise, or you&#x27;ll lose the sound you just built. And: there are no wrong sounds today. Explore first, then we talk.&#x201D;`, ro: `„Trei lucruri înainte să pornim. Unu: sunteți doi la un synth. Faceți schimb la controale la fiecare exercițiu, ca să treacă panoul prin ambele perechi de mâini, și uitați-vă amândoi la mine: nu trebuie să citiți nimic. Doi: căștile — sus când cântați, o ureche liberă când vorbesc eu; volumul MAIN la ora douăsprezece și îl lăsăm acolo. Trei: dacă vă pierdeți, aveți un buton de acasă: țineți apăsat TRANSPOSE DOWN și apăsați PROGRAM. Se încarcă Basic Program — un saw simplu, cu filtrul deschis. De acolo pornim de fiecare dată. Nu apăsați PROGRAM altfel, că pierdeți sunetul pe care tocmai l-ați construit. Și: nu există sunete greșite azi. Explorați, apoi vorbim."` },
    },
    {
      id: '00·03',
      title: { en: `DEMO · THE DISTANCE`, ro: `DEMO · DISTANȚA` },
      minutes: 1,
      say: { en: `&#x201C;This is a factory sound.&#x201D; (play the spectacular preset for 20 seconds) &#x201C;And this is point zero.&#x201D; (Basic Program, a few notes) &#x201C;By the end we&#x27;ll have built the distance between these two — and you&#x27;ll know what every knob does along the way.&#x201D;`, ro: `„Ăsta e un sunet de fabrică." (cânți 20 de secunde pe presetul spectaculos ales) „Și ăsta e punctul zero." (Basic Program, câteva note) „Până la final construim distanța dintre astea două — și o să știți ce face fiecare buton pe drum."` },
      room: { en: `PA · Headphones down`, ro: `PA · Căștile jos` },
    },
    {
      id: '00·04',
      title: { en: `FIRST CONTACT`, ro: `PRIMUL CONTACT` },
      minutes: 1,
      say: { en: `&#x201C;Headphones on. Play a few notes on whatever is loaded right now. Then do the reset: hold TRANSPOSE DOWN, press PROGRAM. Play again: this plain saw is where every sound today starts from. Swap and repeat.&#x201D;`, ro: `„Căștile sus. Cântați câteva note pe ce e încărcat acum. Apoi faceți resetul: țineți TRANSPOSE DOWN, apăsați PROGRAM. Cântați din nou: acest saw simplu e locul de unde pornește orice sunet de azi. Schimbați și repetați."` },
      theyDo: { en: `(A) plays a few notes → hold <strong>transpose down</strong> + press <strong>program</strong> → plays again. (B) the same. You walk the tables and check everyone is on Basic Program.`, ro: `(A) cântă câteva note → hold <strong>transpose down</strong> + press <strong>program</strong> → cântă din nou. (B) la fel. Tu treci printre mese și verifici că toți sunt pe Basic Program.` },
    },
    ],
  },
  {
    id: '01',
    title: { en: `MODULE 01 · SIGNAL FLOW`, ro: `MODULUL 01 · SIGNAL FLOW` },
    beats: [
    {
      id: '01·01',
      title: { en: `COVER`, ro: `COVER` },
      minutes: 1,
      say: { en: `&#x201C;The whole course rests on a single idea: sound follows a path. Learn the path once and no synthesizer will ever look complicated again, no matter how many knobs it has.&#x201D;`, ro: `„Tot cursul stă pe o singură idee: sunetul urmează un drum. Învață drumul o dată și niciun sintetizator nu o să ți se mai pară complicat, oricâte butoane are."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '01·02',
      title: { en: `WHAT&#x27;S IN A SOUND`, ro: `WHAT&#x27;S IN A SOUND` },
      minutes: 1,
      say: { en: `&#x201C;What&#x27;s inside a sound? A note isn&#x27;t a single frequency: it&#x27;s one base frequency, the fundamental, plus a tower of quieter tones stacked above it — the harmonics. Their blend is what we hear as timbre. A saw has all of them, a square only the odd ones, a triangle the odd ones too but fading fast, which is why one is bright, one hollow, one soft. Subtractive synthesis starts from a rich wave and takes away. Think of a sculptor: the raw block is the wave, the chisel is the filter, and the shape over time comes from the envelopes.&#x201D;`, ro: `„Ce e într-un sunet? O notă nu e o singură frecvență: e o frecvență de bază, fundamentala, plus un turn de tonuri mai slabe deasupra, armonicele. Amestecul lor e ceea ce auzim ca timbru. Un saw le are pe toate, un pătrat doar pe cele impare, un triangle tot pe cele impare, dar care scad repede, de aia unul e strălucitor, altul gol, altul moale. Sinteza subtractivă pornește de la o undă bogată și scoate din ea. Gândiți-vă la un sculptor: blocul brut e unda, dalta e filtrul, iar forma în timp o dau anvelopele."` },
      demo: { en: `<strong>(20 s):</strong> a lone saw — &#x201C;a boring buzz, like the cheapest transistor organ&#x201D; — then the same saw with the filter half closed and a slow attack: &#x201C;the same block, sculpted.&#x201D;`, ro: `<strong>(20 s):</strong> un saw singur — „un bâzâit plictisitor, ca cea mai ieftină orgă cu tranzistori" — apoi același saw cu filtrul închis pe jumătate și un attack lent: „același bloc, sculptat."` },
      room: { en: `PA · Headphones down`, ro: `PA · Căștile jos` },
    },
    {
      id: '01·03',
      title: { en: `THE VOICE PATH`, ro: `THE VOICE PATH` },
      minutes: 1,
      say: { en: `&#x201C;Left to right: the oscillators make the raw tone, the mixer balances four sources, the filter sculpts the brightness, the amplifier shapes the volume, the speaker gets the result. The dotted line: the Fourm can feed its own signal back into the mixer — feedback; we&#x27;ll use it in module 6.&#x201D;`, ro: `„De la stânga la dreapta: oscilatoarele fac tonul brut, mixerul echilibrează patru surse, filtrul sculptează strălucirea, amplificatorul modelează volumul, boxa primește rezultatul. Linia punctată: Fourm își poate întoarce propriul semnal înapoi în mixer — feedback-ul; îl folosim în modulul 6."` },
    },
    {
      id: '01·04',
      title: { en: `WHERE ON FOURM`, ro: `WHERE ON FOURM` },
      minutes: 1,
      say: { en: `&#x201C;Here&#x27;s the best part: the panel is laid out in the same order as the path. Look at your synth and put a finger on it: oscillators, mixer, filter, envelopes, main. The sections on the left — modulation, aftertouch — and the ones along the bottom — unison, glide, LFO, clock, arpeggiator — we&#x27;ll take one by one, in the modules ahead.&#x201D;`, ro: `„Partea cea mai bună: panoul e așezat în aceeași ordine ca drumul. Uitați-vă la synth-ul vostru și puneți degetul: oscilatoare, mixer, filtru, anvelope, main. Secțiunile din stânga — modulation, aftertouch — și cele de jos — unison, glide, LFO, clock, arpeggiator — le luăm pe rând, în modulele următoare."` },
    },
    {
      id: '01·05',
      title: { en: `THE MIXER`, ro: `THE MIXER` },
      minutes: 1,
      say: { en: `&#x201C;Four sources: Osc A, Osc B, noise, feedback. The golden rule of troubleshooting, which I&#x27;ll repeat all evening: if you hear nothing, check the mixer first, then the cutoff, then any amount knob left at twelve o&#x27;clock.&#x201D;`, ro: `„Patru surse: Osc A, Osc B, noise, feedback. Regula de aur a depanării, pe care o s-o repet toată seara: dacă nu auzi nimic, verifică întâi mixerul, apoi cutoff-ul, apoi orice knob de amount lăsat la ora douăsprezece."` },
      demo: { en: `bring up Osc A alone, add B, then a hiss of noise on top.`, ro: `ridici Osc A singur, adaugi B, apoi un fâșâit de noise peste.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '01·06',
      title: { en: `TRY IT`, ro: `TRY IT` },
      minutes: 2,
      say: { en: `&#x201C;Headphones on. From Basic Program: hold a note and take OSC A in the mixer down to zero. Silence — no source, no sound. Bring it back. Press SAW on Oscillator B and raise OSC B: two oscillators, one note, already fatter. Swap: your partner does the same, and at the end, trace the path across the panel with a finger.&#x201D;`, ro: `„Căștile sus. Din Basic Program: țineți o notă și dați OSC A din mixer la zero. Liniște — fără sursă, fără sunet. Aduceți-l înapoi. Apăsați SAW la Oscillator B și ridicați OSC B: două oscilatoare, o notă, deja mai gros. Schimbați: partenerul face același lucru și, la final, urmăriți cu degetul drumul pe panou."` },
      theyDo: { en: `(A) <strong>osc a</strong> to zero → silence → back up; Osc B <strong>saw</strong> on; <strong>osc b</strong> up. (B) repeats; both trace the path with a finger. You walk the tables.`, ro: `(A) <strong>osc a</strong> la zero → liniște → înapoi; Osc B <strong>saw</strong> on; <strong>osc b</strong> sus. (B) repetă; ambii urmăresc drumul cu degetul. Tu treci printre mese.` },
    },
    {
      id: '01·07',
      title: { en: `KEY TERMS`, ro: `KEY TERMS` },
      minutes: 0,
      say: { en: `&#x201C;The terms: VCO, mixer, VCF, VCA, feedback, harmonics. They come back in every module; stop me now if any of them is unclear.&#x201D; A real three-second pause.`, ro: `„Termenii: VCO, mixer, VCF, VCA, feedback, armonice. Se întorc în fiecare modul; opriți-mă acum dacă vreunul e neclar." Pauză reală de trei secunde.` },
    },
    ],
  },
  {
    id: '02',
    title: { en: `MODULE 02 · OSCILLATORS`, ro: `MODULUL 02 · OSCILLATORS` },
    beats: [
    {
      id: '02·01',
      title: { en: `COVER`, ro: `COVER` },
      minutes: 1,
      say: { en: `&#x201C;First stop: the place where sound is born. Everything further down the path only removes or reshapes what the oscillators give us. That&#x27;s why the waveshapes matter so much.&#x201D;`, ro: `„Prima oprire: locul unde se naște sunetul. Tot ce urmează pe drum doar scoate sau remodelează ce ne dau oscilatoarele. De aia formele de undă contează atât."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '02·02',
      title: { en: `THE WAVESHAPES`, ro: `THE WAVESHAPES` },
      minutes: 2,
      say: { en: `&#x201C;Three shapes, three personalities. Saw: all the harmonics, the bright workhorse — brass, strings. Triangle: soft, almost pure — the sub layer. Pulse: hollow like a clarinet when it&#x27;s square, thin and nasal as it narrows — with a secret parameter we&#x27;ll open up in a moment.&#x201D;`, ro: `„Trei forme, trei personalități. Saw: toate armonicele, calul de povară strălucitor — alămuri, coarde. Triangle: moale, aproape pur — stratul de sub. Pulse: gol ca un clarinet când e pătrat, subțire și nazal când se îngustează — și cu un parametru secret pe care îl deschidem imediat."` },
      demo: { en: `same note, slowly switch through the three shapes. Then the game (30 s): &#x201C;Which shape is this?&#x201D; — play saw / pulse / tri at random, the room shouts. &#x201C;Learn to recognize them and you&#x27;ll hear them in every track from now on.&#x201D;`, ro: `aceeași notă, schimbi lent cele trei forme. Apoi jocul (30 s): „Ce formă e asta?" — cânți la întâmplare saw / pulse / tri, sala strigă. „Învățați să le recunoașteți și o să le auziți în orice piesă de acum încolo."` },
      room: { en: `PA · Headphones down`, ro: `PA · Căștile jos` },
    },
    {
      id: '02·03',
      title: { en: `OCTAVES &amp; TUNING`, ro: `OCTAVES &amp; TUNING` },
      minutes: 1,
      say: { en: `&#x201C;The registers: five octave positions, from minus two to plus two, on each oscillator; A and B an octave apart means instant size. FREQUENCY is the fine tuning, up to seven semitones. And here&#x27;s the first secret of &#x2018;fatness&#x2019;: detune B slightly against A and the two waves start beating against each other — the sound breathes. Too far, and you hear two notes.&#x201D;`, ro: `„Registrele: cinci poziții de octavă, de la minus doi la plus doi, pe fiecare oscilator; A și B la o octavă distanță înseamnă mărime instant. FREQUENCY e acordajul fin, până la șapte semitonuri. Și aici e primul secret al «grosimii»: dezacordezi puțin B față de A și cele două unde încep să bată una în alta — sunetul respiră. Prea mult, și auzi două note."` },
      demo: { en: `B&#x27;s <strong>frequency</strong> from center slowly to the left: slow beats → chorus → two notes → back.`, ro: `B cu <strong>frequency</strong> de la centru încet spre stânga: bătăi lente → chorus → două note → înapoi.` },
    },
    {
      id: '02·04',
      title: { en: `PULSE WIDTH &amp; PWM`, ro: `PULSE WIDTH &amp; PWM` },
      minutes: 1,
      say: { en: `&#x201C;The pulse&#x27;s secret: its width. On the Fourm there&#x27;s no knob — hold PULSE and turn SELECT. Zero is the square; toward the edge it thins out, like through a straw, until it disappears. Hand its width to the LFO and the tone won&#x27;t sit still: a single oscillator that sounds like a chorus. That&#x27;s PWM, and we&#x27;ll do it in module 5.&#x201D;`, ro: `„Secretul pulsului: lățimea lui. Pe Fourm nu e knob — țineți PULSE apăsat și rotiți SELECT. Zero e pătratul; spre margine se subțiază, ca printr-un pai, până dispare. Dă-i lățimea LFO-ului și tonul nu mai stă locului: un singur oscilator care sună a chorus. Asta e PWM și o facem în modulul 5."` },
      demo: { en: `sweep the PW by hand.`, ro: `plimbi PW cu mâna.` },
    },
    {
      id: '02·05',
      title: { en: `THE SUB TRICK`, ro: `THE SUB TRICK` },
      minutes: 1,
      say: { en: `&#x201C;The ten-second trick: Osc B on triangle, one octave below A. The nearly pure wave slides underneath the tone and adds nothing but weight — no clutter.&#x201D;`, ro: `„Trucul de zece secunde: Osc B pe triangle, o octavă sub A. Unda aproape pură alunecă sub ton și adaugă doar greutate, fără aglomerație."` },
      demo: { en: `A alone, add the sub, take it out — &#x201C;the room has to feel the hole.&#x201D;`, ro: `A singur, adaugi sub-ul, îl scoți — „sala trebuie să simtă golul."` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '02·06',
      title: { en: `NOISE`, ro: `NOISE` },
      minutes: 1,
      say: { en: `&#x201C;Noise: every frequency at once, no pitch — the raw material of drums. Three colors: white is full, pink is warm, violet leans into the highs. Press NOISE, hold and turn SELECT for the level. A little sharpens the attack; a lot becomes percussion.&#x201D;`, ro: `„Noise: toate frecvențele deodată, fără înălțime — materia primă a tobelor. Trei culori: white plin, pink cald, violet spre înalte. Apeși NOISE, ții și rotești SELECT pentru nivel. Puțin ascute atacul, mult devine percuție."` },
      demo: { en: `<strong>(20 s):</strong> noise alone with a short envelope = hi-hat.`, ro: `<strong>(20 s):</strong> noise singur cu anvelopă scurtă = hi-hat.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '02·07',
      title: { en: `TRY IT`, ro: `TRY IT` },
      minutes: 3,
      say: { en: `&#x201C;Headphones on, from Basic Program. Osc A: press PULSE, so both saw and pulse are lit. Hold PULSE and turn SELECT toward the edge, then back. Osc B: press TRI, octave to minus one, raise OSC B in the mixer — put the sub in, take it out, feel the weight. Nudge B&#x27;s FREQUENCY a little off center and listen to the beats; too far and it splits into two notes — bring it back. Press NOISE, hold and turn SELECT to about thirty: just a bit of air. Swap halfway.&#x201D;`, ro: `„Căștile sus, din Basic Program. Osc A: apăsați PULSE, să fie aprinse și saw și pulse. Țineți PULSE și rotiți SELECT spre margine, apoi înapoi. Osc B: apăsați TRI, octava la minus unu, ridicați OSC B din mixer — puneți sub-ul, scoateți-l, simțiți greutatea. Mișcați FREQUENCY-ul lui B puțin de la centru și ascultați bătăile; prea mult și se despart în două note — aduceți-l înapoi. Apăsați NOISE, țineți și rotiți SELECT până la vreo treizeci: doar un pic de aer. Schimbați la jumătate."` },
      theyDo: { en: `(A) Osc A: <strong>pulse</strong> on (saw + pulse) → hold <strong>pulse|pw</strong> + <strong>select</strong> toward the edge and back → Osc B: <strong>tri</strong> on, octave -1, <strong>osc b</strong> up → B&#x27;s <strong>frequency</strong> slightly off-centre → back. (B) <strong>noise</strong> on → hold <strong>noise</strong> + <strong>select</strong> ~30 → plays; then repeats A&#x27;s steps. The result stays on the synth: it&#x27;s the raw material for the bass in module 4.`, ro: `(A) Osc A: <strong>pulse</strong> on (saw + pulse) → hold <strong>pulse|pw</strong> + <strong>select</strong> spre margine și înapoi → Osc B: <strong>tri</strong> on, octave -1, <strong>osc b</strong> sus → <strong>frequency</strong> B ușor off-centre → înapoi. (B) <strong>noise</strong> on → hold <strong>noise</strong> + <strong>select</strong> ~30 → cântă; apoi repetă pașii lui A. Rezultatul rămâne pe synth: e materia primă a bass-ului din modulul 4.` },
      room: { en: `You walk the tables`, ro: `Umbli printre mese` },
    },
    {
      id: '02·08',
      title: { en: `KEY TERMS`, ro: `KEY TERMS` },
      minutes: 1,
      say: { en: `&#x201C;Recap: waveshape, harmonics, pulse width and PWM, sub, noise, the LO modes — for the curious, they&#x27;re in the student handbook. Question for the room: who has heard PWM in a track without knowing its name? Everyone, starting today.&#x201D;`, ro: `„Recapitulare: waveshape, armonice, pulse width și PWM, sub, noise, modurile LO — pentru curioși, în manualul cursantului. Întrebare pentru sală: cine a auzit PWM într-o piesă fără să-i știe numele? Toată lumea, de azi înainte."` },
    },
    ],
  },
  {
    id: '03',
    title: { en: `MODULE 03 · FILTER`, ro: `MODULUL 03 · FILTER` },
    beats: [
    {
      id: '03·01',
      title: { en: `COVER`, ro: `COVER` },
      minutes: 1,
      say: { en: `&#x201C;The oscillators gave us the block of harmonics. The filter is the chisel. It&#x27;s the most important knob on any synthesizer, and the one you&#x27;ll touch the most tonight.&#x201D;`, ro: `„Oscilatoarele ne-au dat blocul de armonice. Filtrul e dalta. E cel mai important knob de pe orice sintetizator și cel pe care o să-l atingeți cel mai mult în seara asta."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '03·02',
      title: { en: `LOW-PASS`, ro: `LOW-PASS` },
      minutes: 2,
      say: { en: `&#x201C;Low-pass means exactly what it says: what sits below a certain frequency passes, what sits above fades away. That frequency is the cutoff. Close it — darker; open it — brighter. It&#x27;s like a trumpet player&#x27;s hand over the bell: cover it and the sound turns softer, rounder, more muffled. Fully closed, nothing gets through — that&#x27;s why &#x2018;I can&#x27;t hear anything&#x2019; almost always starts at the cutoff.&#x201D;`, ro: `„Low-pass înseamnă exact ce spune: ce e sub o anumită frecvență trece, ce e deasupra se stinge. Frecvența aia e cutoff-ul. Închizi — se întunecă; deschizi — se luminează. E ca mâna trompetistului pe pâlnie: acoperă și sunetul devine mai moale, mai rotund, mai surd. Închis de tot, nu mai trece nimic — de aia «nu aud nimic» începe aproape mereu de la cutoff."` },
      demo: { en: `held chord, cutoff from open to closed and back, slowly.`, ro: `acord ținut, cutoff de la deschis la închis și înapoi, încet.` },
      room: { en: `PA · Headphones down`, ro: `PA · Căștile jos` },
    },
    {
      id: '03·03',
      title: { en: `RESONANCE`, ro: `RESONANCE` },
      minutes: 2,
      say: { en: `&#x201C;Resonance is an accent right at the cutoff. Picture a string stretched in front of a speaker: it only vibrates on its own when you hear its note — that&#x27;s resonance. A little gives focus and a vowel-like character when you move the cutoff: eee-yah-ooo-uuu&#x201D; (sing the sweep with the room) &#x201C;A lot makes the filter whistle alongside the note. At maximum, the filter feeds itself and produces a clean sine with no oscillator at all — like a microphone too close to a speaker. A fifth sound source.&#x201D;`, ro: `„Rezonanța e un accent exact la cutoff. Imaginați-vă o coardă întinsă în fața unei boxe: vibrează singură doar când auzi nota ei — asta e rezonanța. Puțină dă focus și un caracter de vocală când miști cutoff-ul: eee-iaa-ooo-uuu" (cânți sweep-ul cu sala) „Multă face filtrul să fluiere pe lângă notă. La maximum, filtrul se hrănește singur și scoate un sinus curat, fără niciun oscilator — ca un microfon prea aproape de boxă. A cincea sursă de sunet."` },
      demo: { en: `<strong>1:</strong> sweep with resonance at three quarters. <strong style="color:#C25010;">DEMO 2 (30 s), &#x201C;the filter becomes an oscillator&#x201D;:</strong> oscillators at zero in the mixer, resonance max, key track full → play a melody on the filter&#x27;s sine. Warning: &#x201C;it comes in sudden and loud — bring the volume down a touch first.&#x201D;`, ro: `<strong>1:</strong> sweep cu rezonanță la trei sferturi. <strong style="color:#C25010;">DEMO 2 (30 s), „filtrul devine oscilator":</strong> oscilatoarele la zero în mixer, rezonanță max, key track full → cânți o melodie pe sinusul filtrului. Avertisment: „vine brusc și tare — coborâți puțin volumul înainte."` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '03·04',
      title: { en: `KEY TRACK &amp; ENV AMOUNT`, ro: `KEY TRACK &amp; ENV AMOUNT` },
      minutes: 1,
      say: { en: `&#x201C;Two small things with a big effect. Key track: the cutoff follows the keyboard — higher notes get a more open filter, the way acoustic instruments behave; without it, the top notes vanish behind the filter. Hold KEY TRACK and choose with SELECT: quarter, half, full. With full tracking, the self-playing filter plays a tuned scale. And ENV AMT: how much the filter envelope moves the cutoff over the life of the note — plus or minus, with zero at twelve o&#x27;clock. That&#x27;s the story of the next module.&#x201D;`, ro: `„Două lucruri mici, cu efect mare. Key track: cutoff-ul urmează claviatura — notele de sus primesc un filtru mai deschis, cum fac instrumentele acustice; fără el, notele de sus dispar în spatele filtrului. Se ține KEY TRACK apăsat și se alege cu SELECT: sfert, jumătate, întreg. Cu tracking întreg, filtrul care cântă singur cântă o gamă acordată. Și ENV AMT: cât de mult mișcă anvelopa de filtru cutoff-ul pe durata notei — plus sau minus, cu zero la ora douăsprezece. Asta e povestea modulului următor."` },
      demo: { en: `<strong>Optional (20 s), &#x201C;a kick from nothing&#x201D;:</strong> same as before + filter env with a short decay → a kick drum out of the filter.`, ro: `<strong>opțional (20 s), „kick din nimic":</strong> la fel ca înainte + filter env cu decay scurt → o tobă mare din filtru.` },
    },
    {
      id: '03·05',
      title: { en: `TRY IT`, ro: `TRY IT` },
      minutes: 3,
      say: { en: `&#x201C;Headphones on. Hold a chord. Cutoff slowly down until it&#x27;s dark, then back. Resonance to three o&#x27;clock and one more sweep: the whistle rides the sweep. Now, careful: bring MAIN down a little, resonance to maximum, close the cutoff a bit and play single notes — the filter sings on its own. Hold KEY TRACK, turn SELECT to Full and hear the top notes light up. To finish: resonance back to nine o&#x27;clock, cutoff to twelve — we keep this for the next module. Swap in the middle.&#x201D;`, ro: `„Căștile sus. Țineți un acord. Cutoff încet în jos până e întunecat, apoi înapoi. Rezonanța la ora trei și încă un sweep: fluieratul călărește sweep-ul. Acum, atenție: coborâți puțin MAIN, rezonanța la maximum, închideți cutoff-ul un pic și cântați note simple — filtrul cântă singur. Țineți KEY TRACK, rotiți SELECT la Full și ascultați cum notele de sus se luminează. La final: rezonanța înapoi la ora nouă, cutoff la ora douăsprezece — păstrăm asta pentru modulul următor. Schimbați la mijloc."` },
      theyDo: { en: `(A) <strong>cutoff</strong> down → up; <strong>resonance</strong> at 3 o&#x27;clock, sweep. Swap. (B) <strong>main</strong> slightly down → <strong>resonance</strong> max → <strong>cutoff</strong> a bit closed → single notes; hold <strong>key track</strong> + <strong>select</strong> → Full; then <strong>resonance</strong> to 9 o&#x27;clock, <strong>cutoff</strong> to 12 o&#x27;clock.`, ro: `(A) <strong>cutoff</strong> jos → sus; <strong>resonance</strong> la 3 o&#x27;clock, sweep. Swap. (B) <strong>main</strong> puțin jos → <strong>resonance</strong> max → <strong>cutoff</strong> puțin închis → note simple; hold <strong>key track</strong> + <strong>select</strong> → Full; apoi <strong>resonance</strong> la 9 o&#x27;clock, <strong>cutoff</strong> la 12 o&#x27;clock.` },
      room: { en: `You walk the tables`, ro: `Umbli printre mese` },
    },
    {
      id: '03·06',
      title: { en: `KEY TERMS`, ro: `KEY TERMS` },
      minutes: 1,
      say: { en: `&#x201C;Cutoff, resonance, self-oscillation, key track, env amount. Five words you&#x27;ll use on every synth in the world. And a line worth remembering: run a Moog oscillator through a Korg filter and it sounds like a Korg — the filter carries the identity.&#x201D;`, ro: `„Cutoff, rezonanță, auto-oscilație, key track, env amount. Cinci cuvinte pe care le veți folosi la orice synth din lume. Și o replică de ținut minte: pui un oscilator de Moog printr-un filtru de Korg și sună a Korg — filtrul dă identitatea."` },
    },
    ],
  },
  {
    id: '04',
    title: { en: `MODULE 04 · ENVELOPES`, ro: `MODULUL 04 · ENVELOPES` },
    beats: [
    {
      id: '04·01',
      title: { en: `COVER`, ro: `COVER` },
      minutes: 1,
      say: { en: `&#x201C;An oscillator through a filter is still a beep: it starts when you press, stops when you let go, and nothing happens in between. Real instruments have a shape in time. An organ starts and stops instantly. A plucked string starts loud and dies away. A bow swells into the note. The envelope is that shape, drawn with four knobs and replayed on every key.&#x201D;`, ro: `„Un oscilator printr-un filtru e încă un bip: pornește când apeși, se oprește când dai drumul, și între ele nu se întâmplă nimic. Instrumentele adevărate au o formă în timp. Orga pornește și se oprește instant. O coardă ciupită pornește tare și se stinge. Un arcuș umflă nota. Anvelopa e forma aia, desenată din patru knob-uri și recântată la fiecare clapă."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '04·02',
      title: { en: `ADSR`, ro: `ADSR` },
      minutes: 2,
      say: { en: `&#x201C;Imagine turning a stereo&#x27;s volume knob over the course of a single note: from zero to ten, then down to five, hold it there, and at the end back to zero. That drawing is the envelope. Attack: how long the climb from silence to the peak takes. Decay: how long the fall from the peak to the sustain level takes. Sustain: a level, not a time — where the sound sits while you hold the key. Release: how long the fade takes after you lift your finger. The brain recognizes an instrument from the first milliseconds: the attack matters most.&#x201D;`, ro: `„Imaginați-vă că rotiți volumul unei combine pe durata unei singure note: de la zero la zece, apoi cobori la cinci, ții acolo, iar la final la zero. Desenul acela e anvelopa. Attack: cât durează urcarea de la liniște la vârf. Decay: cât durează coborârea de la vârf la nivelul de sustain. Sustain: un nivel, nu un timp — unde stă sunetul cât ții clapa. Release: cât durează stingerea după ce ai luat degetul. Creierul recunoaște un instrument din primele milisecunde: attack-ul contează cel mai mult."` },
      demo: { en: `the same note with zero attack, then a long attack; then short vs long release.`, ro: `aceeași notă cu attack zero, apoi cu attack lung; apoi release scurt vs lung.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '04·03',
      title: { en: `TWO ENVELOPES ON FOURM`, ro: `TWO ENVELOPES ON FOURM` },
      minutes: 1,
      say: { en: `&#x201C;The Fourm has two. The amp envelope drives the amplifier: the note&#x27;s volume contour. The filter envelope drives the cutoff, by however much ENV AMT in the filter section allows: the brightness contour. Same shape, two jobs: how loud, how bright. Watch out for ENV AMT: it&#x27;s bipolar, zero at twelve o&#x27;clock, plus to the right, minus to the left. Left at twelve, the filter envelope does nothing — the classic trap.&#x201D;`, ro: `„Pe Fourm sunt două. Amp envelope conduce amplificatorul: conturul de volum al notei. Filter envelope conduce cutoff-ul, în măsura dată de ENV AMT din secțiunea filtrului: conturul de strălucire. Aceeași formă, două slujbe: cât de tare, cât de luminos. Atenție la ENV AMT: e bipolar, zero la ora douăsprezece, plus spre dreapta, minus spre stânga. Lăsat la ora douăsprezece, anvelopa de filtru nu face nimic — capcana clasică."` },
      demo: { en: `<strong>&#x201C;the pluck knob&#x201D; (30 s):</strong> saw, cutoff at half, env amt at three o&#x27;clock, filter decay from long to short — &#x201C;the shorter the decay, the harder the sound plucks.&#x201D;`, ro: `<strong>„the pluck knob" (30 s):</strong> saw, cutoff la jumătate, env amt la ora trei, filter decay de la lung la scurt — „cu cât decay-ul e mai scurt, cu atât sunetul ciupește mai tare."` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '04·04',
      title: { en: `BASS vs PAD`, ro: `BASS vs PAD` },
      minutes: 1,
      say: { en: `&#x201C;The same oscillators, two instruments. Bass: instant attack, short decay, low sustain, short release — a pluck that bites. Pad: slow attack, no decay, sustain at maximum, long release — a sound that blooms. And three kitchen rules: with sustain at maximum, the decay has nowhere left to fall and does nothing; with sustain at zero, the note dies while you hold it — that&#x27;s the pluck; a filter envelope slower than the amp envelope gives you the pad that opens up — the other way around you hear nothing, because the amplifier closes first.&#x201D;`, ro: `„Aceleași oscilatoare, două instrumente. Bass: attack instant, decay scurt, sustain jos, release scurt — un pluck care mușcă. Pad: attack lent, fără decay, sustain la maximum, release lung — un sunet care înflorește. Și trei reguli de bucătărie: sustain la maximum, decay-ul nu mai are unde cădea și nu face nimic; sustain la zero, nota moare cât o ții — asta e pluck-ul; anvelopa de filtru mai lentă decât cea de amp dă pad-ul care se deschide — invers nu auzi nimic, pentru că amplificatorul se închide primul."` },
    },
    {
      id: '04·05',
      title: { en: `TRY IT`, ro: `TRY IT` },
      minutes: 5,
      say: { en: `&#x201C;Headphones on. Partner A builds the bass, B builds the pad, then show each other. Bass, from the module 2 sound: amp envelope — attack zero, decay ten o&#x27;clock, sustain eight o&#x27;clock, release eight o&#x27;clock. Filter envelope — attack zero, decay ten o&#x27;clock, sustain minimum, release eight o&#x27;clock. In the filter: ENV AMT to three o&#x27;clock — from twelve toward the right! — and cutoff at nine o&#x27;clock. Short notes, low. Then shorten the filter decay: more pluck. Pad, partner B: amp envelope — attack twelve o&#x27;clock, decay zero, sustain maximum, release two o&#x27;clock. Cutoff at twelve o&#x27;clock, ENV AMT at ten o&#x27;clock. Osc B on saw, octave zero, FREQUENCY nudged a little. Hold a chord and let it bloom. The positions are starting points, not rules — listen.&#x201D;`, ro: `„Căștile sus. Partenerul A face bass-ul, B face pad-ul, apoi vă arătați unul altuia. Bass, din sunetul de la modulul 2: amp envelope — attack zero, decay ora zece, sustain ora opt, release ora opt. Filter envelope — attack zero, decay ora zece, sustain minim, release ora opt. În filtru: ENV AMT la ora trei — de la douăsprezece spre dreapta! — și cutoff la ora nouă. Note scurte, jos. Apoi scurtați decay-ul filtrului: mai mult pluck. Pad, partenerul B: amp envelope — attack ora douăsprezece, decay zero, sustain maxim, release ora două. Cutoff la ora douăsprezece, ENV AMT la ora zece. Osc B pe saw, octava zero, FREQUENCY puțin mișcat. Țineți un acord și lăsați-l să înflorească. Pozițiile sunt puncte de plecare, nu reguli — ascultați."` },
      theyDo: { en: `(A) BASS: AMP ENV <strong>attack</strong> 0 · <strong>decay</strong> 10 o&#x27;clock · <strong>sustain</strong> 8 o&#x27;clock · <strong>release</strong> 8 o&#x27;clock; FILTER ENV <strong>attack</strong> 0 · <strong>decay</strong> 10 o&#x27;clock · <strong>sustain</strong> min · <strong>release</strong> 8 o&#x27;clock; FILTER <strong>env amt</strong> 3 o&#x27;clock · <strong>cutoff</strong> 9 o&#x27;clock; short notes; then FILTER ENV <strong>decay</strong> shorter. Swap. (B) PAD: AMP ENV <strong>attack</strong> 12 o&#x27;clock · <strong>decay</strong> 0 · <strong>sustain</strong> max · <strong>release</strong> 2 o&#x27;clock; FILTER <strong>cutoff</strong> 12 o&#x27;clock · <strong>env amt</strong> 10 o&#x27;clock; OSC B <strong>saw</strong> on, octave 0, <strong>frequency</strong> slightly off-centre; hold a chord. Note the positions you liked in the student handbook, page 04.`, ro: `(A) BASS: AMP ENV <strong>attack</strong> 0 · <strong>decay</strong> 10 o&#x27;clock · <strong>sustain</strong> 8 o&#x27;clock · <strong>release</strong> 8 o&#x27;clock; FILTER ENV <strong>attack</strong> 0 · <strong>decay</strong> 10 o&#x27;clock · <strong>sustain</strong> min · <strong>release</strong> 8 o&#x27;clock; FILTER <strong>env amt</strong> 3 o&#x27;clock · <strong>cutoff</strong> 9 o&#x27;clock; note scurte; apoi FILTER ENV <strong>decay</strong> mai scurt. Swap. (B) PAD: AMP ENV <strong>attack</strong> 12 o&#x27;clock · <strong>decay</strong> 0 · <strong>sustain</strong> max · <strong>release</strong> 2 o&#x27;clock; FILTER <strong>cutoff</strong> 12 o&#x27;clock · <strong>env amt</strong> 10 o&#x27;clock; OSC B <strong>saw</strong> on, octave 0, <strong>frequency</strong> ușor off-centre; acord ținut. Notează în manualul cursantului, la pagina 04, pozițiile care ți-au plăcut.` },
      room: { en: `You walk the tables, one ear on every station`, ro: `Umbli printre mese, cu urechea la fiecare stație` },
    },
    {
      id: '04·06',
      title: { en: `KEY TERMS`, ro: `KEY TERMS` },
      minutes: 1,
      say: { en: `&#x201C;Attack, decay, sustain, release, env amount, velocity. The envelope is what makes a synth sound like an instrument instead of a signal. And the beautiful part: four knobs describe almost every instrument on Earth.&#x201D;`, ro: `„Attack, decay, sustain, release, env amount, velocity. Anvelopa e ce face un synth să sune a instrument, nu a semnal. Și partea frumoasă: patru knob-uri descriu aproape orice instrument de pe lume."` },
    },
    ],
  },
  {
    id: '05',
    title: { en: `MODULE 05 · LFO &amp; MODULATION`, ro: `MODULUL 05 · LFO &amp; MODULATION` },
    beats: [
    {
      id: '05·01',
      title: { en: `COVER`, ro: `COVER` },
      minutes: 1,
      say: { en: `&#x201C;Envelopes give the note its shape; modulation keeps it alive. A sound that stands still sounds like a signal — every sound in nature moves. Modulation is the verb of synthesis: something moves something else.&#x201D;`, ro: `„Anvelopele dau formei notei; modulația o ține în viață. Un sunet care stă pe loc sună a semnal — orice sunet din natură se mișcă. Modulația e verbul sintezei: ceva mișcă altceva."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '05·02',
      title: { en: `THE LFO`, ro: `THE LFO` },
      minutes: 2,
      say: { en: `&#x201C;LFO: low frequency oscillator. An oscillator too slow to hear as a note — you hear what it moves. Sent to pitch: vibrato, the violinist rocking a finger on the string. Sent to cutoff: wah. Sent to the amplifier: tremolo — the volume rocked twice a second. The FREQUENCY knob is the speed, SYNC ties it to the tempo, and the shapes can be combined: triangle for smooth vibrato, square for trills, sample and hold for random, stepped motion. Musical vibrato is small and about six or seven times a second; speed it up and it&#x27;s not vibrato anymore, it&#x27;s a growl.&#x201D;`, ro: `„LFO: low frequency oscillator. Un oscilator prea lent ca să-l auzi ca notă — auzi ce mișcă. Trimis la pitch: vibrato, violonistul care își leagănă degetul pe coardă. Trimis la cutoff: wah. Trimis la amplificator: tremolo — volumul legănat de două ori pe secundă. Knob-ul FREQUENCY e viteza, SYNC îl leagă de tempo, iar formele se pot combina: triangle pentru vibrato lin, square pentru triluri, sample and hold pentru mișcare aleatoare, în trepte. Vibrato-ul muzical e mic și cam de șase-șapte ori pe secundă; îl grăbești și nu mai e vibrato, e mârâit."` },
      demo: { en: `<strong>(45 s):</strong> one LFO → cutoff, FREQUENCY from very slow (ambient sweep) to 1–2 Hz (wah) to 15 Hz (growl); then the same LFO → pitch (vibrato) → amp (tremolo).`, ro: `<strong>(45 s):</strong> un LFO → cutoff, cu FREQUENCY de la foarte lent (sweep ambiental) la 1–2 Hz (wah) la 15 Hz (growl); apoi același LFO → pitch (vibrato) → amp (tremolo).` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '05·03',
      title: { en: `THE MODULATION SECTION`, ro: `THE MODULATION SECTION` },
      minutes: 2,
      say: { en: `&#x201C;Look at the left side of the panel. Three sources: filter env, osc B, and the LFO, each with a ROUTE button and an amount knob. Eight destinations on the right: freq A, freq B, PW A, PW B, cutoff, amp, LFO freq, LFO amount. Press ROUTE once — red LED, the direct bus: the modulation is always on. Press it twice — blue, the wheel bus: the modulation only appears as you raise the mod wheel. The wheel becomes the modulation&#x27;s volume — without it, a vibrato would be permanently on, which isn&#x27;t musical. Destinations work the same: one press, red; two, blue; three, both — purple. And the trap of the evening, once more: the amount knobs are bipolar, zero at twelve o&#x27;clock. Nothing happening? Turn from twelve toward the right.&#x201D;`, ro: `„Uitați-vă în stânga panoului. Trei surse: filter env, osc B și LFO-ul, fiecare cu un buton ROUTE și un knob de amount. Opt destinații în dreapta: freq A, freq B, PW A, PW B, cutoff, amp, LFO freq, LFO amount. Apeși ROUTE o dată — LED roșu, bus-ul direct: modulația e mereu pornită. Apeși de două ori — albastru, bus-ul roții: modulația apare doar când ridici mod wheel-ul. Roata devine volumul modulației — fără ea, un vibrato ar fi mereu pornit, ceea ce nu e muzical. La destinații la fel: o apăsare, roșu; două, albastru; trei, ambele — mov. Și capcana serii, încă o dată: knob-urile de amount sunt bipolare, zero la ora douăsprezece. Nu se întâmplă nimic? Rotește de la douăsprezece spre dreapta."` },
      demo: { en: `vibrato on the wheel, ROUTE and destinations on blue; raise the wheel slowly.`, ro: `vibrato pe wheel, cu ROUTE și destinațiile pe albastru; ridici roata încet.` },
    },
    {
      id: '05·04',
      title: { en: `TRY IT`, ro: `TRY IT` },
      minutes: 3,
      say: { en: `&#x201C;Headphones on, on the pad from module four. In the LFO: TRIANGLE, FREQUENCY at ten o&#x27;clock. In Modulation: the ROUTE under LFO twice — blue. FREQ A and FREQ B twice each — blue. Turn the LFO&#x27;s AMOUNT from twelve toward the right until you hear it, then push the mod wheel: vibrato under your control. Swap. Partner: press FREQ A and FREQ B until they go dark, press PW A twice — the pulse breathes. Then CUTOFF twice — wah. Faster, more: go too far, then bring it back.&#x201D;`, ro: `„Căștile sus, pe pad-ul de la modulul patru. În LFO: TRIANGLE, FREQUENCY la ora zece. În Modulation: ROUTE de sub LFO de două ori — albastru. FREQ A și FREQ B de două ori fiecare — albastru. Rotiți AMOUNT-ul LFO-ului de la douăsprezece spre dreapta până auziți, apoi împingeți mod wheel-ul: vibrato pe care îl controlați voi. Schimbați. Partenerul: apăsați FREQ A și FREQ B până se sting, apăsați PW A de două ori — pulsul respiră. Apoi CUTOFF de două ori — wah. Mai repede, mai mult: mergeți prea departe, apoi aduceți înapoi."` },
      theyDo: { en: `(A) LFO <strong>triangle</strong> on, <strong>frequency</strong> 10 o&#x27;clock → MOD: <strong>route</strong> (lfo) ×2 = blue → <strong>freq a</strong> ×2, <strong>freq b</strong> ×2 = blue → <strong>lfo</strong> amount from 12 o&#x27;clock to the right → mod wheel up. Swap. (B) <strong>freq a</strong>/<strong>freq b</strong> until dark → <strong>pw a</strong> ×2 → plays; then <strong>cutoff</strong> ×2 → <strong>frequency</strong> and amount higher, then back.`, ro: `(A) LFO <strong>triangle</strong> on, <strong>frequency</strong> 10 o&#x27;clock → MOD: <strong>route</strong> (lfo) ×2 = albastru → <strong>freq a</strong> ×2, <strong>freq b</strong> ×2 = albastru → <strong>lfo</strong> amount de la 12 o&#x27;clock spre dreapta → mod wheel sus. Swap. (B) <strong>freq a</strong>/<strong>freq b</strong> până se sting → <strong>pw a</strong> ×2 → cântă; apoi <strong>cutoff</strong> ×2 → <strong>frequency</strong> și amount mai sus, apoi înapoi.` },
      room: { en: `You walk the tables, checking LED colors`, ro: `Umbli printre mese, verifici culorile LED-urilor` },
    },
    {
      id: '05·05',
      title: { en: `KEY TERMS`, ro: `KEY TERMS` },
      minutes: 1,
      say: { en: `&#x201C;LFO, rate, vibrato, tremolo, PWM, modulation bus, mod wheel. And a promise kept: the PWM from module two — you just made it with your own hands.&#x201D;`, ro: `„LFO, rate, vibrato, tremolo, PWM, bus de modulație, mod wheel. Și o promisiune ținută: PWM-ul din modulul doi tocmai l-ați făcut cu mâna voastră."` },
    },
    ],
  },
  {
    id: '06',
    title: { en: `MODULE 06 · VOICES &amp; UNISON`, ro: `MODULUL 06 · VOICES &amp; UNISON` },
    beats: [
    {
      id: '06·01',
      title: { en: `COVER`, ro: `COVER` },
      minutes: 1,
      say: { en: `&#x201C;So far we&#x27;ve built one voice. The Fourm has four — each with its own oscillators, filter and envelopes. This module is about how we spend them: spread across a chord, stacked onto one huge note, or replayed as a memorized chord from a single key. And about the loop that fattens everything.&#x201D;`, ro: `„Până acum am construit o voce. Fourm are patru — fiecare cu oscilatoarele, filtrul și anvelopele ei. Modulul ăsta e despre cum le cheltuim: întinse pe un acord, stivuite pe o singură notă uriașă, sau recântate ca un acord memorat dintr-o singură clapă. Și despre bucla care îngroașă tot."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '06·02',
      title: { en: `POLYPHONY`, ro: `POLYPHONY` },
      minutes: 1,
      say: { en: `&#x201C;A mono synth plays one note at a time. The Fourm plays four; the fifth steals the oldest. A ten-second story: the Oberheim Four Voice, 1975, was literally four monosynths bolted into a wooden box — and in unison, one of the most overwhelming monosynths ever made. The Fourm is the same idea, in a four-kilogram box. HOLD sustains up to four notes even after your hands leave.&#x201D;`, ro: `„Un mono synth cântă o notă odată. Fourm cântă patru; a cincea o fură pe cea mai veche. Poveste de zece secunde: Oberheim Four Voice, 1975, era literalmente patru monosynth-uri înșurubate într-o cutie de lemn — și în unison, unul dintre cele mai copleșitoare monosynth-uri făcute vreodată. Fourm e aceeași idee, într-o cutie de patru kilograme. HOLD ține până la patru note și după ce iei mâinile."` },
      demo: { en: `five notes, you hear the steal; then HOLD.`, ro: `cinci note, se aude furtul; apoi HOLD.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '06·03',
      title: { en: `UNISON`, ro: `UNISON` },
      minutes: 2,
      say: { en: `&#x201C;Unison: every chosen voice — from one to four, hold UNISON and turn SELECT — on a single note. The Fourm goes monophonic and, with four voices, huge. On its own it&#x27;s just louder; the magic is the detune: parameter ten, Unison Detune, a few cents between the voices and the tone turns wide, alive, pulsing. When it sounds huge, pull it back ten percent — that&#x27;s usually where the good sound lives.&#x201D;`, ro: `„Unison: toate vocile alese — de la una la patru, ții UNISON și rotești SELECT — pe o singură notă. Fourm devine monofonic și, cu patru voci, uriaș. Singur e doar mai tare; magia e detune-ul: parametrul zece, Unison Detune, câțiva cenți între voci și tonul devine lat, viu, pulsând. Când sună uriaș, dă-l înapoi cu zece la sută — acolo stă de obicei sunetul bun."` },
      demo: { en: `unison with no detune, then detune raised slowly until it shimmers, then too far, then back.`, ro: `unison fără detune, apoi detune crescut încet până sclipește, apoi prea mult, apoi înapoi.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '06·04',
      title: { en: `CHORD MEMORY`, ro: `CHORD MEMORY` },
      minutes: 1,
      say: { en: `&#x201C;Hold a chord, memorize it, and from then on every key plays the whole chord, transposed. One finger, full harmony — for chord stabs it&#x27;s gold. It saves with the program. This is how the rave stabs of the early nineties were played: one finger on a synth with chord memory, and the whole hall thought it was a keyboard player.&#x201D;`, ro: `„Ține un acord, memorează-l, și de-acum orice clapă cântă tot acordul, transpus. Un deget, armonie completă — pentru chord stabs e aur. Se salvează cu programul. Așa se cântau stab-urile de rave la începutul anilor nouăzeci: un deget pe un synth cu chord memory, și toată sala credea că e un clăpar."` },
      demo: { en: `<strong>at the presenter&#x27;s synth, with the real steps:</strong> (UNISON → SELECT to the middle row → Chord → UNISON → hold the chord → UNISON): memorize a minor chord and walk it chromatically with one finger. Participants just listen — the steps are in the student handbook, under Level 2.`, ro: `<strong>la prezentator, cu pașii reali:</strong> (UNISON → SELECT la rândul din mijloc → Chord → UNISON → ține acordul → UNISON): memorezi un acord minor și îl plimbi cromatic cu un deget. Participanții doar ascultă — pașii sunt în manualul cursantului, la Level 2.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '06·05',
      title: { en: `FEEDBACK`, ro: `FEEDBACK` },
      minutes: 1,
      say: { en: `&#x201C;The promise from module one: the loop. A mixer channel feeds the Fourm&#x27;s output back into the mix, with soft-clipping diodes along the way. Press FEEDBACK — it comes in at one hundred —, hold and turn SELECT for the amount. A little means warmth, a lot means snarl. Unison plus feedback is the biggest bass the Fourm can make. This started as a hack: on the Minimoog people took a cable out of the headphone socket and back into the external input, so the instrument overdrove its own mixer. Half a century later, the Fourm has that loop built in — with the diodes that keep it thick instead of screaming.&#x201D;`, ro: `„Promisiunea din modulul unu: bucla. Un canal din mixer întoarce ieșirea lui Fourm înapoi în mix, cu diode de soft-clipping pe drum. Apeși FEEDBACK — intră la o sută —, ții și rotești SELECT pentru cantitate. Puțin înseamnă căldură, mult înseamnă mârâit. Unison plus feedback e cel mai mare bass pe care îl scoate Fourm. Trucul a început ca un hack: pe Minimoog lumea scotea un cablu din ieșirea de căști și îl băga în intrarea externă, ca instrumentul să își satureze propriul mixer. Jumătate de secol mai târziu, Fourm are bucla asta integrată — cu diodele care o țin groasă în loc să o lase să țipe."` },
      demo: { en: `on a held bass, feedback from clean to aggressive and back. <strong style="color:#C25010;">Optional (30 s):</strong> &#x201C;Glass Echo&#x201D;, F1 17 — self-oscillating filter + feedback: a tuned echo appears on the release.`, ro: `pe un bass ținut, feedback de la curat la agresiv și înapoi. <strong style="color:#C25010;">Opțional (30 s):</strong> „Glass Echo", F1 17 — filtru auto-oscilant + feedback: un ecou acordat apare la release.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '06·06',
      title: { en: `TRY IT`, ro: `TRY IT` },
      minutes: 2,
      say: { en: `&#x201C;Headphones on. Play five notes at once and count what you hear. Hold UNISON, SELECT to four voices, play a line: one huge note. Press PARAM, go to ten — Unison Detune —, press SELECT, turn to about forty, PROGRAM to exit: the tone widens. Press FEEDBACK, hold and turn SELECT down to sixty: snarl without chaos. Swap: your partner turns unison off, plays a chord, presses HOLD and lifts both hands.&#x201D;`, ro: `„Căștile sus. Cântați cinci note deodată și numărați ce auziți. Țineți UNISON, SELECT la patru voci, cântați o linie: o singură notă uriașă. Apăsați PARAM, mergeți la zece — Unison Detune —, apăsați SELECT, rotiți la vreo patruzeci, PROGRAM ca să ieșiți: tonul se lățește. Apăsați FEEDBACK, țineți și rotiți SELECT în jos până la șaizeci: mârâit fără haos. Schimbați: partenerul scoate unison-ul, cântă un acord, apasă HOLD și ridică mâinile."` },
      theyDo: { en: `(A) 5 notes → hold <strong>unison</strong> + <strong>select</strong> = 4 → line → <strong>param</strong> → 10 → press <strong>select</strong> → ~40 → <strong>program</strong> → <strong>feedback</strong> on → hold <strong>feedback</strong> + <strong>select</strong> → ~60. Swap. (B) <strong>unison</strong> off → chord → <strong>hold</strong> → hands up.`, ro: `(A) 5 note → hold <strong>unison</strong> + <strong>select</strong> = 4 → linie → <strong>param</strong> → 10 → press <strong>select</strong> → ~40 → <strong>program</strong> → <strong>feedback</strong> on → hold <strong>feedback</strong> + <strong>select</strong> → ~60. Swap. (B) <strong>unison</strong> off → acord → <strong>hold</strong> → mâinile sus.` },
      room: { en: `You walk the tables`, ro: `Umbli printre mese` },
    },
    {
      id: '06·07',
      title: { en: `KEY TERMS`, ro: `KEY TERMS` },
      minutes: 1,
      say: { en: `&#x201C;Polyphony, voice, unison, detune in cents, chord memory, hold, feedback, soft clipping. The practical advice, once more: after it sounds big, pull everything back ten percent.&#x201D;`, ro: `„Polifonie, voce, unison, detune în cenți, chord memory, hold, feedback, soft clipping. Sfatul practic, încă o dată: după ce sună mare, dă totul înapoi cu zece la sută."` },
    },
    ],
  },
  {
    id: '07',
    title: { en: `MODULE 07 · EXPRESSION`, ro: `MODULUL 07 · EXPRESSION` },
    beats: [
    {
      id: '07·01',
      title: { en: `COVER`, ro: `COVER` },
      minutes: 1,
      say: { en: `&#x201C;Until now we&#x27;ve been building the sound; from here on we play it. Envelopes and LFOs make every note the same; what turns that into music is what your hands add. Velocity reads how fast you strike, aftertouch reads how hard you keep pressing, glide ties the notes together. The Fourm&#x27;s Tactive keyboard feels the pressure under each individual key.&#x201D;`, ro: `„Până acum am construit sunetul; de aici încolo îl cântăm. Anvelopele și LFO-urile fac fiecare notă la fel; ce face din asta muzică e ce adaugă mâinile voastre. Velocity citește cât de repede lovești, aftertouch citește cât de tare continui să apeși, glide leagă notele. Claviatura Tactive a lui Fourm simte presiunea sub fiecare clapă în parte."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '07·02',
      title: { en: `VELOCITY`, ro: `VELOCITY` },
      minutes: 1,
      say: { en: `&#x201C;On real instruments, louder notes also carry more harmonics — that&#x27;s why velocity goes to the filter, not just the volume. Each envelope has a VELOCITY button: press it and how hard you play scales that envelope&#x27;s depth. Velocity on the filter envelope: soft stays dark, hard bites. Five response curves in Global, from Soft+ to Hard+, match the keyboard to your touch.&#x201D;`, ro: `„La instrumentele reale, notele mai tari au și mai multe armonice — de aia velocity merge la filtru, nu doar la volum. Fiecare anvelopă are un buton VELOCITY: îl apeși și cât de tare cânți scalează adâncimea anvelopei aceleia. Velocity pe filter envelope: moale rămâne întunecat, tare mușcă. Cinci curbe de răspuns în Global, de la Soft+ la Hard+, potrivesc claviatura cu tușeul vostru."` },
      demo: { en: `the same phrase pianissimo, then forte, with velocity on the filter.`, ro: `aceeași frază pianissimo, apoi forte, cu velocity pe filtru.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '07·03',
      title: { en: `POLY AFTERTOUCH`, ro: `POLY AFTERTOUCH` },
      minutes: 1,
      say: { en: `&#x201C;The Fourm&#x27;s signature. After the note is down, extra pressure becomes a continuous modulator, on every key. Press into a single note of a chord and only that one blooms — like blowing harder into a flute: louder, brighter. On most keyboards aftertouch is mono, it moves all the voices at once; per-note was a rarity — the Yamaha CS-80, the Prophet T8 — and the Fourm has it natively.&#x201D;`, ro: `„Semnătura lui Fourm. După ce nota e jos, presiunea în plus devine un modulator continuu, pe fiecare clapă. Apeși într-o singură notă dintr-un acord și doar ea înflorește — ca și cum ai sufla mai tare într-un flaut: mai tare, mai luminos. La majoritatea claviaturilor aftertouch-ul e mono, mișcă toate vocile deodată; per notă era o raritate — Yamaha CS-80, Prophet T8 — și Fourm îl are nativ."` },
      demo: { en: `held chord, press into each note in turn.`, ro: `acord ținut, apeși pe rând în fiecare notă.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '07·04',
      title: { en: `PRESSURE ROUTING`, ro: `PRESSURE ROUTING` },
      minutes: 1,
      say: { en: `&#x201C;Where you send the pressure: six destinations — freq A, freq B, filt, amp, LFO freq, LFO amount —, chosen with the three DEST buttons, two per button, and a single AMOUNT knob, plus or minus. Cutoff is the classic: press for brightness, let go to relax; with negative amount, it closes. Pitch is for the brave.&#x201D;`, ro: `„Unde trimiți presiunea: șase destinații — freq A, freq B, filt, amp, LFO freq, LFO amount —, alese cu cele trei butoane DEST, câte două pe buton, și un singur knob AMOUNT, plus sau minus. Cutoff e clasicul: apeși pentru strălucire, lași ca să se relaxeze; cu amount negativ, se închide. Pitch e pentru curajoși."` },
      demo: { en: `switch the destination live between filt and freq. <span style="background:#FFF3E8; padding:1px 4px;">[TEST AT HOME, before the workshop: AT → LFO amount on a single note of a chord — does only that note vibrate (per voice, as the Sequential developer says) or all of them (as the manual says)? If it&#x27;s per voice, add a line here: &#x201C;and a bend under one finger, via LFO amount&#x201D;.]</span>`, ro: `schimbi destinația live între filt și freq. <span style="background:#FFF3E8; padding:1px 4px;">[DE TESTAT ACASĂ, înainte de workshop: AT → LFO amount pe o singură notă dintr-un acord — vibrează doar ea (per voce, cum spune developerul Sequential) sau toate (cum spune manualul)? Dacă e per voce, adaugă aici o frază: „și bend pe deget, prin LFO amount".]</span>` },
    },
    {
      id: '07·05',
      title: { en: `GLIDE`, ro: `GLIDE` },
      minutes: 1,
      say: { en: `&#x201C;Glide, or portamento: the pitch slides from the previous note to the next instead of jumping. Press GLIDE and set the RATE — on with rate at zero it does nothing. Subtle almost always sounds more musical than spectacular: it&#x27;s the difference between a keyboard melody and a phrase that sounds like a voice.&#x201D;`, ro: `„Glide, sau portamento: pitch-ul alunecă de la nota anterioară la următoarea în loc să sară. Apeși GLIDE și setezi RATE — pornit cu rate pe zero nu face nimic. Subtil sună aproape mereu mai muzical decât spectaculos: e diferența dintre o melodie de claviatură și o frază care sună a voce."` },
      demo: { en: `the same bass phrase without glide, then with. &#x201C;The modes — four of them — are in the student handbook.&#x201D;`, ro: `aceeași frază de bass fără glide, apoi cu glide. „Modurile — patru — sunt în manualul cursantului."` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '07·06',
      title: { en: `TRY IT`, ro: `TRY IT` },
      minutes: 2,
      say: { en: `&#x201C;Headphones on. In FILTER ENVELOPE press VELOCITY; play soft, then hard. In AFTERTOUCH: press the DEST button under FILT/AMP until only FILT stays lit, AMOUNT at two o&#x27;clock; hold a three-note chord and press into the top note only. Now AMOUNT at ten o&#x27;clock: pressure closes the filter. Swap. Partner: GLIDE on, RATE at ten o&#x27;clock, a bass line — the notes slide. Then move the pressure to FREQ A and FREQ B, with a small amount: a bend, under one finger.&#x201D;`, ro: `„Căștile sus. În FILTER ENVELOPE apăsați VELOCITY; cântați moale, apoi tare. În AFTERTOUCH: apăsați butonul DEST de sub FILT/AMP până rămâne aprins doar FILT, AMOUNT la ora două; țineți un acord de trei note și apăsați doar în nota de sus. Acum AMOUNT la ora zece: presiunea închide filtrul. Schimbați. Partenerul: GLIDE pornit, RATE la ora zece, o linie de bass — notele alunecă. Apoi mutați presiunea pe FREQ A și FREQ B, cu amount mic: un bend, pe deget."` },
      theyDo: { en: `(A) FILTER ENV <strong>velocity</strong> on → soft/hard → AFTERTOUCH <strong>dest</strong> (FILT/AMP) until only <strong>filt</strong> → <strong>amount</strong> 2 o&#x27;clock → chord, pressure on the top note → <strong>amount</strong> 10 o&#x27;clock. Swap. (B) <strong>glide</strong> on → <strong>rate</strong> 10 o&#x27;clock → bass line → <strong>dest</strong> (FREQ A/FREQ B) → small amount → bend under a finger.`, ro: `(A) FILTER ENV <strong>velocity</strong> on → moale/tare → AFTERTOUCH <strong>dest</strong> (FILT/AMP) până e doar <strong>filt</strong> → <strong>amount</strong> 2 o&#x27;clock → acord, presiune pe nota de sus → <strong>amount</strong> 10 o&#x27;clock. Swap. (B) <strong>glide</strong> on → <strong>rate</strong> 10 o&#x27;clock → linie de bass → <strong>dest</strong> (FREQ A/FREQ B) → amount mic → bend pe deget.` },
      room: { en: `You walk the tables`, ro: `Umbli printre mese` },
    },
    {
      id: '07·07',
      title: { en: `KEY TERMS`, ro: `KEY TERMS` },
      minutes: 1,
      say: { en: `&#x201C;Velocity, poly aftertouch, pressure routing, Tactive, glide, portamento, legato. Invite your partner to feel the press inside a chord: the sensation sticks better than the definition.&#x201D;`, ro: `„Velocity, poly aftertouch, pressure routing, Tactive, glide, portamento, legato. Invitați-vă partenerul să simtă apăsarea în acord: senzația se ține minte mai bine decât definiția."` },
    },
    ],
  },
  {
    id: '08',
    title: { en: `MODULE 08 · ARPEGGIATOR &amp; SEQUENCER`, ro: `MODULUL 08 · ARPEGGIATOR &amp; SEQUENCER` },
    beats: [
    {
      id: '08·01',
      title: { en: `COVER`, ro: `COVER` },
      minutes: 1,
      say: { en: `&#x201C;Patterns out of held notes: harmony becomes rhythm. And behind the arpeggiator, the Fourm hides a full sequencer. A mouse is not a musical instrument — that&#x27;s why the arpeggiator lives on the panel.&#x201D;`, ro: `„Tipare din note ținute: armonia devine ritm. Iar în spatele arpeggiator-ului, Fourm ascunde un sequencer întreg. Mouse-ul nu e instrument muzical — de aia arpeggiator-ul e pe panou."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '08·02',
      title: { en: `HOLD A CHORD`, ro: `HOLD A CHORD` },
      minutes: 1,
      say: { en: `&#x201C;Press ON, hold the chord, the synth plays the pattern: up, down, up-down, random, or in the order you pressed — across one to three octaves; hold MODE or OCTAVE and turn SELECT. HOLD keeps it running hands-free. And a trick: change how many notes you&#x27;re holding and the rhythm changes — it sounds like a mistake until you embrace it.&#x201D;`, ro: `„Apeși ON, ții acordul, synth-ul cântă tiparul: up, down, up-down, random, în ordinea în care ai apăsat — pe una până la trei octave; ții MODE sau OCTAVE și rotești SELECT. HOLD îl ține în mers cu mâinile libere. Și un truc: schimbă numărul de note pe care le ții și se schimbă ritmul — sună a greșeală până îl îmbrățișezi."` },
      demo: { en: `arp on a triad, switch directions live; then four notes, then two.`, ro: `arp pe o triadă, schimbi direcțiile live; apoi patru note, apoi două.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '08·03',
      title: { en: `CLOCK &amp; SYNC`, ro: `CLOCK &amp; SYNC` },
      minutes: 1,
      say: { en: `&#x201C;One clock drives everything: tap TAP TEMPO four times, or hold it and turn SELECT for the BPM. CLK DIV picks the grid — quarters, eighths, sixteenths, triplets — and the LFO&#x27;s SYNC follows the same clock. If the arp won&#x27;t start: Clock Mode in Global is on In, waiting for external clock.&#x201D;`, ro: `„Un singur clock conduce tot: bați de patru ori pe TAP TEMPO, sau îl ții și rotești SELECT pentru BPM. CLK DIV alege grila — pătrimi, optimi, șaisprezecimi, triolete — iar SYNC-ul LFO-ului urmează același clock. Dacă arp-ul nu pornește: Clock Mode din Global e pe In și așteaptă clock extern."` },
      demo: { en: `the same arpeggio through three divisions, without stopping the pattern.`, ro: `același arpegiu prin trei divizii, fără să oprești tiparul.` },
      room: { en: `PA`, ro: `PA` },
    },
    {
      id: '08·04',
      title: { en: `NOTE &amp; MOD SEQ`, ro: `NOTE &amp; MOD SEQ` },
      minutes: 1,
      say: { en: `&#x201C;Beyond arpeggios: up to 64 recorded steps — notes, chords, rests, legato, even glide per step —, triggered and transposed from the keyboard; or a sequence that moves a parameter instead of playing notes: cutoff, pulse width, feedback. A sequencer in disguise, and a story for another workshop.&#x201D; <strong style="color:#C25010;">The image:</strong> &#x201C;a sequencer is, at its origin, sixteen faders stepped through by a clock — the height of the faders draws the melody; that&#x27;s how &#x2018;I Feel Love&#x2019; was made.&#x201D;`, ro: `„Dincolo de arpegii: până la 64 de pași înregistrați — note, acorduri, pauze, legato, chiar glide pe fiecare pas —, declanșați și transpuși de la claviatură; sau o secvență care mișcă un parametru în loc să cânte note: cutoff, pulse width, feedback. Un sequencer deghizat, și o poveste pentru alt workshop." <strong style="color:#C25010;">Imaginea:</strong> „un sequencer e, la origine, șaisprezece fadere pășite de un clock — înălțimea faderelor desenează melodia; așa s-a făcut «I Feel Love»."` },
    },
    {
      id: '08·05',
      title: { en: `TRY IT`, ro: `TRY IT` },
      minutes: 2,
      say: { en: `&#x201C;Headphones on. Arpeggiator ON, hold C–E–G, press HOLD and lift your hands. Tap TAP TEMPO four times at your own tempo. Hold CLK DIV and turn SELECT to sixteenths, then back to eighths. Ride the CUTOFF as far as it goes. Swap. Partner: hold MODE and turn SELECT to Random; hold OCTAVE and turn SELECT to 2. Then a &#x2018;wrong&#x2019; chord, and let it repeat: give it eight bars.&#x201D;`, ro: `„Căștile sus. ON la arpeggiator, țineți do-mi-sol, apăsați HOLD și ridicați mâinile. Bateți TAP TEMPO de patru ori pe tempoul vostru. Țineți CLK DIV și rotiți SELECT la șaisprezecimi, apoi înapoi la optimi. Călăriți CUTOFF-ul cât merge. Schimbați. Partenerul: ține MODE și rotește SELECT la Random; ține OCTAVE și rotește SELECT la 2. Apoi un acord «greșit», și lăsați-l să se repete: dați-i opt bare."` },
      theyDo: { en: `(A) ARP <strong>on</strong> → C–E–G → <strong>hold</strong> → <strong>tap tempo|bpm</strong> ×4 → hold <strong>clk div</strong> + <strong>select</strong> → 1/16 → 1/8 <span style="background:#FFF3E8; padding:1px 4px;">[check at home: hold + select vs. repeated presses; it&#x27;s also Param 19]</span> → <strong>cutoff</strong>. Swap. (B) hold <strong>mode</strong> + <strong>select</strong> → Random → hold <strong>octave</strong> + <strong>select</strong> → 2 → a &#x201C;wrong&#x201D; chord, 8 bars.`, ro: `(A) ARP <strong>on</strong> → C–E–G → <strong>hold</strong> → <strong>tap tempo|bpm</strong> ×4 → hold <strong>clk div</strong> + <strong>select</strong> → 1/16 → 1/8 <span style="background:#FFF3E8; padding:1px 4px;">[verifică acasă: hold + select vs. apăsări succesive; e și Param 19]</span> → <strong>cutoff</strong>. Swap. (B) hold <strong>mode</strong> + <strong>select</strong> → Random → hold <strong>octave</strong> + <strong>select</strong> → 2 → acord „greșit", 8 bare.` },
      room: { en: `You walk the tables · leave your own arp running slowly in the background`, ro: `Umbli printre mese · lași arp-ul tău să meargă încet în fundal` },
    },
    {
      id: '08·06',
      title: { en: `KEY TERMS`, ro: `KEY TERMS` },
      minutes: 1,
      say: { en: `&#x201C;Arpeggiator, hold, clock, BPM, division, note and mod sequencer. Leave the arps running quietly while we recap: the room stays in rhythm.&#x201D;`, ro: `„Arpeggiator, hold, clock, BPM, divizie, note și mod sequencer. Lăsați arp-urile să meargă încet cât recapitulăm: sala rămâne în ritm."` },
    },
    ],
  },
  {
    id: '09',
    title: { en: `MODULE 09 · WRAP-UP · Q&amp;A · FREE PLAY`, ro: `MODULUL 09 · WRAP-UP · Q&amp;A · FREE PLAY` },
    beats: [
    {
      id: '09·01',
      title: { en: `THE ROAD, AGAIN`, ro: `THE ROAD, AGAIN` },
      minutes: 1,
      say: { en: `&#x201C;This is the road: oscillator, mixer, filter, envelopes, LFO and modulation, voices, expression, rhythm. Every synth you&#x27;ll meet from now on is the same road in different clothes. If you know the road, you know where to look.&#x201D;`, ro: `„Ăsta e drumul: oscilator, mixer, filtru, anvelope, LFO și modulație, voci, interpretare, ritm. Orice synth pe care o să-l întâlniți de acum e același drum cu alte haine. Dacă știți drumul, știți unde să căutați."` },
      room: { en: `Headphones down`, ro: `Căștile jos` },
    },
    {
      id: '09·02',
      title: { en: `CHALLENGE`, ro: `CHALLENGE` },
      minutes: 2,
      say: { en: `&#x201C;Last exercise, two minutes. From Basic Program, rebuild the bass from module four: A builds, B checks against the student handbook, page 04, then swap. When you&#x27;re done, write your settings into the student handbook — a sound on paper survives, one in memory rarely does.&#x201D;`, ro: `„Ultimul exercițiu, două minute. Din Basic Program, reconstruiți bass-ul de la modulul patru: A construiește, B verifică în manualul cursantului, la pagina 04, apoi schimbați. Când ați terminat, notați-vă pozițiile în manualul cursantului — un sunet pe hârtie supraviețuiește, unul în memorie rar."` },
      theyDo: { en: `(A) hold <strong>transpose down</strong> + <strong>program</strong> → the BASS recipe from page 04. Swap. (B) checks, then rebuilds it too.`, ro: `(A) hold <strong>transpose down</strong> + <strong>program</strong> → rețeta BASS din pagina 04. Swap. (B) verifică, apoi reconstruiește și el.` },
      room: { en: `You walk the tables`, ro: `Umbli printre mese` },
    },
    {
      id: '09·03',
      title: { en: `Q&amp;A`, ro: `Q&amp;A` },
      minutes: 5,
      say: { en: `&#x201C;Questions. Anything — from &#x2018;what&#x27;s that knob&#x2019; to &#x2018;how do I make the sound from track X&#x2019;.&#x201D; <strong style="color:#C25010;">Your moderating rule:</strong> with every answer, tie the term back to the demo where they heard it. When someone describes a sound, ask for concrete words: bright/dark, thin/fat, pluck/pad, static/moving.`, ro: `„Întrebări. Orice — de la «ce e ăla knob» la «cum fac sunetul din piesa X»." <strong style="color:#C25010;">Regula ta de moderare:</strong> la fiecare răspuns, leagă termenul de demo-ul în care l-au auzit. Când cineva descrie un sunet, cere-i cuvinte concrete: strălucitor/întunecat, subțire/gros, pluck/pad, static/în mișcare.` },
    },
    {
      id: '09·04',
      title: { en: `THANK YOU`, ro: `THANK YOU` },
      minutes: 1,
      say: { en: `&#x201C;Thank you. Zeedo, thank you for making this possible; Sequential, thank you for the instruments. On your way out you&#x27;ll get the student handbook, in English or Romanian: the same diagrams, all the theory. You&#x27;ll find us at Sintezaur — [where] — and that&#x27;s where we announce the next workshop. Until then: the synths are yours for another ten minutes.&#x201D;`, ro: `„Mulțumesc. Zeedo, mulțumim că ați făcut asta posibil; Sequential, mulțumim pentru instrumente. La plecare primiți manualul cursantului, în engleză sau română: aceleași diagrame, toată teoria. Ne găsiți la Sintezaur — [unde] — și acolo anunțăm următorul workshop. Până atunci: synth-urile sunt ale voastre încă zece minute."` },
    },
    {
      id: '09·05',
      title: { en: `FREE PLAY`, ro: `FREE PLAY` },
      minutes: 4,
      say: { en: `&#x201C;Ten free minutes. One suggestion, if you want one: a single sound, sixty seconds — starts quiet, grows, hits a peak, comes down. The cutoff and the resonance are the story.&#x201D; You walk the tables, going to raised hands; group photo at the end.`, ro: `„Zece minute libere. O propunere, dacă vreți una: un singur sunet, șaizeci de secunde — pornește încet, crește, atinge un vârf, coboară. Cutoff-ul și rezonanța sunt povestea." Tu printre mese, la cine ridică mâna; foto de grup la final.` },
    },
    ],
  },
];


/**
 * Which slides a beat puts on screen: the content slide, then (for the demo)
 * its Where-on-Fourm focus slide. Slide ids are stable across the two cuts,
 * so one table serves both; the renderer skips a slide the cut left out.
 */
export const BEAT_SLIDES: Record<string, BeatSlides> = {
  '00·01': { slide: 'hub' },
  '00·02': { slide: '00·02' },
  '00·04': { slide: '00·04·W' },
  '01·01': { slide: '01·01' },
  '01·02': { slide: '01·02' },
  '01·03': { slide: '01·03' },
  '01·04': { slide: '01·04' },
  '01·05': { slide: '01·05' },
  '01·07': { slide: '01·06' },
  '02·01': { slide: '02·01' },
  '02·02': { slide: '02·02' },
  '02·03': { slide: '02·03', demoSlide: '02·03·W' },
  '02·04': { slide: '02·04', demoSlide: '02·04·W' },
  '02·05': { slide: '02·05' },
  '02·06': { slide: '02·06' },
  '02·08': { slide: '02·07' },
  '03·01': { slide: '03·01' },
  '03·02': { slide: '03·02', demoSlide: '03·02·W' },
  '03·03': { slide: '03·03', demoSlide: '03·03·W' },
  '03·04': { slide: '03·04', demoSlide: '03·04·W' },
  '03·06': { slide: '03·05' },
  '04·01': { slide: '04·01' },
  '04·02': { slide: '04·02', demoSlide: '04·02·W' },
  '04·03': { slide: '04·03', demoSlide: '04·03·W' },
  '04·04': { slide: '04·04' },
  '04·06': { slide: '04·05' },
  '05·01': { slide: '05·01' },
  '05·02': { slide: '05·02', demoSlide: '05·02·W' },
  '05·03': { slide: '05·03', demoSlide: '05·03·W' },
  '05·05': { slide: '05·04' },
  '06·01': { slide: '06·01' },
  '06·02': { slide: '06·02' },
  '06·03': { slide: '06·03', demoSlide: '06·03·W' },
  '06·04': { slide: '06·04', demoSlide: '06·04·W' },
  '06·05': { slide: '06·05', demoSlide: '06·05·W' },
  '06·07': { slide: '06·06' },
  '07·01': { slide: '07·01' },
  '07·02': { slide: '07·02', demoSlide: '07·02·W' },
  '07·03': { slide: '07·03' },
  '07·04': { slide: '07·04', demoSlide: '07·04·W' },
  '07·05': { slide: '07·05' },
  '07·07': { slide: '07·06' },
  '08·01': { slide: '08·01' },
  '08·02': { slide: '08·02', demoSlide: '08·02·W' },
  '08·03': { slide: '08·03' },
  '08·04': { slide: '08·04' },
  '08·06': { slide: '08·05' },
  '09·01': { slide: '09·01' },
  '09·04': { slide: '09·02' },
};
